### ISSUE TITLE
Support for LayerControl

### ISSUE THREAD

**Issue by marcorivm** [KoRiGaN/Vue2Leaflet#101]
### Description

When using multiple LayerTiles it convenient to group them using layerControl options, are you thinking about implementing this component too?

#### Live Demo

http://leafletjs.com/examples/layers-control/

**Comment by KoRiGaN** [comment]
Hi @marcorivm,

I do not work on this yet and I don't think I will have time in the next few weeks.

Feel free to create a pull request if you have some implementation for this.

Cheers,
Mickaël

**Comment by marcorivm** [comment]
Hey @KoRiGaN, thanks for answering, I'll submit the pull request sometime this week then.

**Comment by KoRiGaN** [comment]
Also related to #41

**Comment by KoRiGaN** [comment]
Hi @marcorivm,  

Controls like Layers are now implemented in v1.0.1.

Let me know if it solves your issue.

Micka
