### ISSUE TITLE
Permanent label on markers

### ISSUE THREAD

**Issue by Fillah** [KoRiGaN/Vue2Leaflet#102]
Hey

In Leaflet it's now possible to add a permanent label on markers. you bind the marker to a tooltip, where the permanent presents, like the following: 

`marker.bindTooltip("My Label", {permanent: true, className: "my-label", offset: [0, 0] });`

Example:
[Stackoverflow question](https://stackoverflow.com/questions/34775308/leaflet-how-to-add-a-text-label-to-a-custom-marker-icon)

Is it possible to do the same with Vue2Leaflet?

I'm trying to bind a number on all of my markers on the map, so the user can see it without opening a popup window.

My code for repeating markers on the map:

```
<div v-for="item in markers">
      <v-marker :lat-lng="item.coordinates">
             <v-popup :content="item.popup"></v-popup>
       </v-marker>
</div>
```

Thanks in advance

**Comment by KoRiGaN** [comment]
How about this [example](https://jsfiddle.net/ww5jngyu/)?

Micka

**Comment by Fillah** [comment]
That could work, I think. Thanks for replying!

 Can you use both the popup and tooltip on the same element? So the tooltip says “1” and the popup says “popup content”?

**Comment by KoRiGaN** [comment]
Yes I thinks so.

**Comment by Fillah** [comment]
@KoRiGaN is it possible to make a custom marker with a tooltip inside the marker?
To illustrate what i mean, look at this example:

![example](https://user-images.githubusercontent.com/15626471/33476762-720a2caa-d683-11e7-873e-558ed6eba29f.PNG)

The marker is a circle with a custom fill color and a number inside, which should be the tooltip.
Do you think this is possible? If so, can you make an example?

**Comment by KoRiGaN** [comment]
@Fillah,

You can use plugins like [this](https://github.com/lvoogdt/Leaflet.awesome-markers) to customize marker.
As far as I know, it doesn't exist in Leaflet directly.

Hope this helps,

Micka
