### ISSUE TITLE
[Documentation] Many features are undocumented / API unclear

### ISSUE THREAD

**Issue by fdenzer** [KoRiGaN/Vue2Leaflet#104]
Hi,
so i was looking for onclick-Handlers for my markers. The Wiki redirects to nothings. The readme does not list much in the way of an API.

I finally found `l-click` in the MultiMap.vue-example, yet still feel frustrated: how am I supposed to find the pendant for each and every leaflet functionality? Where could this be placed best, e.g. by opening a Wiki, elaboration on examples or in a tabular section of the ReadMe.md?

## PS

Not only examples, but this issues tracker seems to contain some of the API references:
[Issue 29](https://github.com/KoRiGaN/Vue2Leaflet/issues/29) ist about events-API, and thereby includes an implicit solution to my problem.
(and is thereby non-searchable by words like click handler, on-click, `@`click)

Still the issues section does not seem like the best way to find features.

**Comment by KoRiGaN** [comment]
Hi,

The documentation is not perfect, I agree. You can find this in the readme (Faq section) : 

> How can I bind events of Vue2Leaflet components ?
> 
> All event binding can be done to event called l-[leaflet_event], where [leaflet_event] is the name of the event from leaflet documentation.
> 
> For example if you want to bind to leaflet marker move event, you can bind to Vue2Leaflet.Marker l-move event.
```
<div id="app" style="height: 100%">
  <v-map :zoom=13 :center="[47.413220, -1.219482]">
     <v-tilelayer url="http://{s}.tile.osm.org/{z}/{x}/{y}.png"></v-tilelayer>
     <v-marker :lat-lng="[47.413220, -1.219482]" @l-move="doSomething"></v-marker>
   </v-map>
 </div>
```
I wish I could make a better documentation but don't have much time. I'm open to pull request though :-)

**Comment by fdenzer** [comment]
Thank you for a quick response.
Withdrawn. For now 😈
