### ISSUE TITLE
When setting bounds: TypeError: t.isValid is not a function

### ISSUE THREAD

**Issue by psychosis448** [KoRiGaN/Vue2Leaflet#107]
When setting bounds it throws a type error  
 **t.isValid is not a function**
``` javascript
    <template>
    <div>
    <v-map :bounds="bounds"></v-map>
    </div>
    </template>
    
    <script>
    export default {
      name: 'LeafLet',
      data () {
        return {
          bounds: [[47.262943, 6.030290], [55.093354, 14.909721]]
      }
    }
    </script>
```

#### Actual Results

```
TypeError: t.isValid is not a function
    at VueComponent.setBounds (vue2-leaflet.min.js?31d2:1)
    at VueComponent.boundFn [as setBounds] (vue.esm.js?efeb:188)
    at VueComponent.mounted (vue2-leaflet.min.js?31d2:1)
    at callHook (vue.esm.js?efeb:2868)
    at Object.insert (vue.esm.js?efeb:4045)
    at invokeInsertHook (vue.esm.js?efeb:5806)
    at Vue$3.patch [as __patch__] (vue.esm.js?efeb:6025)
    at Vue$3.Vue._update (vue.esm.js?efeb:2613)
    at Vue$3.updateComponent (vue.esm.js?efeb:2741)
    at Watcher.get (vue.esm.js?efeb:3084)
```
### Browsers Affected

- [x] Chrome

### Versions
- Leaflet: v1.2.0
- Vue: v2.5.2
- Vue2Leaflet: v0.0.57

**Comment by mhsystem** [comment]
Hello, same problem, any sollution?

**Comment by psychosis448** [comment]
Not yet -- but I'm going to look into it next week & let you know if I can solve it.

**Comment by mhsystem** [comment]
I have solution:
<v-map v-bind:zoom="zoom" :center="center"   ref="mapa" :bounds="bo" >

  for (var i = 0; i < response.data.length; i++)
            {
        var item=response.data[i]
        var ppol=[];       
        var ma=L.latLng(parseFloat(item.lan),parseFloat(item.lot))
        trippoints.push(ma)
            }
this.bo=L.latLngBounds(this.trippoints)

**Comment by psychosis448** [comment]
@mhsystem   
Where does your code snippet go?  
I don't get at what ajax call your 'response' points...

**Comment by mhsystem** [comment]
Respondentů.data is json array od {“lan”:xxx,”lot”:yyy}

**Comment by mhsystem** [comment]
Sorry response.data is json... 😀

**Comment by psychosis448** [comment]
That's clear.  
But json array of what?  
Regarding the example above.

**Comment by psychosis448** [comment]
@mhsystem could you elaborate where your code snippet goes & what it does?

**Comment by KoRiGaN** [comment]
@mhsystem  @psychosis448 Vue2Leaflet was not able to manage raw array as bounds but this issue should now be fixed in 0.0.58.

Let me know if it works for you.

Micka

**Comment by KoRiGaN** [comment]
Closing as no answer for a while

**Comment by psychosis448** [comment]
Works fine now! Thx :)
