### ISSUE TITLE
Invalid key "custom" in validation rules object for prop "XYZ".

### ISSUE THREAD

**Issue by Ankit-Dave** [KoRiGaN/Vue2Leaflet#109]
### Description
When importing components vue esm is giving warnings as custom is not valid prop key.
as they have added the check for "warn misspelled keys on prop validation object"
https://github.com/vuejs/vue/commit/d02bb37efb3c4ee14b8cf9db22d1ab3340ba2c0f

#### Steps to Reproduce
Use vue: v2.5.11
https://github.com/vuejs/vue/releases

### Browsers Affected

- [.] Chrome
- [.] Firefox
- [.] Edge
- [.] Safari 9
- [.] Safari 8
- [.] IE 11

### Versions
- Leaflet: v1.2.0
- Vue: v2.5.11
- Vue2Leaflet: v0.0.57

**Comment by wuxiashuangji** [comment]
[](url)
![qq 20171215191345](https://user-images.githubusercontent.com/21117027/34039831-1f0a09fe-e1cc-11e7-9196-216673b635e6.png)

**Comment by fdenzer** [comment]
[vue issue#7198](https://github.com/vuejs/vue/pull/7198) was the ``nonbreaking fix'' that causes the warning to be displayed.

**Comment by asifm** [comment]
Yes, it's happening everywhere. 

I believe it's related to these changes in the new release https://github.com/vuejs/vue/releases

**Bug Fixes**

avoid unnecessary lowercase coersion in component name validation 3f0c628, closes vuejs/vue#7237

**Improvements**

warn misspelled keys on prop validation object (#7198) d02bb37, closes vuejs/vue#7198

**Comment by KoRiGaN** [comment]
Yet it seems the Vue now check properties to look exactly like in the documentation says no more.

Vue2Leaflet is using a key called "custom" in the property in order to bind it to the method of the Vue2Leaflet object or the method of the underlying leaflet object.

It seems that you can no longer do that with Vue.

I think I need to find a new way of doing this...
You can still use Vue v2.5.10 in the meanwhile.

Mickaël

**Comment by alexcode** [comment]
@asifm @KoRiGaN, the props validation has been remove in Vuejs v2.5.13 as per this [diff](https://github.com/vuejs/vue/commit/01c07503bf6af902dde06fafa8a0008ee3e303aa#diff-93a422db7b74c2c7c3d7563688c7d5d9).

**Comment by KoRiGaN** [comment]
Closing as it should no longer be an issue with the last vue version.
