### ISSUE TITLE
Cant run examples

### ISSUE THREAD

**Issue by VadimCpp** [KoRiGaN/Vue2Leaflet#114]
Cannot run examples.

#### Steps to Reproduce

``` bash
# Clone the repo
git clone https://github.com/KoRiGaN/Vue2Leaflet.git

# Go to examples folder
cd Vue2Leaflet

# Run demo at localhost:8080
$ npm link
$ cd examples
$ npm link vue2-leaflet
$ npm install
# serve with hot reload at localhost:8080
$ npm run dev
```

#### Error

 ERROR  Failed to compile with 15 errors                                                                      12:40:18 PM

This dependency was not found:

* vue2-leaflet in ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0&bustCache!./src/components/MarkerPopupExample.vue, ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0&bustCache!./src/components/CRSAndImageOverlay.vue and 13 others

To install it, you can run: npm install --save vue2-leaflet

#### Details

``` bash
node --version
v9.3.0

npm --version
5.6.0
```

**Comment by KoRiGaN** [comment]
Please follow the "Run demo locally" section of the Readme.

Let me know if it helps.

**Comment by VadimCpp** [comment]
I did.

No success :(

**Comment by KoRiGaN** [comment]
Did you build it first? 

In the main folder :

npm install
npm run build

**Comment by VadimCpp** [comment]
I did.

There is an error while npm install:

```
MacBook-Pro:examples anon$ npm install

> fsevents@1.1.2 install /Users/anon/Work/tools/Vue2Leaflet/examples/node_modules/fsevents
> node install

node-pre-gyp ERR! Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.2/fse-v1.1.2-node-v59-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.1.2 and node@9.3.0 (node-v59 ABI) (falling back to source compile with node-gyp) 
```

Maybe this one is the reason of the error:

```
 ERROR  Failed to compile with 15 errors                                                                       3:18:54 PM

This dependency was not found:

* vue2-leaflet in ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0&bustCache!./src/components/MarkerPopupExample.vue, ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0&bustCache!./src/components/CRSAndImageOverlay.vue and 13 others

To install it, you can run: npm install --save vue2-leaflet
> Listening at http://localhost:8080

```

**Comment by VadimCpp** [comment]
There is definitely should be an easier way to run examples. I would like to contribute.

**Comment by lucky06688** [comment]
I‘ve had the same issue. But fortunately I've solved it just run **npm install --save vue2-leaflet**

**Comment by KoRiGaN** [comment]
Hi @VadimCpp,

I found two issues here:
1. You use an up to date version of node and npm and fsevents package was outdated and not compatible with your version.

=> I've updated outdated package in this project and it should now build correctly.

2. How I used to link vue2-leaflet package doesn't seem to work (don't know if it is related to new npm version):
```
$ npm link vue2-leaflet
$ npm install
```
This removes the linked vue2-leaflet when doing npm install.
=> You should link the package after installing dependencies:
```
$ npm install
$ npm link vue2-leaflet
```
I've updated the README accordingly.

Let me know if this helps.

Micka

**Comment by VadimCpp** [comment]
Hi, @KoRiGaN 

I was able to start up example successfully.
Everything works good now.
Thank you.
