### ISSUE TITLE
Unknown warnings

### ISSUE THREAD

**Issue by VadimCpp** [KoRiGaN/Vue2Leaflet#115]
After setting up vue2-leaflet in my application I am getting warnings in the console:

[Vue warn]: Invalid key "custom" in validation rules object for prop "attribution".
[Vue warn]: Invalid key "custom" in validation rules object for prop "detectRetina".
[Vue warn]: Invalid key "custom" in validation rules object for prop "paddingBottomRight".

This probably should be fixed

UPD: it has connection to VMap props

**Comment by KoRiGaN** [comment]
Closing as a duplicate of #109.
