### ISSUE TITLE
Greyscale

### ISSUE THREAD

**Issue by nexequ** [KoRiGaN/Vue2Leaflet#116]
I would like to ask if there is any possibility to turn on greyscale like here:
http://leafletjs.com/examples/layers-control/

**Comment by KoRiGaN** [comment]
Hi @nexequ,

Yes, it's possible.

In this example, the provider of the tile is MapBox so you need to add a tilelayer to your map that uses Mapbox greyscale tiles. 
`
<v-tilelayer :url="url" :attribution="attribution" :token="token"></v-tilelayer>
`

Let me know if it helps.

**Comment by KoRiGaN** [comment]
Closing as no answer for a while

**Comment by ilmars** [comment]
you can use: https://cartodb-basemaps-a.global.ssl.fastly.net/#3/24.29/-3.87
