### ISSUE TITLE
Draw Circle

### ISSUE THREAD

**Issue by Jehanramadhan** [KoRiGaN/Vue2Leaflet#117]
Is there any example or is possible i draw a circle with Vue2Leaflet?

**Comment by kino90** [comment]
Look at the [LCircle](https://github.com/KoRiGaN/Vue2Leaflet/blob/master/src/components/LCircle.vue) component:

```
<v-circle :lat-lng="circle.coords"
    :radius="500"
    :opacity=".2"
   [...]
 />
```

**Comment by KoRiGaN** [comment]
Thanks @kino90 for the answer.

@Jehanramadhan did kino90 explanation fixed your issue?

**Comment by KoRiGaN** [comment]
Closing as no answer for a while
