### ISSUE TITLE
GeoJson vuex not working rendered through onEachFeature

### ISSUE THREAD

**Issue by verediongzon** [KoRiGaN/Vue2Leaflet#120]
I am trying to access the data from vuex with the GeoJson but cannot access it. Cannot map all existing vuex storage.

The component is rendered through onEachFeature attribute for GeoJson. I'm trying to accomplish an update at vuex state with the popup rendered by this onEachFeature.

Do you have any idea on how to access it or some resolution for this?

**Comment by KoRiGaN** [comment]
Hi @verediongzon,

You should be able to display data from Vuex into Vue2Leaflet.

Very hard to tell what is your problem in your specific case using Vuex, Vue2Leaflet and Leaflet.
Could you make a running example using jsfiddle or a public repo?

This would help to understand your problem.

Micka

**Comment by KoRiGaN** [comment]
Closing as no answer for a while
