### ISSUE TITLE
Add additional plugin for Vue2Leaflet

### ISSUE THREAD

**Issue by yellowcap** [KoRiGaN/Vue2Leaflet#121]
Hi

I wrote a plugin to add vector tile protobuffer layers to Vue2Leaflet.

https://github.com/tesselo/vue2-leaflet-vectorgrid

The plugin is similar to the other two existing ones. Please consider adding the plugin to the list in the README file.

Thanks,

Daniel

**Comment by KoRiGaN** [comment]
Hi @yellowcap,

I've added your plugin in the plugin section of the readme.

Good to see more plugins being developed!

Micka

**Comment by yellowcap** [comment]
Awesome, thanks!

**Comment by chemoral87** [comment]
please, add this plugin.

https://github.com/mad-gooze/Leaflet.Arc
