### ISSUE TITLE
how to use popup

### ISSUE THREAD

**Issue by alexbigdic** [KoRiGaN/Vue2Leaflet#122]
#### Live Demo

http://jsfiddle.net/Boumi/k04zpLx9/

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions
- Leaflet: vX.X.X
- Vue: vX.X.X
- Vue2Leaflet: vX.X.X

**Comment by KoRiGaN** [comment]
Hi @alexbigdic,

Could you please explain what is your issue more clearly?

You can have a look at the examples folder where you will find many code example and some using popups.

 Micka
