### ISSUE TITLE
Default tag name for components

### ISSUE THREAD

**Issue by manelclos** [KoRiGaN/Vue2Leaflet#124]
Is there any reason why the Vue2Leaflet components don't have a default tag name like:

```
export default {
  name: 'v-map',
```

Then I could just do

```
import Vue2Leaflet from 'vue2-leaflet'

export default {
  components: {
    Vue2Leaflet.Map,
```

or:

```
import {Map, TileLayer} from 'vue2-leaflet'

export default {
  components: {
    Map,
    TileLayer,
```

Also, when choosing the default tag name, it would be nice to use 'l-map' as you already use the 'l-' prefix for events.

I offer myself to do the boring task of adding the default tag names :)

**Comment by KoRiGaN** [comment]
Hi @manelclos , @kino90,  

All defaults tag names are now set in v1.0.1.
However, component name and event name have been changed in this major version.
All Component are prefixed with L, LMarker for example.
All Event names are now the same as the one in Leaflet (no l-[event-name] required).

Let me know if it solves your issue.

Micka

**Comment by manelclos** [comment]
Looks great! I'll be checking soon!

**Comment by KoRiGaN** [comment]
Closing as no comments for 3 weeks.
Please reopen this issue if it not solved yet.
