### ISSUE TITLE
Map options regression from 0.0.57 to 0.0.58

### ISSUE THREAD

**Issue by manelclos** [KoRiGaN/Vue2Leaflet#126]
### Description
Consider this simple map with *dynamic* markers:

```
    <div class="center-row">
      <v-map ref='map' :zoom='15' :center="[41.973, 2.780]"
             :options='{zoomControl: false}' @l-ready='onMapReady'>
        <v-marker v-for="item in markers" :key="item.id" :lat-lng="item.latlng">
        </v-marker>
      </v-map>
    </div>
```

Looks like when a marker is added, v-map is reevaluated and it tries to call setOptions, which will fail for Map, there is no such function. The Javascript error is:

```
vue.js:1451 TypeError: leafletElement.update is not a function
    at VueComponent.vueElement.$watch.deep (propsBinder.js?3fb7:26)
```

#### Live Demo
Check this fiddle with the console opened. It is using 0.0.58. An error is produced when after 2 seconds a marker is added. Change vue2-leaflet version to 0.0.57 and see how the problem stops.
http://jsfiddle.net/manelclos/sqe8c741/

#### Expected Results
No error thrown, this is causing other code to abort.

#### Actual Results
Exception is thrown.

### Browsers Affected
- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions
- Leaflet: v1.3.1
- Vue: v2.2.5
- Vue2Leaflet: v0.0.58

**Comment by KoRiGaN** [comment]
Seems like a bug. Will try to have a look at it.

Micka

**Comment by manelclos** [comment]
Hi, changing the vue2-leaflet version to 0.0.60 in the jsfiddle test fixes the problem.

Thanks!
