### ISSUE TITLE
Request: change zoom control position

### ISSUE THREAD

**Issue by rbrtmrtn** [KoRiGaN/Vue2Leaflet#129]
This is just a request to be able to change the zoom control position. Or can you already do that? I didn't see anything in the code that alluded to it.
Thanks!

**Comment by rbrtmrtn** [comment]
Hi @manelclos , thanks for the comment. I ended up putting something similar in the `mounted` hook for that component. Unfortunately, the method in #125 doesn't work (AFAIK) since the Leaflet map constructor doesn't have an option for where to put the zoom control. I'll go ahead and close this out.

**Comment by bportesio** [comment]
I've changed the class name of Zoom Tool 
methods: {
   addZoomControl() {
         const zoomControl = this.$el.querySelector('.leaflet-top.leaflet-left');
         zoomControl.className = 'leaflet-bottom leaflet-right';
   },
}

mounted () {
    this.addZoomControl();
},
