### ISSUE TITLE
Getting map state (center + zoom) in real time does not work

### ISSUE THREAD

**Issue by purell** [KoRiGaN/Vue2Leaflet#130]
#### Live Demo

http://jsfiddle.net/czahx9k6/2/

#### Steps to Reproduce
Move and zoom the map with the mouse and the printed coordinate will not be updated.

#### Expected Results

As the `center` and `zoom` variable has been pass with the vue-js modifier `.sync`, I would have expected them to be updated in **real time**.

The only work around I found is the use a `setInterval` and query the map

```js
setInterval(() => {
    const ret = {
      center: this.$refs.deviceMap.mapObject.getCenter(),
      zoom: this.$refs.deviceMap.mapObject.getZoom(),
      bound: this.$refs.deviceMap.mapObject.getBounds(),
    };
    this.mapState = ret;
  }
}, 500);
```

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions
- Leaflet: v1.3.1
- Vue: v2.5.13
- Vue2Leaflet: v0.0.58

**Comment by KoRiGaN** [comment]
Hi @purell,

The binding for the moment is only one way (from parent to child).
As in the [example](https://github.com/KoRiGaN/Vue2Leaflet/blob/master/examples/src/components/Example.vue) you can listen to events on the map like zoomanim to update the zoom.

I didn't know about the .sync in Vue Js and it seems pretty easy to emit some updates when some event happens (like zoomanim in the previous example).
I agree that it requires some knowledge of Leaflet and work to get the value updated correctly and would like to make it easier.
It also has to be consistent across components in order for the user not to be confused.

From my point of view here are the values that must be kept in sync:

- Map => center, zoom, bounds
- Marker => position 

What do you think?

Micka

**Comment by purell** [comment]
Hi @KoRiGaN, 

I used to see reactive vue-js components. So they internally use the vue-js [two-way binding](https://vuejs.org/v2/guide/components.html#sync-Modifier) to update their bounded props values when it matter. In this case, I would have hoped to see the `center` and` zoom` to be updated in real time. I mean, without having to call a function with the help of an interval or a timeout. This is where I'm a little bit confused.

I unfortunately used an interval as I don't have time to create a PR for Vue2Leaflet. But If I had time I would certainly start looking at subscribe to Leaflet [LocationEvent](http://leafletjs.com/reference-1.3.0.html#event-objects) and then [update](https://vuejs.org/v2/guide/components.html#sync-Modifier) the bounds props of the Vue2Leaflet components. But I'm not sure if Leaflet expose event to get `center` and `zoom`.

> From my point of view here are the values that must be kept in sync:
>
>* Map => center, zoom, bounds
>* Marker => position

I'm totally agree with you ;)

**Comment by KoRiGaN** [comment]
Hi @purell,

This should now work in v0.0.60.
Only zoom will need the 'sync' modifier as others (marker position, map center and bounds) are object and value are updated inside them automatically.

Hope this helps,

Micka

**Comment by KoRiGaN** [comment]
Closing as no comments for 3 weeks.
Please reopen this issue if it not solved yet.
