### ISSUE TITLE
how to change the angle of the marker

### ISSUE THREAD

**Issue by SupriyaSudhindra** [KoRiGaN/Vue2Leaflet#131]
Hi,
I want to show the direction of movement of my custom icon. So I want to change the rotate the icon in certain angle. Can you please suggest me how to implement it?

**Comment by jezzerarsenio** [comment]
i use plugin Leaflet.RotatedMarker for doing that job.

**Comment by SupriyaSudhindra** [comment]
can you please explain how to use it?

**Comment by jezzerarsenio** [comment]
visit Leaflet.RotatedMarker github repo,
you can look in the example section.

**Comment by SupriyaSudhindra** [comment]
i have seen the plugin...I tried implementing in vue2-leaflet....didnt work...so asked?

**Comment by KoRiGaN** [comment]
Hi @SupriyaSudhindra,

Leaflet don't have many options to customise markers.
As  @jezzerarsenio suggested you should use plugins like Leaflet.rotated markers.

@SupriyaSudhindra you should give an example of what you tried and why doesn't work so we can give help.
This is a plugin for Leaflet, maybe it is better to ask for help on their repository.

In the meanwhile, I tried it [here](https://jsfiddle.net/Lbgyes4e/4/) and it works as expected.

Please close this issue if this example solves your problem.

Cheers,

Micka

**Comment by SupriyaSudhindra** [comment]
Thanks @jezzerarsenio and @KoRiGaN ...it worked
