### ISSUE TITLE
Can not (how to) reach tooltip object

### ISSUE THREAD

**Issue by sangdth** [KoRiGaN/Vue2Leaflet#133]
In FAQ, it said that I can reach map and other component objects by using this way:

`this.$refs.map.mapObject;`
> This also works for any other component (Marker, Polyline, etc...)

It works perfectly with map, but when I try to get tooltip object, I got empty.
```
this.$refs.leaftooltip.mapObject; // return empty, can not apply any method on it.
this.$refs.leaftooltip            // return undefined
```
Please help me how to do it. I need it because I want to run `setToolTipContent()`, how can I archive it with Vue2Leaflet?

**Comment by KoRiGaN** [comment]
Hi @sangdth,

Vue refs are only available once the "mounted" step of the lifecycle.  As the tooltip is not displayed it is not yet mounted.

If you want to update the tooltip content, why don't you bind the content property of tooltip?

Hope this helps.

Micka

**Comment by KoRiGaN** [comment]
Hi @sangdth,

Closing this as no answer for a while.

Micka

**Comment by sangdth** [comment]
Thank you, KoRiGan, the tooltip is now working as expected.
