### ISSUE TITLE
Update on npm

### ISSUE THREAD

**Issue by timwis** [KoRiGaN/Vue2Leaflet#136]
Hi! I'm trying to use the new feature from eb4d2890129de0d700a8533a18561fb6e097fe15 that lets me pass a custom tile layer class (great idea!). But it seems the version in the npmjs registry doesn't have that feature. I think you may have forgotten to increment the version number and publish?

EDIT: I think this also involves updating the `dist/` directory, as I can't use this feature even if I install the repo directly from github. Unless I point to `src/`, which requires transpiling it.

**Comment by KoRiGaN** [comment]
Hi @timwis,

Yes, it's not published yet. I have fixed some issues and merge some PR since the last release.

I have one more issue to fix before testing and releasing a new version.
I hope I can do it in the next couple of days.

Micka

**Comment by timwis** [comment]
All right -- it would be great if there were a way to use it in the meantime, but not sure how. I'll keep checking to see when it's published then. Thanks for your work on it!

**Comment by KoRiGaN** [comment]
Hi @timwis,

A new version is available on npm that include the PR you were watching.

Hope this helps.

Micka

**Comment by timwis** [comment]
Woohoo! Thanks

**Comment by timwis** [comment]
Say, have you got an example of it working with `tileLayerClass`? It doesn't seem to be working with esri-leaflet's `TiledMapLayer` class :/
