### ISSUE TITLE
error on defferedMountedTo, _ is not defined

### ISSUE THREAD

**Issue by davidverriere** [KoRiGaN/Vue2Leaflet#14]
Hi,
I have an issue when map is mounted : 
deferredMountedTo: function deferredMountedTo(parent) {
	      this.$tileLayer.addTo(parent);
	     => _.forEach(this.$children, function (child) {
	        child.deferredMountedTo(that);
	      });
	    }
![image](https://cloud.githubusercontent.com/assets/6039093/23340397/c2e14ee8-fc35-11e6-89c3-b895a93d7ecb.png)

I don't understand why lodash is not present.

**Comment by davidverriere** [comment]
I do this dirty fix in my app 
` window._ = require('lodash');`

**Comment by KoRiGaN** [comment]
Hi,

Thanks for having raised that issue.
The problem was that lodash was not requiered correctly on all component so you could end up having lodash not defined when using some components only.

Lodash was only used for few forEach so I removed it as a dependancie

**Comment by davidverriere** [comment]
Thanks
