### ISSUE TITLE
Will we support DomUtil?

### ISSUE THREAD

**Issue by sangdth** [KoRiGaN/Vue2Leaflet#140]
I would like to use `L.DomUtil` functions, what is the best way to do inside Vue components? In case you can not make it, could you show me how to make work with Vue2Leaflet?

Thanks.

**Comment by KoRiGaN** [comment]
Hi @sangdth,

I'm not familiar with L.DomUtil but as Vue2Leaflet is just a wrapper you can use them.
L.DomUtil are just functions and don't require any Vue components.

Micka

**Comment by sangdth** [comment]
I avoided to use DomUtil, so I close this.
