### ISSUE TITLE
v-if和v-show标签对v-tilelayer组件无效 （V-if and V-show labels are invalid for V-tilelayer components）

### ISSUE THREAD

**Issue by a750183047** [KoRiGaN/Vue2Leaflet#141]
你好
      v-if和v-show标签对v-tilelayer组件无效，无法动态的改变它的显示和不显示的状态。

Hello there
       The v-if and v-show tags have no effect on the v-tile layer component and cannot dynamically change its display and non-display state.

**Comment by KoRiGaN** [comment]
Hi @a750183047,

v-if and v-show just add a class to the template of the component for it not to be displayed.
However, most Leaflet elements don't have any template like tile layer so it have no effect.

With Vue2Leaflet you will be able to use a visible property on all layers component.
This is already available for most of the component and will be available in the next release for tilelayer.

Hope this helps,

Micka

**Comment by KoRiGaN** [comment]
Hi @a750183047,
Visible property in tilelayer is now available in v1.0.1.

Micka

**Comment by KoRiGaN** [comment]
Closing as no comments for 3 weeks.
Please reopen this issue if it not solved yet.
