### ISSUE TITLE
Support base Control class

### ISSUE THREAD

**Issue by manelclos** [KoRiGaN/Vue2Leaflet#142]
### Description
The base class L.Control is not wrapped. Once wrapped you could create controls in VueJS.

#### Expected Results
Being able to create to create a Vue component that "extends" Control base class/component.

#### Actual Results
I'm manually creating the leaflet Control and "linking" the onAdd method, which seems to be enough:

```
  ...
  mounted () {
    this.mapObject = new L.Control()
    this.mapObject.onAdd = this.onAdd
  },
  deferredMountedTo (parent) {
  ...
```

### Versions
- Leaflet: v1.3.1
- Vue: v2.5.13
- Vue2Leaflet: v0.0.58

**Comment by wishinghand** [comment]
@manelclos Can you go more into how you're making custom controls?

**Comment by manelclos** [comment]
@wishinghand see one example here:

https://github.com/giscube/giscube-geoportal-vuejs/blob/master/src/components/LayersControl.vue

deferredMountTo could be lighter (moving 'l-add' binding out of it).

**Comment by DonNicoJs** [comment]
Closing this since l-control is inside the codebase since a while
