### ISSUE TITLE
Vue2Leaflet polyline error: Error in mounted hook: "TypeError: Cannot read property 'x' of undefined"

### ISSUE THREAD

**Issue by oblomki** [KoRiGaN/Vue2Leaflet#144]
### Description
Any attempt to add a Polyline results in an error, "Error in mounted hook: "TypeError: Cannot read property 'x' of undefined"

Although I've encountered this in my much more complicated app, this is also replicated in a simple JS Fiddle, below, using the most basic code from the Vue2Leaflet examples to add a polyline.

If I use Leaflet JS directly, i.e. without Vue2-leaflet, I am able to create polylines as usual. The problem seems to be with Vue2-Leaflet. 

This was not happening with an earlier version of Vue2-leaflet (0.0.58 with Leaflet 1.2.0).

#### Live Demo

https://jsfiddle.net/hp9o4d19/ - basic example WITHOUT polyline - works

https://jsfiddle.net/p3pxanhe/ - same example WITH polyline - won't actually load, probably because of the error, but remove the polyline component and it will work as normal.

#### Steps to Reproduce
Add a polyline element to the template, add latlngs object.

#### Expected Results
Expected result is a polyline plotted according to the lat-lngs supplied.

#### Actual Results

vue.esm.js?efeb:1741 TypeError: Cannot read property 'x' of undefined
    at Bounds.intersects (leaflet-src.js?9eb7:1053)
    at NewClass._clipPoints (leaflet-src.js?9eb7:8207)
    at NewClass._update (leaflet-src.js?9eb7:8252)
    at NewClass._reset (leaflet-src.js?9eb7:7760)
    at NewClass.onAdd (leaflet-src.js?9eb7:7708)
    at NewClass._layerAdd (leaflet-src.js?9eb7:6487)
    at NewClass.whenReady (/app/electron/node_modules/leaflet/dist/leaflet-src.js:4367)
    at NewClass.addLayer (/app/electron/node_modules/leaflet/dist/leaflet-src.js:6549)
    at NewClass.addTo (leaflet-src.js?9eb7:6429)
    at VueComponent.deferredMountedTo (/app/electron/node_modules/vue2-leaflet/dist/vue2-leaflet.min.js:1)
    at VueComponent.mounted (/app/electron/node_modules/vue2-leaflet/dist/vue2-leaflet.min.js:1)
    at callHook (vue.esm.js?efeb:2921)
    at Object.insert (vue.esm.js?efeb:4158)
    at invokeInsertHook (vue.esm.js?efeb:5960)
    at VueComponent.patch [as __patch__] (vue.esm.js?efeb:6179)
    at VueComponent.Vue._update (vue.esm.js?efeb:2670)

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [ ] Edge
- [x] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions
- Leaflet: v1.3.1 (also 1.2.0, possibly others)
- Vue: v2.5.16
- Vue2Leaflet: v0.0.60

**Comment by KoRiGaN** [comment]
Hi @oblomki,

I can't reproduce your issue.
Both you JSFiddle don't work because vue2leaflet is loaded before leaflet.
If I just load vue2leaflet last in both your examples, the 2 examples works.

I never get the "TypeError: Cannot read property 'x' of undefined".

Hope this helps,

Micka

**Comment by oblomki** [comment]
Hi Micka,

Yes, I realised that myself, was going to update the Fiddle with reordered scripts and realised that the polyline works there too. 

So it's something to do with my own environment, but I can't understand what: even the most basic example, the same as in the Fiddle, produces the "TypeError: Cannot read property 'x' of undefined" error described. I'll have to keep digging, but so far I'm baffled.

Thanks a lot for your work, btw.

**Comment by oblomki** [comment]
This error went away as unexpectedly as it came. Closing this, thanks for your help and for the excellent component.

**Comment by chaogis** [comment]
Did you solve the problem? I met the problem today, version of vue2-leaflet is 1.2.3-beta.9 and i import L from 'vue2-leafelt', which export it out.
![image](https://user-images.githubusercontent.com/32628057/52994740-86341180-3453-11e9-9bce-5352eeae17ec.png)

Hope you answer, thank you. @ikmolbo @KoRiGaN

**Comment by lordfuoco** [comment]
@chaogis check #281  and this line of the faq: https://korigan.github.io/Vue2Leaflet/#/faq/?id=why-am-i-getting-weird-errors-for-things-that-work-fine-in-the-demos
