### ISSUE TITLE
v-tilelayer components added using v-for over an async array do not render

### ISSUE THREAD

**Issue by mikeu** [KoRiGaN/Vue2Leaflet#145]
### Description
If `v-tilelayer` components are added to the map using `v-for` to iterate an array of definitions that was loaded asynchronously, then the layers do not appear on the map.

Loading a single layer definition object asynchronously works as expected. Iterating over an array of pre-existing definitions works as expected. But combining the two approaches, to load an array of definitions asynchronously, does not.

#### Live Demo
https://jsfiddle.net/munderwood/zh699z61/51/

This demo outputs three maps and a status area. The first map uses a single `v-tilelayer` based on a definition that is added asynchronously two seconds after the map mounts. The second uses `v-for` to iterate over an array of layer definitions already available when the page loads. Both of these work.

Four seconds after the map mounts, an array containing a single layer definition is added asynchronously. The third map should show this, but it never renders, even after the status area updates to show that the definition has been loaded and properties from within it are accessible and iterable via `v-for`.

#### Steps to Reproduce
Attempt to include an array of TileLayer components on a map, with definitions read from an array that is populated asynchronously:

```vue
<v-map>
  <v-tilelayer
    v-for="(layer, index) in ajaxLayers"
    :key="index"
    :url="layer.url"
    :attribution="layer.attribution">
  </v-tilelayer>
</v-map>
```

#### Expected Results
Any layers correctly defined within the loaded array should be added, in array order, to the map.

#### Actual Results
The map remains empty. No attribution information is added from the loaded layers. Other reactive elements on the page demonstrate that the data appears to have been loaded correctly.

### Browsers Affected

- [X] Chrome
- [X] Firefox
- [X] Edge
- [?] Safari 9
- [?] Safari 8
- [?] IE 11

### Versions
- Leaflet: v1.3.1
- Vue: v2.5.16
- Vue2Leaflet: v0.0.60

Thank you for your work on this project, and for any help you can provide with this issue.

**Comment by KoRiGaN** [comment]
Hi @mikeu,

Thanks for this details bug report. I will try to investigate as soon as possible.

Micka

**Comment by mikeu** [comment]
Well that was some good timing with the 1.0 release! Whether or not you explicitly address this issue that quickly, the problem is no longer there.

Here's an updated fiddle in which I changed nothing except updating Vue2-Leaflet to 1.0.1, and referencing `LMap` and `LTileLayer` instead of `Map` and `Layer`: https://jsfiddle.net/munderwood/zh699z61/55/

As you can see, all three maps now successfully load their respective tile layers correctly.

**Comment by KoRiGaN** [comment]
Perfect! 
I didn't address this issue directly or even tested it but in v1 I made some changes that make thing more straightforward when loading layers.
😄 happy to see that it also fixed your issue and thanks for giving v1 a try!
