### ISSUE TITLE
Consider using modular lodash

### ISSUE THREAD

**Issue by alexcroox** [KoRiGaN/Vue2Leaflet#15]
A brief look at the components and you only seem to be using loadash's `_.forEach`, consider reducing the dependency size by using the [modular parts of lodash you need](https://www.npmjs.com/package/lodash.foreach) rather than the entire library:

```
import _each from 'lodash.foreach'

_each(events, (eventName) => {...
```

**Comment by KoRiGaN** [comment]
Thanks for that comment. Lodash was great to start quickly by as you noticed is not really a requierement. 

So I removed it as a dependancie.
