### ISSUE TITLE
How to add layer-group into control-layers

### ISSUE THREAD

**Issue by sangdth** [KoRiGaN/Vue2Leaflet#150]
In [official documentation](http://leafletjs.com/examples/layers-control/), Leaftlet shows me to use `L.control.layers(baseMaps, overlayMaps).addTo(map);` to add `baseMaps` and `overlayMaps` to control layer. How can I do that with l-layer-group and l-control-layers?

I checked the example, it has the only `baseMaps` option.

Make an example, I want to add this layer group, it is a set of markers, how do I add another checkbox on control-layers to become `overlayMaps`?

```html
<l-tile-layer
    layerType="base"
    name="Default Base"
    :url="url"
/>
<l-layer-group :visible="sourceVisible">
    <l-marker
         v-for="(item, index) in sources"
         :key="index"
         :lat-lng="[item.coordinates[1], item.coordinates[0]]"
         :icon="sourceIcon(item.icon)"
         @l-click="onClick(item)"
    >
    </l-marker>
</l-layer-group>
```

Thank you.

**Comment by KoRiGaN** [comment]
Hi @sangdth,

The documentation is far from perfect and I want to add many examples of the official documentation to Vue2Leaflet documentation but didn't have the time yet.
You can add overlay to your control like this:
```javascript
<l-contol-layers></l-control-layers>
<l-tile-layer
    layerType="base"
    name="Default Base"
    :url="url"
/>
<l-layer-group :visible="sourceVisible" layerType="overlay" name="Sources">
    <l-marker
         v-for="(item, index) in sources"
         :key="index"
         :lat-lng="[item.coordinates[1], item.coordinates[0]]"
         :icon="sourceIcon(item.icon)"
         @l-click="onClick(item)"
    >
    </l-marker>
</l-layer-group>
```

Let me know if this helps.

Micka

**Comment by mujahidinside** [comment]
Hello @KoRiGaN,
How to add/show all layers in leaflet-control-layers-toggle?
in <l-contol-layers></l-control-layers> no layers show.

**Comment by sangdth** [comment]
Thank you @KoRiGaN, I tried it before posting it here. As you can see, I typed exactly the code, but it only displays the Default Base.

![screen shot 2018-04-04 at 14 22 25](https://user-images.githubusercontent.com/1083478/38304965-d4759bb2-3813-11e8-96dd-f00a1853fc1f.png)

I went to [check the source code](https://github.com/KoRiGaN/Vue2Leaflet/blob/263887d4b886a2d0b1c5e45cc9f0c77f391da2a0/src/components/LLayerGroup.vue#L11), and inside `layer-group` it has only 1 props, it does not have layerType.

Maybe I missed something...

**Comment by KoRiGaN** [comment]
I'm sorry @sangdth, you're right.

It's something I'm working on but is not published yet that should simplify all properties and make all layer components have a name and layerType properties.
I will try to publish it soon. 

In the meanwhile, you can:

- Attach a reference to your control layers (ref="myControl")
- Register an event handler on add event on the different layer that use leaflet addBaseLayer(<Layer> layer, <String> name) and addOverlay(<Layer> layer, <String> name) methods on this.$refs.myControl.mapObject to add them manually.

Hope this helps.

**Comment by KoRiGaN** [comment]
@mujahidinside  does my previous message answer your question?

**Comment by mujahidinside** [comment]
@KoRiGaN ,
Here is my code
![l-control-layers](https://user-images.githubusercontent.com/10596346/38347924-e8fe5750-38b7-11e8-8e7e-cb0871991dfb.PNG)

Here map showing looks good in [leaflet-control-layers]

![without-hower-mouse](https://user-images.githubusercontent.com/10596346/38347956-36c4638a-38b8-11e8-91ce-8d16478be4bf.PNG)

But on hower, it looks like this

![with-mouse-hower](https://user-images.githubusercontent.com/10596346/38347967-50629ece-38b8-11e8-9b4e-7c8fb66c93df.PNG)

Nothing showing.

**Comment by sangdth** [comment]
I remember I had the similar problem when I've messed with adding image overlay and control layer manually. After I clean my code and use purely this package, problem gone.

If the `:name="layer.name"` has something wrong, it will print out undefined. Can you give us more detail about your code.

**Comment by KoRiGaN** [comment]
Hi @mujahidinside,

You must add 
```
layerType="overlay" 
```
for layers to be added as overlay layers in the control.

**Comment by KoRiGaN** [comment]
@mujahidinside,  Do you have a running example, for example, a JS Fiddle.
It's really hard to guess like that...

**Comment by sangdth** [comment]
@KoRiGaN , I followed your guide, use `$refs`, and it works! Thank you. But there is small thing relate to Vue, I would like to have some explanation if you have time.

```javascript
methods: {
    addSourcesOverlay() {
        const layersControl = this.$refs.layersControl.mapObject;
        const sourcesGroup = this.$refs.sourcesGroup.mapObject.addTo(this.lmap);
        layersControl.addOverlay(sourcesGroup, 'Show sources');
    },
}
```

Right now if I put these code into methods and bind it to a button with `@click`, it will work as expected. But if I call it from `mounted()`, nothing happens. I have to do some hack, put it into `$nextTick`.

```javascript
mounted() {
    this.lmap = this.$refs.map.mapObject;
    this.$nextTick(() => {
        this.addSourcesOverlay();
    });
 },
```
If I simply run ` this.addSourcesOverlay();` right after the `this.lmap` assignment, it won't work. Why the script stops after this line `this.lmap = this.$refs.map.mapObject;`? 

I know this is not related to your code, but I'm learning Vue so I would like to have some help from you.

Thanks in advance.

**Comment by mujahidinside** [comment]
@KoRiGaN

**Comment by sangdth** [comment]
@mujahidinside Please check this: https://jsfiddle.net/sangdth/L0uzzjn4/ 
I've done some hack to make it works. In future we can use simple `layer-type="overlay"`, but for now I have to hack it like this.

**Comment by KoRiGaN** [comment]
@sangdth example is right.

1. Property LayerType should be written layer-type in the template.
2. Overlay layers must be added manually,
 
@sangdth, I will try to explain your issue:
When mounted is called on your Vue app the other component (layer-group for example) are not mounted yet so they don't exist in $refs yet.
Vue.$nextTick() will trigger your method just after the DOM is updated so all inside components should have been mounted and be in $refs at that time.

This is why it's probably better to do it when the layer group is added to the map (add event). I modified your example [here](https://jsfiddle.net/L0uzzjn4/49/) to make it work without $nextTick.

**Comment by sangdth** [comment]
Thank you @KoRiGaN. I also think about that the leaflet map's components in $refs do not exist yet when I tested with `created()`, that's why I tried to use $nextTick. I will more about add event, thank you for your suggestion.

I closed this issue as it is solved.

**Comment by nstickney** [comment]
> @mujahidinside Please check this: https://jsfiddle.net/sangdth/L0uzzjn4/


> This is why it's probably better to do it when the layer group is added to the map (add event). I modified your example [here](https://jsfiddle.net/L0uzzjn4/49/) to make it work without $nextTick.


@KoRiGaN The two JSFiddle examples above return 404 now... is there a working example of adding overlay layers to `l-layer-control` that I can look at? My base layers show up fine but even using `.addOverlay` I'm unable to get overlay layers to show up.

**Comment by RoshanAtDure** [comment]
Hi,

I facing same issue. the link given in [Previous commnet](https://github.com/KoRiGaN/Vue2Leaflet/issues/150#issuecomment-378966110) is not working.

Can anybody please guid?

**Comment by DonNicoJs** [comment]
@RoshanAtDure Can you create a reproduction fiddle of what are you doing?

**Comment by RoshanAtDure** [comment]
@DonNicoJs  here is link:  [fiddle](https://jsfiddle.net/roshan_dure/n5ep1jy9/7/)

I want add controls for marker but they are not reflecting.

I am new to vue and dont know where i am doing wrong

Thanks

**Comment by DonNicoJs** [comment]
@RoshanAtDure you are using vue2-leaflet version 1.x :) we are 2.2.1 now! Can your  try to update and use the new one?

**Comment by RoshanAtDure** [comment]
@DonNicoJs  i am using update version only on local.
![version](https://user-images.githubusercontent.com/19946693/68671306-0d429000-0575-11ea-8967-9262a7fe1919.png)

Here is update link of fiddle with 2.2.1 [link](https://jsfiddle.net/roshan_dure/n5ep1jy9/12/)

Thanks

**Comment by DonNicoJs** [comment]
@RoshanAtDure Here, the fiddle is still using the old version but I updated it and fixed the code:
https://jsfiddle.net/a0sm8ghj/12/

**Comment by RoshanAtDure** [comment]
@DonNicoJs  Thanks man.. Its working now.  I miss the  layer-type="overlay" in  layer group.

Thanks again for your help.

**Comment by paibanezma** [comment]
@KoRiGaN thanks so much for this information. I am currently trying to add the awesome wind overlay danwild has created (https://github.com/danwild/leaflet-velocity) to my vue based leaflet map but it is based on a custom class extended from L.Layer:

```
L.VelocityLayer = (L.Layer ? L.Layer : L.Class).extend({
all the class details
});
```

As I understand from your post, we could add this overlay with this code:

 ```
<l-layer-group 
    layer-type="overlay"
    name="Sources"
    :visible="true">
   <l-marker
            v-for="marker in markers"
            :key="marker.id"
            :visible="marker.visible"

            :lat-lng="marker.position"

          />
</l-layer-group>
```
But instead of using the LMarker component we must create a vue component for the custom Layer extended class and used it inside the LLayerGroup.

Could you please tell me how could I create this component in vue?

Thanks so much @KoRiGaN ,

Pablo
