### ISSUE TITLE
styles for google map tile

### ISSUE THREAD

**Issue by mits87** [KoRiGaN/Vue2Leaflet#151]
Hi, 

I'm using google map tile: `http://{s}.google.com/vt/lyrs=m&x={x}&y={y}&z={z}` (with `subdomains: ['mt0', 'mt1', 'mt2', 'mt3']`) and my question is how can I add styles for this tile like here: [https://developers.google.com/maps/documentation/javascript/styling](https://developers.google.com/maps/documentation/javascript/styling) ?

**Comment by KoRiGaN** [comment]
Hi @mits87,

It seems to me that these kind of style are specific to Google Maps so not implemented in Leaflet or Vue2Leaflet.

I would say that the best way to use this kind of styling would probably to create a Vue component that wraps [GoogleMutant](https://gitlab.com/IvanSanchez/Leaflet.GridLayer.GoogleMutant) as a V ue2Leaflet plugin.

Hope this helps!
