### ISSUE TITLE
init map when vue rerender other component

### ISSUE THREAD

**Issue by dfy167** [KoRiGaN/Vue2Leaflet#152]
when click <a> to update class of text. then the map set to initstate. even the <a> tag has no ref with map
`<v-map ref="map" :zoom=13 :center="[28.1938459445,112.9574064230]">
          <v-tilelayer url="http://t4.tianditu.cn/DataServer?T=img_w&X={x}&Y={y}&L={z}"></v-tilelayer>
        </v-map>`

`<a class="navbar-item" @click.stop="button1">
                      <span :class="{'has-text-info':isActive1}">aaaa</span>
                    </a>`
` methods: {
 button1: function () {
      console.log('button1')
       this.isActive1 = !this.isActive1
    }}`

### Browsers Affected
- [ ] Chrome

### Versions
- Leaflet: 1
- Vue: 2
- Vue2Leaflet: latest

**Comment by dfy167** [comment]
fix it by delete    _:center="[28.1938459445,112.9574064230]"_

**Comment by KoRiGaN** [comment]
Hi @dfy167,

Could you please rephrase your question or make a running example that reproduces this issue?

I'm not sure to understand what you mean. 

Micka
