### ISSUE TITLE
Use dependency injection

### ISSUE THREAD

**Issue by timwis** [KoRiGaN/Vue2Leaflet#153]
I had no idea this was even a Vue feature but I was reading the newly rewritten component docs today and saw it: [dependency injection in components](https://vuejs.org/v2/guide/components-edge-cases.html#Dependency-Injection). Instantly thought of this library. Particularly if you want to nest or wrap your components. What do you think?

**Comment by KoRiGaN** [comment]
Hi @timwis,

Thanks for the information, it is good to know. I was not aware of this dependency injection feature in Vue.

However, I always had stuff to the first parent. For example, a marker is added to a layer group on top of it and this layer group is added to the map on top of it.
I try to never access the map directly as it makes everything harder to had/remove.
 
I will keep it in mind though if I need it for future improvements.

Thanks,

Micka

**Comment by timwis** [comment]
Hm, I think it would remove the need for [`findRealParent`](https://github.com/KoRiGaN/Vue2Leaflet/blob/master/src/utils/findRealParent.js), and allow you to wrap your map components in non-vue2-leaflet components, for example.

**Comment by KoRiGaN** [comment]
If you take an example of a map containing 2 layers, each containing 10 markers.

The way it works today is that the 2 layers are added to the map and the makers are added to the layers. So if you change the visibility of the layer all 10 makers are un/visible.

If all components have only access to the injected map they would add themselves to the map. Making the layer group useless for example.  

Not sure what you mean by 'you to wrap your map components in non-vue2-leaflet components, for example'. Do you have an example of something that is not possible today?

**Comment by avioli** [comment]
I think what @timwis is saying is that currently you **cannot** do something like this:

```vue
<template>
  <l-circle-marker
    :lat-lng="latLng"
    color="#ffffff"
    :weight="1.5"
    fillColor="#ff0000"
    :fillOpacity="1"
  />
</template>

<script>
import { LCircleMarker } from 'vue2-leaflet'

export default {
  name: 'RedCircleMarker',
  props: {
    latLng: {
      type: [Object, Array]
    }
  },
  components: {
    LCircleMarker
  }
}
</script>
```

**Comment by KoRiGaN** [comment]
Closing this issue as no comment for 3 weeks.
@timwis if you think your issue is not solved feel free to reopen this issue.

Micka

**Comment by bezany** [comment]
@KoRiGaN @lordfuoco 
May be planning refactor for use `provide/inject` with mapObject instead `findRealParent`? Also possible override injected values (need for LLayerGroup). But it is not mentioned in the documentation.
See this example:
https://jsfiddle.net/bezanyu/1Lwgun4a/

**Comment by lordfuoco** [comment]
@bezany yes I am working on another project and using provide inject extensively there. I am planning to do the same here too
