### ISSUE TITLE
[Support] How to make Vue2Leaflet works with Awesome Markers plugin?

### ISSUE THREAD

**Issue by sangdth** [KoRiGaN/Vue2Leaflet#154]
Hi @KoRiGaN, this is not a bug, or issue, just asking, is it possible to make [this Awesome Markers plugin](https://github.com/lvoogdt/Leaflet.awesome-markers) works with yours?

**Comment by KoRiGaN** [comment]
Hi @sangdth,

Yes it should work if you set the icon value of marker option using Awesome Markers.
Something like:
```Javascript
options: { 
    icon: L.AwesomeMarkers.icon({
        icon: 'coffee',
        markerColor: 'red'
    })
}
```

**Comment by sangdth** [comment]
Thank you @KoRiGaN  for your support, it works!
