### ISSUE TITLE
Customize every points on Polyline

### ISSUE THREAD

**Issue by zaqisilverano** [KoRiGaN/Vue2Leaflet#155]
Hi, i want customize the polyline path with arrow or something like this 
https://github.com/bbecquet/Leaflet.PolylineDecorator

![image](https://user-images.githubusercontent.com/4515947/38759142-87aebc22-3f9e-11e8-8348-3d6adeae729a.png)

but i am not found the plugin wrapped with the vue js, have you solution for that?
thanks

**Comment by KoRiGaN** [comment]
Hi @zaqisilverano,

As far as I know, no wrapper exists for PolylineDecorator so you can:

- Write your own wrapper and share it with the community 👍,
- Use PolylineDecorator on its own with Vue2Leaflet by doing something like this:
```
L.polylineDecorator(latlngs, options).addTo(this.$refs.map.mapObject);

```
where map is a ref added to the Vue2Leaflet map.
 
Hope this helps,

**Comment by jperelli** [comment]
Hi @zaqisilverano I made a wrapper plugin for this, you can see it in https://github.com/jperelli/vue2-leaflet-polylinedecorator

**Comment by jperelli** [comment]
I'm uploading it to npm tomorrow
