### ISSUE TITLE
[Support] How to accept both event and my parameter?

### ISSUE THREAD

**Issue by sangdth** [KoRiGaN/Vue2Leaflet#158]
Hello @KoRiGaN, I would like to have some help on this:
I have a set of markers like this:
```html
<l-marker
    v-for="(site, index) in sites"
    :key="site.site_name + index"
    :lat-lng="site.coordinates"
    :icon="siteIcon"
    @moveend="updateCoordinates(site)"
/>
```
I can access the `event` object if call only `@moveend="updateCoordinates"`, but in my function, I need to access both, `event` and `site` object.

```javascript
methods: {
    updateCoordinates(event, site) {
        // Do something with both event and site.
    }
}
```
If I use both `@moveend="updateCoordinates(event, site)"`, Vue will say `event` does not declare. If I use only site, I can not access `event`.

Do you have any suggestion to work around this? 

Thank you in advance.

**Comment by KoRiGaN** [comment]
Hi @sangdth,

Please use $event as explained in [VueJS doc](https://v1.vuejs.org/guide/events.html#Inline-Statement-Handler).

Micka

**Comment by sangdth** [comment]
I was using `@click` event to work around, but the `$event` is cooler. Thank you sooo much. I close this.
