### ISSUE TITLE
Changes the marker position to the given point

### ISSUE THREAD

**Issue by nwpuhmz** [KoRiGaN/Vue2Leaflet#161]
Hi~
I'm going to dynamicly update my marker . How to change the marker position to the given point,like `setLatLng(<LatLng> latlng)` (Leaflet Marker's API).
Thanks!

**Comment by KoRiGaN** [comment]
Hi @nwpuhmz,
Just update the position that is bind to the marker. The marker will update is position on the map automatically.

You can see an example [here](https://jsfiddle.net/LL9jcz1d/2/).

Hope this helps,

Micka

**Comment by nwpuhmz** [comment]
@KoRiGaN Got it! Thank you very much~

**Comment by winstxnhdw** [comment]
@KoRiGaN Hey! Your example seems to only work for a single marker. Is this possible to do on multiple markers at the same time?
