### ISSUE TITLE
Missing documentation ?

### ISSUE THREAD

**Issue by ScreamZ** [KoRiGaN/Vue2Leaflet#167]
Hey,

The link supposed to show the documentation is only displaying samples, but without any code ?

Why ?

Regards

**Comment by KoRiGaN** [comment]
It's only because I didn't take the time to do it at the moment.

**Comment by davidverriere** [comment]
Code sample are available in git repo : https://github.com/KoRiGaN/Vue2Leaflet/tree/master/examples

**Comment by lordfuoco** [comment]
https://github.com/KoRiGaN/Vue2Leaflet/issues/185#issuecomment-423886038

**Comment by lordfuoco** [comment]
Closing this since new docs are just rolled out! (feedback welcomed)
