### ISSUE TITLE
webstorm build support?

### ISSUE THREAD

**Issue by xzzh999** [KoRiGaN/Vue2Leaflet#168]
hello~

I can builld the project from command line, but can you support webstorm too? when i try to build use webstorm to build the project, print the follow error: 

(i use the v1.0.1 package)

       npm ERR! code ELIFECYCLE
       npm ERR! errno 1
       npm ERR! vue2-leaflet@1.0.1 build: `cd scripts && ./build.sh`
       npm ERR! Exit status 1
       npm ERR! 
       npm ERR! Failed at the vue2-leaflet@1.0.1 build script.
       npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

       npm ERR! A complete log of this run can be found in:
       npm ERR!     E:\NODE\npm-cache\_logs\2018-05-14T07_21_54_869Z-debug.log

and the details of the log is:

           9 verbose lifecycle vue2-leaflet@1.0.1~build: CWD: E:\tech-research\leaflet\Vue2Leaflet-1.0.1
          10 silly lifecycle vue2-leaflet@1.0.1~build: Args: [ '/d /s /c', 'cd scripts && ./build.sh' ]
          11 silly lifecycle vue2-leaflet@1.0.1~build: Returned: code: 1  signal: null
          12 info lifecycle vue2-leaflet@1.0.1~build: Failed to exec build script
          13 verbose stack Error: vue2-leaflet@1.0.1 build: `cd scripts && ./build.sh`
          13 verbose stack Exit status 1
          13 verbose stack     at EventEmitter.<anonymous> (E:\node\node\node-v8.10.0-win- 
          x64\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
          13 verbose stack     at emitTwo (events.js:126:13)
          13 verbose stack     at EventEmitter.emit (events.js:214:7)

need your help,  thank you.

**Comment by KoRiGaN** [comment]
Hi @xzzh999,

Vue2Leaflet will not provide support for any specific IDE.
It seems webstorm is trying to use a build.sh script, it should be possible to run a npm command instead.
Have a look [here](https://www.jetbrains.com/help/webstorm/installing-and-removing-external-software-using-node-package-manager.html) form some documentation.

Hope this helps.

**Comment by xzzh999** [comment]
Hi @KoRiGaN, 
Thank you for your reply,
i use  npm command to build project ok, 
and i build with webstorm ok too, just modify package.json as follow:

      "build": "cd scripts && build.sh",

it seems windows must use build.sh instead of ./build.sh.
