### ISSUE TITLE
Popup two-way binding

### ISSUE THREAD

**Issue by SupriyaSudhindra** [KoRiGaN/Vue2Leaflet#169]
Hi,
can you please suggest me how to do two way binding for popup?

**Comment by KoRiGaN** [comment]
Hello @SupriyaSudhindra,

You can check [this example](https://jsfiddle.net/y5oxk8x5/1/)

**Comment by SupriyaSudhindra** [comment]
Hi @KoRiGaN ,
Thanks for the update...but i need for v-model value as array object value i.e., dynamic...sorry forgot to mention that....
Also, i tried using computed, watch with deep clone etc...but didn't work

**Comment by SupriyaSudhindra** [comment]
Here is the example i am trying to achieve..
`<l-map :zoom="zoom" :center="center">
              <l-tile-layer :url="tileprovider" :attribution="attribution"></l-tile-layer>
              <l-layer-group :visible="visible" >
                <l-layer-group :visible="markersVisible" >
                  <l-marker ref="pin" v-for="(items, index) in markers" :key="index" :icon="items.icon" :visible="items.visible" :draggable="items.draggable" :lat-lng="items.position">
                    <l-popup >
                      <strong>Location Name: </strong>{{items.location_name}}
                      <br><strong>Date: </strong>{{items.time}}
                      <br><button class="btn btn-warning btn-sm" style="color: white;margin:5% 0% 0% 35%;" @click="addStops(items.stop)">Add</button>
                    </l-popup>
                  </l-marker>
                </l-layer-group>
                <l-layer-group :visible="polyVisible" v-for="(poly, index) in polylines" :key="index">
                  <v-editable-polyline ref="poly" :latLng="poly.points" :options="poly.options">
                  </v-editable-polyline>
                </l-layer-group>
              </l-layer-group>
            </l-map>`

`computed: {
    tempstudent: function () {
      var me = this
      if (me.studentSearch !== '') {
        return me.students.filter(function (item) {
          return item['text'].includes(me.studentSearch)
        })
      } else {
        return me.students
      }
    },
    tempmarkers: function () {
      var me = this
      me.Stops.filter(function (item) {
        var mark = me.markers.find(x => x.log_id === item.log_id)
        if (mark !== undefined) {
          mark.location_name = item.location_name
          mark.time = item.date
          return me.markers
        } else {
          return me.markers
        }
      })
    }
  }`

`<b-table show-empty
          striped hover
            responsive="md"
             stacked="sm"
             :items="Stops"
             :fields="stopFields"
             :filter="filter"
             :sort-by.sync="sortBy"
             :sort-desc.sync="sortDesc"
             @filtered="onFiltered"
          >
            <template slot="location_name" slot-scope="row">
              <p v-if="row.item.log_id === 'Dstop'">{{row.value}}</p>
              <b-form-input v-model="row.item.location_name" type="text" placeholder="0,0" v-if="row.item.log_id !== 'Dstop'"></b-form-input>
            </template>`

so for the change of value of row.item.location_name should change value in popup two-way binding simultaneously.

please suggest...

**Comment by SupriyaSudhindra** [comment]
Hi @KoRiGaN ,
any luck with popup two-way binding?

**Comment by KoRiGaN** [comment]
Hi @SupriyaSudhindra,

Still not sure what is not working. I spent some time having a try with Bootstrap table and Vue2Lealfet marker popup edition.
I ended up with [this example ](https://jsfiddle.net/y5oxk8x5/4/) that works properly.

So I still don't know what is your issue as you don't provide a clear working example.

Hope this helps,

**Comment by KoRiGaN** [comment]
Hi @SupriyaSudhindra,
Still not sure what you want to achieve here. Do you want 2 different arrays to be sync together?

**Comment by SupriyaSudhindra** [comment]
yes...

**Comment by KoRiGaN** [comment]
Then this is not 2-way binding and what you want to achieve is not related to a bug in Vue2Leaflet but how to implement your requirement in javascript.

The VueJs watch functionality should probably help so you should dig on this side.
You can also ask for help on VueJs Discord chat.

Micka

**Comment by SupriyaSudhindra** [comment]
ok...thank you...
