### ISSUE TITLE
components v-popup and v-tooltip not working

### ISSUE THREAD

**Issue by jokkopp** [KoRiGaN/Vue2Leaflet#17]
`<template>`
`<v-map :zoom="zoom" :center="center" :min-zoom="minZoom" :max-zoom="maxZoom">`
`<v-tilelayer :url="url"></v-tilelayer>`
`<v-marker :lat-lng="latlng" :draggable="true" @l-move="markerMoved" @l-click="markerClick">`
`    <v-popup :content="greeting"></v-popup>`
`    <v-tooltip :content="greeting"></v-tooltip>`
`</v-marker>`
`</v-map>`
`</template>`

`<script>`
    import Vue2Leaflet from 'vue2-leaflet';

    export default {
      components: {
          'v-map': Vue2Leaflet.Map,
          'v-tilelayer': Vue2Leaflet.TileLayer,
          'v-marker': Vue2Leaflet.Marker,
          'v-tooltip': Vue2Leaflet.Tooltip,
          'v-popup': Vue2Leaflet.Popup
      }}
`</script>`

`<style>`
   ` @import "~leaflet/dist/leaflet.css";`
`</style>`

**Comment by KoRiGaN** [comment]
Hi @jokkopp, 

Version 0.0.40 of Vue2Leaflet should fix this.

Mickaël
