### ISSUE TITLE
Emit zoom and center not fired.

### ISSUE THREAD

**Issue by disjfa** [KoRiGaN/Vue2Leaflet#173]
### Description
LMap update:center not fireing and update:zoom not fireing on zoom level 13 (?!). 

I want to use your component to set up a base map, and it looks cool (thanks for that). But i want to save the base zoom level and base center in my database. So i was just checking the emitters and what they do. But when i check the zoom level it does not trigger, but only on zoom level 13 for some strange reason.

The update:center emitter is not triggered at all, more strangeness.

#### Live Demo
https://jsfiddle.net/disjfa/sk6w67qh/2/

#### Steps to Reproduce
Click on the demo, check the console ^_^

#### Expected Results
Zoom level on the console, and the center when moving the map.

#### Actual Results
No zoom level on 13, and no center data at all!

### Browsers Affected
I'm just checking on my local machine, so chrome 66 for now

- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions
I copied the base fiddle, so those.

**Comment by disjfa** [comment]
The zoom is because the zoom is not updated, so it is the base zoom !== zoomlevel.

**Comment by disjfa** [comment]
And the center is also never updated because the if, if you have a center in the props! Weird code, lets see if i can help and check this code.

**Comment by disjfa** [comment]
.... buuuut you don't have a dev server for the examples. I do not know how to run your code on my local dev environment sadly.

The zoomlevel could be updated using something like this:
```
if (this.mapObject.getZoom() != this.zoom) {
    this.$emit('update:zoom', this.mapObject.getZoom());
    this.zoom = this.mapObject.getZoom();
}
 ```
Or
```
if (this.mapObject.getZoom() != this.zoom) {
    this.$emit('update:zoom', this.mapObject.getZoom());
    Vue.set(this, 'zoom',this.mapObject.getZoom());
}
 ```
To update the local zoom prop, so it wont get fired every time.

If i can help please set up a local dev machine from the npm scripts to test the examples. I usually work from a local windows computer spinning up a linux server on a virtual machine.  So a webpack dev server is helpful ^_^. Was just testing to get it up and running but i don't know how in a time willing to get it up ...

**Comment by KoRiGaN** [comment]
Hi disjfa,

Thanks for opening this issue.
It indeed seems to be a bug.

You can run the examples locally, you can have a look at the section 'Run code locally for contributors' from the readme.

Hope this helps,

Micka

**Comment by disjfa** [comment]
I made a quick fix https://github.com/KoRiGaN/Vue2Leaflet/pull/176.

I would remove/re setup the base setup and remove the Array.isArray checks to the mounted. But i don't like the dev setup in the project so i did not check all the changes. But this will do for now.

**Comment by Yerrak** [comment]
Had exactly the same problem and came up with a similar solution and *then* found this issue ...

I went for the more straightforward fix by just emitting the events, see PR#219. Maybe we can integrate either of them :)

**Comment by disjfa** [comment]
I was waiting on @KoRiGaN . We can probably still merge this.

**Comment by blaskovicz** [comment]
I can confirm that the `@update:center="callback"` never fires either in my example that's set up like:

`<l-map :zoom="zoom" :center="center" @update:center="centerUpdate" @update:zoom="zoomUpdate" ref="map" style="height: 300px">`

Two things I was trying to use:
`this.$refs.map.mapObject.fitBounds(bounds)`

and
`this.center = L.latLng(47.41322, -1.219482);`

Center is initialized so it's reactive:
`private center: L.LatLng = L.latLng(47.41322, -1.219482);`

**Comment by lordfuoco** [comment]
@blaskovicz can you try with the lastest 1.1.1 version and see if this is still the case ?

**Comment by disjfa** [comment]
1.1.1 fires on all cylinder. Forgot to mention that the other day when i tested the master branch.

So yes, it fires now 👍
