### ISSUE TITLE
vue.js:596 [Vue warn]: Error in beforeDestroy hook: "TypeError: Cannot read property 'filter' of undefined"

### ISSUE THREAD

**Issue by davidverriere** [KoRiGaN/Vue2Leaflet#177]
https://github.com/KoRiGaN/Vue2Leaflet/blob/bd7709d3b7929f4306e279ce5c5e709d8f49e48a/src/components/LMap.vue#L171

layerToAdd is null on calling removeLayer.

I do not see where layerToAdd is defined

**Comment by lordfuoco** [comment]
Closing this since the issue is resolved and merged, release coming soon

**Comment by DC19950217** [comment]
How can this problem be solved?
