### ISSUE TITLE
Animation Marker

### ISSUE THREAD

**Issue by lusman20** [KoRiGaN/Vue2Leaflet#181]
I would like to know if there is any extension developed for vuejs, which allows the marker animation, or the following plugin developed in vuejs Leaflet.MovingMarker https://github.com/ewoken/Leaflet.MovingMarker

**Comment by KoRiGaN** [comment]
Hi @lusman20,

As far as I know, it doesn't exist yet.

**Comment by RickMeijer** [comment]
It's an old post, but for people coming in from google:

https://github.com/KoRiGaN/Vue2Leaflet/issues/206
leads to
https://github.com/LouisMazel/vue2-leaflet-movingmarker

Might help?

**Comment by DonNicoJs** [comment]
Closing this, movingmarker is listed in the docs as well
