### ISSUE TITLE
Get mouse position on the map

### ISSUE THREAD

**Issue by lusman20** [KoRiGaN/Vue2Leaflet#182]
I'm trying to make the user click on the map to create new markers

For this I need to know where you clicked

I try this

<l-map  id='map' @click="markernew(this)" style="height: 90%" :zoom="zoom" :center="center">
methods:{
       markernew(){
           console.log(L.DomEvent.getMousePosition(LMap))
       },
}
and try with
methods:{
       markernew(){
           console.log(L.DomEvent.getMousePosition('#map'))
       },
}

but it returns me
Point {x: undefined, y: undefined}

Or if you already have something to create geofence

**Comment by KoRiGaN** [comment]
Leaflet will give you an event object on click. You just need to use it.
``` javascript
methods: {
  addMarker(event) {
    this.markers.push(event.latlng);
  }
}
```

**Comment by lusman20** [comment]
Sorry you have some complete example

I try this
```
<l-map  @click="addMarker(this)"  :center="center">
</l-map>
```

```
methods: {
  addMarker(event) {
    console.log(event.latlng)
    //this.markers.push(event.latlng);
  }
}
```

I get this in console

> Uncaught TypeError: Cannot read property 'latlng' of null

**Comment by KoRiGaN** [comment]
<l-map  @click="addMarker"  :center="center">
</l-map>
methods: {
  addMarker(event) {
    console.log(event.latlng)
    //this.markers.push(event.latlng);
  }
}

**Comment by lusman20** [comment]
Thanks @KoRiGaN its work
Very good work with vue2leaflet
