### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by rSammy** [KoRiGaN/Vue2Leaflet#185]
Hello.

I don't see any docs on https://korigan.github.io/Vue2Leaflet/

I'd like to know what vue code is being used not only see the results.

Plus I'd like to know what are the supported directives ? I don't see any information about this.

**Comment by jkatagi** [comment]
Hi @rSammy ,
The example scripts  used in https://korigan.github.io/Vue2Leaflet/ are in the https://github.com/KoRiGaN/Vue2Leaflet/tree/master/examples/src/components .

But more details document does not seem to be present at the moment.

**Comment by jkatagi** [comment]
Please also refer this #167

**Comment by lordfuoco** [comment]
Hi! I started a docs branch where I am writing docs with vuepress, including the old examples and more.
It's smooth sailing but also a long river so it will take a bit to finish, if anyone wants to help it would be appreciated ( even just proofreading )
