### ISSUE TITLE
How to know when map is loaded?

### ISSUE THREAD

**Issue by goors** [KoRiGaN/Vue2Leaflet#187]
When you use `mounted` or `created` you have to `setTimOut` in order to get `this.refs.map`.
Is there some method on `l-map` that says `mounted` or `initialized`?

**Comment by sangdth** [comment]
I found [this](https://leafletjs.com/reference-1.3.0.html#map-load) on Leaflet map doc

**Comment by majdal** [comment]
You have to use `this.$nextTick()`, as mentioned in the [docs](https://github.com/KoRiGaN/Vue2Leaflet#faq). Otherwise, you can use event hooks in the parent components: https://alligator.io/vuejs/component-event-hooks/
