### ISSUE TITLE
Pop-ups in markers

### ISSUE THREAD

**Issue by tiagofassoni** [KoRiGaN/Vue2Leaflet#2]
I'd like to add pop-ups to markers, but have no idea on how would be the best way to do that. 

The easiest one would be to simply create a new method to the pop-up component which... adds a pop-up. But I don't think that's really the best way.

The other would be to create a pop-up component. In terms of how Vue is supposed to work, that would be the best way (I think).

Or there might be a completely different way to do it and I'm completely lost here.

Either way, I'm open to making a pull request with the necessary changes and/or improving the examples.

**Comment by KoRiGaN** [comment]
I have added tooltip and popup components.

You can see an example in the /examples/index.html file.

Let me know if something doesn't work for you.

**Comment by tiagofassoni** [comment]
WOW! That was fast!

Thanks so much!
