### ISSUE TITLE
onEachFeature pass method back to Vue app

### ISSUE THREAD

**Issue by JWDobken** [KoRiGaN/Vue2Leaflet#202]
I finally managed to change the style of my geojson lines on mouse over; see the [JSFiddle](https://jsfiddle.net/jwdobken/qywaz1h8/41/). 

Now; the active line, with mouse over, changes color. But I would actually want to change the color of all OTHER lines on mouse over; but I have no idea how to approach that

**Comment by bezany** [comment]
@JWDobken wait new release with this PR #228. And then you can use `optionsStyle` property with geojson-layer.
