### ISSUE TITLE
LTooltip performance issues

### ISSUE THREAD

**Issue by lordfuoco** [KoRiGaN/Vue2Leaflet#204]
Currently the LTooltip slot is kept in the DOM, with 200 complex tooltip the page lags / hangs.

This commit on Pulilab fork f51ff27ab6f333ea6d9e93843cab43c2865c1cfb address this issue by:

- Instantiate leaflet component with cloned slot element
- unmount the slot from the DOM after instantiation is done

No PR opened due to waiting for the main PR to be checked / merged   #200 

In this commit an example LoadTest is added: 
2a496f5002168ebbe6934dfa9bcd6b1ca62c52b3

**Comment by sangdth** [comment]
This could related to this issue #195 too. I'm working on project that has more than 550+ markers/tooltips, it's really sad to look at console log.

**Comment by lordfuoco** [comment]
@sangdth untill the pr is merged you can use this fork: https://github.com/pulilab/Vue2Leaflet/tree/fix/tooltip-performances

**Comment by lordfuoco** [comment]
@sangdth the code with the fix is merged, release is due to come soon

**Comment by justinbeatz** [comment]
When this is gonna be updated in the npm registry?

**Comment by lordfuoco** [comment]
Early next week, just doing some final tests since the code base updated a lot

**Comment by sangdth** [comment]
@lordfuoco I've moved to new project, but thank you for your update, I will inform the team about this.
