### ISSUE TITLE
LGeoJson.vue has two methods for setVisible

### ISSUE THREAD

**Issue by ashleysommer** [KoRiGaN/Vue2Leaflet#211]
### Description
LGeoJson.vue has two methods named `setVisible`.
1: https://github.com/KoRiGaN/Vue2Leaflet/blob/c39704a6a4c5475ce687711fa45d6554e02871f2/src/components/LGeoJson.vue#L33
2: https://github.com/KoRiGaN/Vue2Leaflet/blob/c39704a6a4c5475ce687711fa45d6554e02871f2/src/components/LGeoJson.vue#L53
I'm not sure which is the more correct one.

This commit in May modified the 2nd one, but not the 1st one:
https://github.com/KoRiGaN/Vue2Leaflet/commit/90c363553b4d0d8909c76af037fe74027905c030

**Comment by lordfuoco** [comment]
This is addressed in this PR: #200
