### ISSUE TITLE
Bounce marker

### ISSUE THREAD

**Issue by moas** [KoRiGaN/Vue2Leaflet#212]
Hi,

Do you known how to add bounce event on marker. I want to start bouncing when user click on marker.

#### Live Demo

http://jsfiddle.net/Boumi/k04zpLx9/

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions
- Leaflet: vX.X.X
- Vue: vX.X.X
- Vue2Leaflet: vX.X.X

**Comment by lordfuoco** [comment]
Hi @moas sorry for taking some time to answer.
You can achieve your bounce event by adding a class to the icon of the marker on click, and then have a CSS animation for the bounce.
the icon prop of the l-marker is reactive, you can pass to it a LDivIcon with your style and change it on click.

**Comment by moas** [comment]
Thx !!

**Comment by zimmicz** [comment]
@moas @lordfuoco hey guys, could you share a sample code? I'm trying to set a class to LMarker/LIcon to no avail for a while. I'll appreciate your help.

**Comment by bezany** [comment]
@zimmicz Hello! If I correctly understand try like [here]( http://jsfiddle.net/bezanyu/srkatboy/)
