### ISSUE TITLE
Access geojson properties on click

### ISSUE THREAD

**Issue by plicplic** [KoRiGaN/Vue2Leaflet#218]
Hi, 
I just read the answer you gave for #86 and it's a little bit related to that kind of problem. Hope you may help with some directions...

I use Vue2Leaflet with its vue-choropleth plugin to display information from a geojson linked to some data, in an infowindow. That works fairly well, using code from [this example](https://github.com/voluntadpear/vue-choropleth/blob/master/examples/node-example/src/App.vue).

But I need to go further: when the user clicks on a specific area, I'd like to pass the area name (features.properties.Name in the geojson) to Vue, to redirect her to a specific page.

I looked at the function oneEchFeature but I don't find a clue to achieve this.

Is this something I can do? And what could be a direction to do it?

Many thanks for your help.

**Comment by plicplic** [comment]
Hi and thanks for your help!
I let vue-choropleth apart for the time being and concentrated on the "click" part. I made som progress since yesterday but I'm still clueless for some parts.

**What I can already do:**

console.log the "Name" property from geojson on mouseover.

**What I can't do yet:** 
1) Have a popup displaying on the same mouseover. It's because I can't find the equivalent of openOn(map) that I use on a simple html leaflet without vue.js test.
2) Get the "Name" properties when one clicks on the popup and pass it to vue.js for a redirection to cards (or pages) specific to each location.

Some code below:

```
<template>
<div>
    <v-map :center="[50.49, 4.7]" :zoom="8" style="height: 600px;">
      <v-geojson :geojson="geojson" :options="mapOptions"> </v-geojson>
    </v-map>
</div>
</template>

<script>
import { geojson } from '../../data/cities.geojson'
import Vue2Leaflet from '../../node_modules/vue2-leaflet/dist/vue2-leaflet.js';
import {
  LMap,
  LTileLayer,
  LMarker,
  LPolygon,
  LPolyline,
  LPopup,
  LGeoJson
} from 'vue2-leaflet';

export default {
  components: { 
    'v-map': Vue2Leaflet.LMap,
    'v-geojson': LGeoJson,
  },

  data() {
    return {
      geojson,
      mapOptions: {
        style: function style(feature) {
          return {
            weight: 4,
            opacity: 0.7,
            color: '#666',
            fillOpacity: 0.3
          };
        },   
        onEachFeature: function onEachFeature(feature, layer) {
          layer.on('mouseover', function(e) {
          console.log(feature.properties.Name);
          //open popup
          var popup = L.popup()
            .setLatLng(e.latlng) 
            .setContent('<h1 style="color: grey; margin-bottom: 0;">'+ feature.properties.Name +'</h1>')
            //.openPopup();  I tried this one but suspect it's not that simple
            //.openOn(map); This one can't work with Vue2Leaflet
          });
        }
    }
} // removed some code related to choropleth part
}     
```

**Comment by plicplic** [comment]
Hi again. Great feeling of getting close to a solution!
When making these changes to the code, I got this error:

`TypeError: self.$refs is undefined, can't access property "myMapRef"`

Do you have any idea what I did wrong here?

**Comment by lordfuoco** [comment]
@plicplic Did you defined self at the beginning of onEachFeature function? if so please change
` onEachFeature: function onEachFeature(feature, layer) {` 
to:
` onEachFeature: (feature, layer)  => {

So that the scope of this is tied to the vue instance

**Comment by plicplic** [comment]
Now it's perfectly working. I added a second _layer.on_ function to take care of the click (this is where I use _self.popupName_, now. It is linked to a _watch_, which listen to a change (the click) and then trigger a redirection to the differents "cards" (all of this is my next todo...)

```
watch: {
      popupName: function(popupName, old) {
      this.$router.push(`/${this.popupName}`)
      }
}   
```
Very grateful for your help. These changes to my code where out of the reach of my tinkerer level. It really motivates me to learn deeper and deeper!

**Comment by lordfuoco** [comment]
@plicplic Glad to have helped!

You actually don't need a watch and you can directly call `self.$router.push` :) 

If you want some code inspiration you can check the github source of vue-people

**Comment by plicplic** [comment]
@lordfuoco Thanks for the suggestion, I will dive in this!

**Comment by lordfuoco** [comment]
@plicplic if this issue is clear please close it :)

**Comment by bagaskarala** [comment]
thanks bro, you saved me 🤩

**Comment by 0wenwu** [comment]
MARK
