### ISSUE TITLE
Add attribute to control scrollWheelZoom option

### ISSUE THREAD

**Issue by carlmjohnson** [KoRiGaN/Vue2Leaflet#220]
Leaflet has an option called [`scrollWheelZoom`](https://leafletjs.com/reference-1.3.4.html#map-scrollwheelzoom), but Vue2Leaflet doesn't support it.

As a workaround for now, I have this code in my root component:

```
  mounted() {
    // Hack to turn off scrollWheelZoom, since vue2-leaflet doesn't support it
    this.$nextTick(() => {
      let map = this.$refs.map.mapObject;
      let layers = [];
      map.eachLayer(l => {
        layers.push(l);
      });
      let options = { ...map.options, layers: layers, scrollWheelZoom: false };
      map.remove();
      this.$refs.map.mapObject = L.map(this.$refs.map.$el, options);
    });
  },
```

(This require `<l-map ref="map">` to be set.)

I would prefer to just set `<l-map :scroll-wheel-zoom="false">`.

**Comment by lordfuoco** [comment]
You can simply do:

`<l-map :options="{scrollWheelZoom:false}" `

Options prop gets bound to leaflet options

**Comment by lordfuoco** [comment]
@carlmjohnson if my answer satisfy your needs please close the issue :)

**Comment by carlmjohnson** [comment]
Awesome, thanks! Can this be added to the docs somewhere? I searched the repo for scrollWheelZoom and didn't find it.

**Comment by lordfuoco** [comment]
I am thinking to make a big doc pr I will make an issue about it today, any help would be welcomed!
