### ISSUE TITLE
About Custom FloorPlan

### ISSUE THREAD

**Issue by l02162010** [KoRiGaN/Vue2Leaflet#225]
Sorry,
How to make like this https://codepen.io/l02162010/pen/aaMmVy?editors=1010
I don't konw how to change to vue2Leaflet 
Please give me some advice

**Comment by lordfuoco** [comment]
@l02162010 I don't have much experience with ImageOverlay, but AFAIK you can just do something like this: 

```
<l-map >
<l-image-overlay :url="youUrl" :bounds="imageBounds" />
</l-map>
```

And have a computed property to calculate image bounds

**Comment by l02162010** [comment]
@lordfuoco Hi
Do you know how to calculate image bounds ?
And How to set Maxbounds in ImageOverlay?
if you know please tell me !  thankyou !

**Comment by l02162010** [comment]
@lordfuoco 
thank you!
It works
