### ISSUE TITLE
resetStyle problem with highlightLayer

### ISSUE THREAD

**Issue by plicplic** [KoRiGaN/Vue2Leaflet#232]
Hi,
I can't get a "resetStyle" working on mouseout with Vue2Leaflet for the highlight feature. Is there something I'm doing wrong? 

Here is the code:

```
 onEachFeature: (feature, layer) => {
          var self = this;
          layer.on('mouseover', function highlightFeature(e) {
            self.highlightLayer = e.target;
              self.highlightLayer.setStyle({
                fillColor: '#cc0000',
                weight: 2
              });
          });
          layer.on('mouseout', function (e) {
             self.highlightLayer.resetStyle(e.target); 
          });   
         ...
```

I get a "not a function" result and have no clue how I could set this up.

Thanks for your attention.

**Comment by plicplic** [comment]
Hi @lordfuoco,
Thanks. The simplified setstyle part works well. But the reset still don't.
Here is the whole bloc. You will recognize your help from a couple of week on capturing at click :-)

```
style: function style(feature) {
          return {
            weight: 1,
            opacity: 0.7,
            color: '#999',
            fillOpacity: 0.2
          }
        },   
        onEachFeature: (feature, layer) => {
          var self = this;
            layer.on('mouseover', () => {
              layer.setStyle({
                color: '#cc0000',
                weight: 2
              });
            });
            layer.on('mouseout', () => {
              layer.resetStyle(); 
            });
          layer.on('mouseover', function(e) {
            //open popup;
            var popup = L.popup()
              .setLatLng(e.latlng) 
              .setContent('<p style="color: #878575; font-size: 1.8em; margin-bottom: 0;">'+ feature.properties.Name +'</>')
              .openOn(self.$refs.myMapRef.mapObject);
          });
          layer.on('mouseout', function (e) { 
            L.popup().openOn(self.$refs.myMapRef.mapObject);
          });
         layer.on('click', function(e) {
            self.popupName = feature.properties.Name;
            console.log(feature.properties.Name);
          });
        },  
```

**Comment by lordfuoco** [comment]
@plicplic do you get a function not found error or the function simply does not work ? 
Also sqeeuze in a `console.log(layer)` inside the mouseout function, to see if is actually running

**Comment by bezany** [comment]
Method `resetStyle` exists only for L.GeoJSON class in leaflet, but in callback `onEachFeature: (feature, layer)` parameter `layer` is not type L.GeoJSON. Is some other L.Layer child. [See this function](https://github.com/Leaflet/Leaflet/blob/ba1b253126df92b91993a678050d18a99d3d7b63/src/layer/GeoJSON.js#L164)
You can use `setStyle` with default options in `mouseout` like this:

```javascript
const defaultStyle = {
  weight: 1,
  opacity: 0.7,
  color: '#999',
  fillOpacity: 0.2
}
const selectedStyle = {
  color: '#cc0000',
  weight: 2
}

onEachFeature: (feature, layer) => {
  layer.on('mouseover', () => {
    layer.setStyle(selectedStyle);
  });
  layer.on('mouseout', () => {
    layer.setStyle(defaultStyle); 
  });
}
```

**Comment by plicplic** [comment]
@bezany Thanks for this clear explanation. I struggle to test your code because I got a "_const is a reserved word_" error.

Some people points to something to add to a .esrlint file but I can't find any trace of such a file in my app directory.

Is it the same to use a function like this?

```
selectStyle: function selectStyle(feature) {
          return {
            weight: 2,
            color: '#cc0000',
            fillOpacity: 0.7
          }
        },      
```
That's what I tried but yet nothing happened and a console.log(layer) returns just nothing so I doubt the function is used yet.

**Comment by bezany** [comment]
@plicplic You may replace `const` to `var`.
I created example: https://jsfiddle.net/3fcxzm9u/15/
Important notice: in `onEachFeature` can call `setStyle` only with parametr-object, not function because `layer` in `onEachFeature` is not L.GeoJSON class.

**Comment by plicplic** [comment]
@bezany looking at your excellent jsfiddle and trying to refactor my code, I feel I'm very close.  but still, there's the var or const problem in my way. I decided to stick to the options rather than the computed properties because I'm more confortable with this at the moment.  Here is my code:

```
mapOptions: {
        var defaultStyle = {
          weight: 1,
          opacity: 0.7,
          color: '#999',
          fillOpacity: 0.2
        }
        style: function style(feature) {
            return defaultStyle
        },    
        onEachFeature: (feature, layer) => {
          var self = this;
          layer.on('mouseover', () => {
          layer.setStyle({
                  color: '#cc0000',
                  weight: 2
            });
          });
          layer.on('mouseout', () => {
            layer.setStyle(defaultStyle); 
          });
          layer.on('mouseover', function(e) {
          var popup = L.popup()
            .setLatLng(e.latlng) 
            .setContent('<p style="color: #878575; font-size: 1.8em; margin-bottom: 0;">'+ feature.properties.Name +'</>')
            .openOn(self.$refs.myMapRef.mapObject);
          });
          layer.on('mouseout', function (e) { 
            L.popup().openOn(self.$refs.myMapRef.mapObject);
          });
          layer.on('click', function(e) {
            self.popupName = feature.properties.Name;
          });
     }  
 }   
```
