### ISSUE TITLE
Are methods from a class accessible?

### ISSUE THREAD

**Issue by wishinghand** [KoRiGaN/Vue2Leaflet#236]
In the the Leaflet library, the Polygon class has a method called `getBounds`. If I have a few Polygons being drawn using Vue2Leaflet, how would I call `getBounds` (or any other method) on a specific polygon, like one that a user has clicked on?

**Comment by lordfuoco** [comment]
@wishinghand yes they are, just place a ref on the polygon and then you can do 
`this.$refs.myRefName.mapObject.methodThatyouWant()`

just keep in consideration that the leaflet version is 1.3.1

**Comment by wishinghand** [comment]
So if I'm drawing each of my polygons with a `v-for`, I'd have to to make auto-incrementing refs? like this?

```
<l-polygon
    v-for="(zone, index) in newEvent.zones"
    ref="`polygon-${index}`"
    :lat-lngs="zone.outline"
    :key="zone.id"
/>
```

If I wanted to call `getBounds` on any particular polygon, how would I grab that ref?

**Comment by lordfuoco** [comment]
You don't need to do that, because if you put a ref on a v-for vue generate an array of them.
Otherwise you can name them with something like zone.id or similar that you can recognise to find the right one
