### ISSUE TITLE
v-marker fadeout

### ISSUE THREAD

**Issue by GopherJ** [KoRiGaN/Vue2Leaflet#237]
#### Live Demo

http://jsfiddle.net/Boumi/k04zpLx9/

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions
- Leaflet: vX.X.X
- Vue: vX.X.X
- Vue2Leaflet: vX.X.X

**Comment by lordfuoco** [comment]
@GopherJ Hi, I don't understand the issue, it's not explained.
The code pen works for me, can you please explain what is your problem / question   by editing the issue description ?

**Comment by GopherJ** [comment]
Sorry for no description, I need a fadeout effect but with Vue2Leaflet I dont know how to implement it cause it remove directly the marker.

Could you help me ?

**Comment by lordfuoco** [comment]
@GopherJ Sure, the general idea is:
have a function that
1)  progressively lower the opacity of the marker
2) when the animation is done (you can hardcode the time I think ) remove the marker as per usual

You could achieve this by putting a ref on the marker and doing something like this:

```
<template>
....
<l-marker v-if="visible" ref="myFadeMaker" ... />
</template>
<script>
...
methods: {
    fadeAndRemove (opacity) {
        if(opacity > 0) {
            opacity -=1;
            this.$refs.myFadeMaker.mapObject.setOpacity(opacity);
            setTimeout( () => {
                this.fadeAndRemove(opacity);
            })
        } else {
            this.visible = false;
        }
    }
}
....
</script>

This is a very rough snippet but I hope it will point you to the correct direction

**Comment by GopherJ** [comment]
Thank you for this solution ! It seems works.
