### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by flerko** [KoRiGaN/Vue2Leaflet#239]
Hi there.

Can you help me, please?
Can I draw the following with your library:
I have a huge cinema, inside the cinema zones, inside the zones of the places (with absolute position and x/y coordinates from API)
I want to display the cinema as a map in which part of the functionality will be available.

```
<l-map :zoom="zoom" :center="center">
  <l-layer-group v-for="(zone, index) in zones"
                 :key="index"
                 :name="'Layer-' + index">
    <l-layer-group layer-type="overlay">
      <l-circle :lat-lng="{ lng: place.x, lat: place.y }"></l-circle>
    </l-layer-group>
  </l-layer-group>
</l-map>
```

Is it possible? 
And what errors can be?

So much thanks

**Comment by lordfuoco** [comment]
@flerko the code snippet that you posted is something that would work with vue-leaflet.
What is the problem? Can you clarify a bit better your question / problems ?

**Comment by flerko** [comment]
Trying to use your snippet:
I get a noncore mapping and I cannot understand what it can be connected with. I need to display in pixels, is this my main problem or maybe something else?

**Comment by lordfuoco** [comment]
@flerko I don't understand what: noncore mapping is, can you make a codesandbox or a jsfiddle with your problem ?

**Comment by flerko** [comment]
The problem was in the wrong coordinates display, the following code fixed the problem:

```
mounted() {
    this.$nextTick(() => {
      let map = this.$refs.Hall.mapObject;

      this.zones.forEach(zone => {
        zone.places.forEach(place => {
          place.x += zone.area.left;
          place.y += zone.area.top;

          let point = L.point(place.x, place.y);
          let coords = map.unproject(point, 3);

          place.lat = coords.lat;
          place.lng = coords.lng;
        });
      });
      this.mapLoaded = true;
    });
  }
```

Thanks for answers!
