### ISSUE TITLE
keep-in-view prop doesn't work

### ISSUE THREAD

**Issue by wishinghand** [KoRiGaN/Vue2Leaflet#242]
### Description
After adding `:keep-in-view="true"` onto an LPopup component, a user is still able to drag the map so the popup is out of view of the map window.

#### Live Demo
https://jsfiddle.net/wishinghand/hvfs5rez/2/

#### Steps to Reproduce
Make a popup on a polygon with the `keep-in-view` prop set to true, open it up, drag the map until the popup moves out of the map frame.

#### Expected Results
Being unable to drag the popup out of bounds

#### Actual Results
The popup is dragged out of bounds

### Browsers Affected

[ x ] Chrome
[ x ] Firefox
[ x ] Safari 11

### Versions
- Leaflet: whatever Vue2Leaflet v1.0.2 packages
- Vue: v2.5.16
- Vue2Leaflet: v1.0.2

**Comment by jericopulvera** [comment]
@wishinghand https://jsfiddle.net/hvfs5rez/3/

There is no "keep-in-view" prop. 
```
        <l-popup :options="{ keepInView: true }">Hey I'm a popup. Try to drag me out of frame.</l-popup>
```

**Comment by wishinghand** [comment]
Ah, I didn't realize options weren't moved out into their own props. Thanks for the clarification.
