### ISSUE TITLE
Strange LoadTest in Examples

### ISSUE THREAD

**Issue by bezany** [KoRiGaN/Vue2Leaflet#247]
In LoadTest.vue in popup used url in src="https://archive.org/download/ElephantsDream/ed_1024_512kb.mp4"
This videofile have size is 50 mb. Every popup create request for video. It's page generate 2000 requests. May be use simple image in base64?

**Comment by lordfuoco** [comment]
@bezany yes, do you want to take care of it ?

**Comment by bezany** [comment]
Yes, i soon create PR.
And other questions: why created 2000 requests when markers only 1000? It'is because we have two object for every popup: vue component and leaflet-popup?

**Comment by lordfuoco** [comment]
Yes that is the reason, I tried many different techniques to avoid having duplicated elements but sadly there are downside on all approach so I reverted to a safe approach.

When the docs are over I will put tips to avoid to overload the page
