### ISSUE TITLE
Support arrays for LatLng objects

### ISSUE THREAD

**Issue by Phyks** [KoRiGaN/Vue2Leaflet#25]
Hi,

It would be useful to support arrays whenever a LatLng object is expected, according to what Leaflet offers.

Typically, passing an array as the `center` prop of the map currently works, but it does not work for `Marker` position, which has to be an object with a `lat` and `lng` key.

Also, for `bounds` prop on `Map`, one has to pass a `L.latLngBounds` object whereas [leaflet should support passing an Array directly](http://leafletjs.com/reference.html#latlngbounds).

Thanks!

**Comment by KoRiGaN** [comment]
Hi @Phyks,

v0.0.46 should fix this for marker, map center and circle center.

**Comment by Phyks** [comment]
Thanks!
