### ISSUE TITLE
Problems with props and default values

### ISSUE THREAD

**Issue by bezany** [KoRiGaN/Vue2Leaflet#251]
I found seriously problem with default properties values and use [object literals spread syntax](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Operators/Spread_syntax) or Object.assign.
Problem's examples below:

maxZoom in options not work
vue2leaflet 1.0.2 version
https://jsfiddle.net/arfomx3p/1/
#next version
https://jsfiddle.net/qk9mjw5p/6/

sort layers raise error
vue2leaflet 1.0.2 version
https://jsfiddle.net/arfomx3p/9/
#next version
https://jsfiddle.net/qk9mjw5p/14/

control position not set
vue2leaflet 1.0.2 version
https://jsfiddle.net/L4k7f0xz/2/
#next version
https://jsfiddle.net/m6v9hbe3/3/

Source of the problem: overriding property value in `options` property using default value from property with same name.
Simple property override demonstration
```javascript
const options = { maxZoom: 3 }
> undefined
options
> {maxZoom: 3}
{ ...options, maxZoom: undefined }
> {maxZoom: undefined}
```
[same as here in source](https://github.com/KoRiGaN/Vue2Leaflet/blob/master/src/components/LMap.vue#L86)
Same problem with Object.assing.

Possible solution:
1. Set all properties `default` to `undefined`. Leaflet have internal default values for all properties. I recommend use this default values, not write same code in vue2-leaflet. Maybe only in special case we can set default value explicitly.
2. Override property in `options` from `same-name property` only after check for `undefined` (I can write util function for this). [Like this](https://github.com/KoRiGaN/Vue2Leaflet/blob/master/src/mixins/Path.js#L90), but now this code useless, because `default` values of properties not set to `undefined`

If my solution is right, I can make the necessary changes and create a PR.

**Comment by steventlee** [comment]
Here is another example with the same issue I discovered.

lStyle not set
vue2leaflet 1.0.2 version
[https://jsfiddle.net/fj06pq7y/](https://jsfiddle.net/fj06pq7y/)

individual assign property work fine but not as an object
does not work
`<l-circle 
        :lat-lng="marker"
        :radius="Math.sqrt(200) * 50000"
        :visible="true" 
        lStyle="{color:red}"   />`

work
`<l-circle 
        :lat-lng="marker"
        :radius="Math.sqrt(200) * 50000"
        :visible="true" 
        :color="red"   />`

Thank you for all the hard works.
