### ISSUE TITLE
Tooltip and Popup with Polygon

### ISSUE THREAD

**Issue by jkermes** [KoRiGaN/Vue2Leaflet#26]
Hi,

I have a problem with tooltips and popups.
It works perfectly with markers, but don't seems to work with polygon.

JSFiddle example: [https://jsfiddle.net/k04zpLx9/18/](https://jsfiddle.net/k04zpLx9/18/)

Did I miss something ?

Thanks!

**Comment by KoRiGaN** [comment]
It was a bug. This should be fixed in the next release.

**Comment by KoRiGaN** [comment]
Implemented in v0.0.45

**Comment by goors** [comment]
@KoRiGaN i sorry, but how to draws stuff with mouse, like this polygon or circle? I mean hot to activate that control? Btw i need bunch of polygons and bunch of circles.
