### ISSUE TITLE
"Quick Start Guide" link doesn't link to a guide

### ISSUE THREAD

**Issue by towc** [KoRiGaN/Vue2Leaflet#262]
### Description

There's a link in the README that points to https://korigan.github.io/Vue2Leaflet/, which to me seems to be a collection of examples, yet the link is called "Quick Start Guide"

**Comment by lordfuoco** [comment]
@towc we are working on a documentation full rewrite :) thank you for taking the time to write an issue!

**Comment by BryTack** [comment]
For a Vue beginner, that's me, some very basic examples would be very useful.  The equivalent of a 'Hello World' example please.

**Comment by lordfuoco** [comment]
@BryTack the examples are already there! but they will be enhanced in the new docs!

**Comment by natezhengbne** [comment]
I am looking forward to the new document and new example

**Comment by lordfuoco** [comment]
@BryTack @natezhengbne you can head to the new docs already! ( if you don't see them please do an hard refresh of the page ) 
https://korigan.github.io/Vue2Leaflet/#/

**Comment by dewey** [comment]
FYI: The link to "Examples" doesn't work from https://korigan.github.io/Vue2Leaflet/#/: https://korigan.github.io/examples/

**Comment by lordfuoco** [comment]
@dewey thank you for letting me know!

**Comment by lordfuoco** [comment]
@dewey fixed the link, a refresh and it should work, closing this!

**Comment by maratumba** [comment]
The quick start guide link on the [readme](https://github.com/KoRiGaN/Vue2Leaflet/blob/master/README.md) (https://github.com/KoRiGaN/Vue2Leaflet/blob/master/quickstart.md) seems not to be working again.

**Comment by DonNicoJs** [comment]
@maratumba thanks fixed the link!
