### ISSUE TITLE
Move build system to vue-cli

### ISSUE THREAD

**Issue by lordfuoco** [KoRiGaN/Vue2Leaflet#263]
I want to move the build system to vue-cli and better integrate the examples.

Two objectives: 
- better development workflow
- webpack 4

**Comment by benzkji** [comment]
what do you mean exactly? integrate with the new vue-cli 3 plugin system, and the so called "generator", that will update all needed webpack configurations for vue2leaflet? +100, then!

I am currently beginning a new Vue project, and struggling how to get the vue2leaflet css into my vue-cli 3 based project. A quick tip would be nice;-)

**Comment by lordfuoco** [comment]
The issue is actually meant for the development experience / build size.

But not that you mention it It would be really cool to be able to use the Vue cli generators!
