### ISSUE TITLE
No load event

### ISSUE THREAD

**Issue by imShara** [KoRiGaN/Vue2Leaflet#265]
I have number of maps and I need to fit map bounds to markers by default. Markers creats with `v-for`. But there is no [load-like](https://github.com/KoRiGaN/Vue2Leaflet/issues/51) event to attach.

Original problem can be solved [like this (JSFiddle)](https://jsfiddle.net/k04zpLx9/3497/) in my case. With nuxt-leaflet, leaflet [should also be imported](https://stackoverflow.com/questions/53075106/vue2-leaflet-with-no-ssr-causes-window-is-not-defined-error/53085343#comment93066396_53080923)

**Comment by bezany** [comment]
@imShara In current version exists event ['leaflet:load'](https://github.com/KoRiGaN/Vue2Leaflet/blob/master/src/components/LMap.vue#L101)
May this event be useful https://jsfiddle.net/42rkhemy/4/
