### ISSUE TITLE
Can't use <router-link> Inside the GeoJson2Popup.vue

### ISSUE THREAD

**Issue by tamanna-makkar** [KoRiGaN/Vue2Leaflet#266]
I am using the Latest features of geoJson version 1.1.1
on some point, I have to show popup on click on polylines/polygons/point, and Inside that Popup I have to use `<router-link>`

I used like this as below ----

```
function onEachFeature (feature, layer) {
  let PopupCont = Vue.extend(PopupContent);
  let popup = new PopupCont({ propsData: { text: feature.properties.popupContent } });
  layer.bindPopup(popup.$mount().$el);
}
```
and PopupContent is my another vue Component, I'm using `<router-link> `inside the PopupContent.vue but it is not working `TypeError: Cannot read property 'resolve' of undefined`

Can somebody please suggest me the possible ways to solve it

**Comment by bezany** [comment]
Hmmm... Looks like problem in manual create component. When you call `new PopupCont(...)` component not get router object. For example [same problem](https://github.com/vuejs-templates/webpack/issues/709)
I don't know right solution. Maybe add an instance of `router` to the argument list for `new PopupCont(...)`. Or add `PopupContent` component in template and copy content when binding Popup.

**Comment by lordfuoco** [comment]
You can put your router link in the popup markup as a slot and in that case It will work.

If you need. To use it with extend as you are doing you need to explicit pass the router instance (and the store and so on) during extend as a config object

**Comment by tamanna-makkar** [comment]
Ahh, many thanks for the reply,
So I can manage separate component for popup and can use `<router-link>` as a slot
and how can I use that `PopupContent`( separate popupComponet ) Inside the onEachFeature() ?

**Comment by lordfuoco** [comment]
@tamanna-makkar can you specify better the last question ? maybe a code example ?
