### ISSUE TITLE
L.divIcon with rendered HTML-Code

### ISSUE THREAD

**Issue by byWulf** [KoRiGaN/Vue2Leaflet#267]
Hello,

as far as I see it is not currently possible to generate the HTML code for a divIcon (later used for a marker) easily with a template of vue, but instead it as a string. If I missed something, please tell me :)

If this does really not exist, I could imagine of an implementation like this:
```
<l-marker :lat-lng="[51.218963, 6.796855]">
    <l-icon class="someCustomClasses" :icon-anchor="[0, 134]">
        <h1>Headline</h1>
        <img src="foobar.png">
        <p>And this is some text</p>
    </l-icon>
</l-marker>
```
This could also be used for normal `L.icon`s:
```
<l-marker :lat-lng="[51.218963, 6.796855]">
    <l-icon icon-url="foobar.png" :icon-anchor="[0, 134]" />
</l-marker>
```

Is this possible with vue? If yes, I would be happy to implement it on my own and post a PR :)

Thanks a lot for your work guys!

**Comment by lordfuoco** [comment]
Mmh so, l-marker need to add the icon instance when is loaded. But what we could do is that the `l-icon` component my use find real parent to detect the marker and then call a set Icon method to set itself.

We would need to pay attention to the performance. 

Would you be up to it? If so go on with a PR

**Comment by lordfuoco** [comment]
@byWulf closing this since the PR is merged!
