### ISSUE TITLE
Enhancement: Expose property to enable/disable the zoom button layer.

### ISSUE THREAD

**Issue by InfoSec812** [KoRiGaN/Vue2Leaflet#269]
As a developer creating an app which tracks the user's current position on a mobile device, I would like the ability to disable the zoom in/out button layer on the map view. The attribute in the Leaflet project is called `zoomControl` and should be relatively easy to expose. I will try to submit a PR shortly for this feature.

**Comment by nparley** [comment]
You can do this at the moment by just using `:options={ zoomControl: false }` on the LMap component.
