### ISSUE TITLE
"style" is a reserved attribute

### ISSUE THREAD

**Issue by jkermes** [KoRiGaN/Vue2Leaflet#27]
Hello,
I have an issue using polygons with vue-devtools:
`[Vue warn]: "style" is a reserved attribute and cannot be used as component prop"`
The warning happens with Polygon, LCircle, Polyline and Rectangle components.

Thanks!

**Comment by KoRiGaN** [comment]
@jkermes I think the best way to go is to map a "l-style" property to leaflet style option

**Comment by KoRiGaN** [comment]
You can bind your style to lStyle property (l-style).

Available from version v0.0.47

**Comment by jkermes** [comment]
Perfect! Thank you very much :)
