### ISSUE TITLE
How to include plugin into project? Does project have any documentation?

### ISSUE THREAD

**Issue by thescs** [KoRiGaN/Vue2Leaflet#271]
main.js
`import L from 'vue2-leaflet'
import 'leaflet/dist/leaflet.css'
Vue.use(L)`

test.vue
`<l-map ref="map" :zoom=13 :center="[47.413220, -1.219482]">
            </l-map>`

Then error:
**[Vue warn]: Unknown custom element: `<l-map>` - did you register the component correctly?**

**Comment by lordfuoco** [comment]
@thescs You can import leaflet component by component as follows:
```
import Vue from 'vue';
import Vue2Leaflet from 'vue2-leaflet';

import L from 'leaflet';
delete L.Icon.Default.prototype._getIconUrl;

L.Icon.Default.mergeOptions({
  iconRetinaUrl: require('leaflet/dist/images/marker-icon-2x.png'),
  iconUrl: require('leaflet/dist/images/marker-icon.png'),
  shadowUrl: require('leaflet/dist/images/marker-shadow.png')
});

Vue.component('l-map', Vue2Leaflet.LMap);
Vue.component('l-tilelayer', Vue2Leaflet.LTileLayer);
Vue.component('l-marker', Vue2Leaflet.LMarker);
Vue.component('l-tooltip', Vue2Leaflet.LTooltip);
Vue.component('l-popup', Vue2Leaflet.LPopup);
Vue.component('l-control-zoom', Vue2Leaflet.LControlZoom);
Vue.component('l-geo-json', Vue2Leaflet.LGeoJson);
Vue.component('l-feature-group', Vue2Leaflet.LFeatureGroup);

```
also you need to load the css: 
```
<style lang="less" >
@import "../../node_modules/leaflet/dist/leaflet.css";
</style>

**Comment by lordfuoco** [comment]
I know that the documentation is lacking, we are catching up on it :)

**Comment by abreitenfeld** [comment]
Same problem here. Also the example project is not working out of the box since `package.json` does not includes `vue2-leaflet` itself and it tries to locate some leaflet resources in the parent `node_modules` folder. Is it an option to decouple the example project from the parent node project.

**Comment by lordfuoco** [comment]
@abreitenfeld the examples are meant to work with `npm link` but yeah docs and better examples are on the way

**Comment by thescs** [comment]
> @thescs You can import leaflet component by component as follows:
> 
> ```
> import Vue from 'vue';
> import Vue2Leaflet from 'vue2-leaflet';
> 
> import L from 'leaflet';
> delete L.Icon.Default.prototype._getIconUrl;
> 
> L.Icon.Default.mergeOptions({
>   iconRetinaUrl: require('leaflet/dist/images/marker-icon-2x.png'),
>   iconUrl: require('leaflet/dist/images/marker-icon.png'),
>   shadowUrl: require('leaflet/dist/images/marker-shadow.png')
> });
> 
> Vue.component('l-map', Vue2Leaflet.LMap);
> Vue.component('l-tilelayer', Vue2Leaflet.LTileLayer);
> Vue.component('l-marker', Vue2Leaflet.LMarker);
> Vue.component('l-tooltip', Vue2Leaflet.LTooltip);
> Vue.component('l-popup', Vue2Leaflet.LPopup);
> Vue.component('l-control-zoom', Vue2Leaflet.LControlZoom);
> Vue.component('l-geo-json', Vue2Leaflet.LGeoJson);
> Vue.component('l-feature-group', Vue2Leaflet.LFeatureGroup);
> ```
> also you need to load the css:
> 
> ```
> <style lang="less" >
> @import "../../node_modules/leaflet/dist/leaflet.css";
> </style>
> ```

its fucking is not working.
and i must to use that fucking google maps...

**Comment by lordfuoco** [comment]
@thescs what is not working? Do you have error messages? Like this is very hard to help you solve your problem

**Comment by lordfuoco** [comment]
Closing and locking  this since is not a constructive conversation, and rude behaviour is not appreciated here. 
@abreitenfeld if you still need any help feel free to open another issue
