### ISSUE TITLE
Cannot read property 'x' of undefined while adding styles to the pointToLayer conditionally

### ISSUE THREAD

**Issue by tamanna-makkar** [KoRiGaN/Vue2Leaflet#272]
I'm using `pointToLayer()` to style the points in geoJson, am using `switch cases` with in the `pointToLayer()` like below

```
pointToLayer: function (feature, latlng) {
          switch (feature.properties.startJaar) {
            case 2018 : return L.circleMarker(latlng, {
              color: '#86F0FF'
            })
            case 2019 : return L.circleMarker(latlng, {
              color: '#86F0FF'
            })
            default: return L.circleMarker(latlng, {
              color: '#000000'
            })
          }
        }
```
but when I use switch cases, then I got `Cannot read property 'x' of undefined` Even I defined the default case In case if property "startJaar" not accounted by any case, then It can use default case

this issue arose with updated vue2-leaflet version(1.1.1), but working fine with the last (1.0.2) version
Can anybody please suggest something

**Comment by lordfuoco** [comment]
Can you send over the geo JSON that you are using please?

**Comment by tamanna-makkar** [comment]
yeah, this is the way am using geoJson

`<l-geo-json v-if="projects.features" :geojson="projects" :options="options"/>`

```
computed: {
   options () {
      return {
        onEachFeature: this.onEachFeatureFunction,
        pointToLayer: function (feature, latlng) {
          switch (feature.properties.startJaar) {
            case 2018 : return L.circleMarker(latlng, {
              fillColor: '#FBC94D',
              weight: 1,
              radius: 8
            })
            case 2019 : return L.circleMarker(latlng, {
              fillColor: '#0181C6',
              weight: 1,
              radius: 8
            })
            default: return L.circleMarker(latlng, {
              fillColor: '#000',
              weight: 1,
              radius: 8
            })
          }
        }
      }
    },
}
```

**Comment by lordfuoco** [comment]
@tamanna-makkar pointToLayer is a leaflet function.
if you want to use L.circleMarker you need to import L in your component.
What changed in 1.1.1 is that we are using the leaflet 1.3.4. 
can you try to console log the params in point to layer and see if some data is missing?

**Comment by tamanna-makkar** [comment]
yes I need to import L into my coponent, see I consoled params and they are properly working

![error](https://user-images.githubusercontent.com/32664347/48059450-423c3a00-e1df-11e8-8fe1-55558e12c2e1.png)

**Comment by lordfuoco** [comment]
To help you i would need access to the code, and check few stuff. Only the componente that makes the geo JSON and geo JSON itself.

Any chance you can put it con codesandbox or code pen?

**Comment by lordfuoco** [comment]
@tamanna-makkar please check here
https://github.com/KoRiGaN/Vue2Leaflet/issues/281

**Comment by tamanna-makkar** [comment]
Ahh! Much thanks, so am gonna closing from here
