### ISSUE TITLE
Enhancement: Expose property to set zoomSnap value and ability to set fractional zoom level.

### ISSUE THREAD

**Issue by kbedra-tbscg** [KoRiGaN/Vue2Leaflet#273]
I need to set a fractional value for zoom level like 4.5 or 2.25. 
In the documentation for leaflet: https://leafletjs.com/examples/zoom-levels/ there is an optional variable to enable fractional values: snapZoom. 
Also zoom, minZoom and maxZoom props need to be changed to type 'String' to be able to put fractional numbers.

**Comment by lordfuoco** [comment]
@kbedra-tbscg marking this as an enhancement and picking it up soon

**Comment by lordfuoco** [comment]
@kbedra-tbscg on a second note.
You can already do this, by passing `zoomSnap` in the options of the `l-map`
I've updated the simple example to include this in action.

**Comment by kbedra-tbscg** [comment]
Thank you for your reply. Indeed, I can set zoomSnap by setting options, I didn't know that. But now, the problem is hat LMap component have "zoom" prop validated as Number, not String so I can't set fractional zoom as initial value. In the example you updated, you have changed  "currentZoom" value which is now different than "zoom". The map remain set on whole level number 13.

**Comment by lordfuoco** [comment]
If you zoom in the map it will scroll down 0.5 by 0.5.

Since the prop is a Number you can pass 0.1 or any other decimal.

Or am I missing something?

**Comment by kbedra-tbscg** [comment]
Sorry, my mistake. Everything is fine, thanks. Can be closed.

**Comment by lordfuoco** [comment]
@kbedra-tbscg glad to be of help!
