### ISSUE TITLE
Roll back to leaflet 1.3.1: markercluster plugin broken 

### ISSUE THREAD

**Issue by lordfuoco** [KoRiGaN/Vue2Leaflet#277]
Apparently leaflet 1.3.4 breaks markercluster plugin.
This is the result of a quick test that I did.
If anyone wants to test / chime in is welcomed.
I will test this more in the coming days  @jperelli  maybe you are interested

**Comment by jperelli** [comment]
Is there an upstream issue? I didn't find it in leaflet-markercluster repository

**Comment by lordfuoco** [comment]
@jperelli I did not check but with leaflet 1.3.4 there is an error in the console about the markercluster constructor

**Comment by lordfuoco** [comment]
related to https://github.com/KoRiGaN/Vue2Leaflet/issues/281
