### ISSUE TITLE
Adding a custom pane

### ISSUE THREAD

**Issue by X1machinemaker1X** [KoRiGaN/Vue2Leaflet#278]
How might I go about adding a custom pane? I was going to do it in the map load event but that doesnt seem to be working correctly. The load event isnt firing. 

(btw, I asked on stackoverflow first, and no one knew)

**Comment by lordfuoco** [comment]
Hi! No problem in asking here.
You can wait for the event: `leaflet:load` on the `l-map` component and then use a ref on the map component to do: `this.$refs.myrefname.mapObject.anyLeafletMethodHere()`

**Comment by X1machinemaker1X** [comment]
hmm, when I try to add a method to the leaflet:load event, (I was using the ready event before and it still gave me the same results), it says this is undefined.

**Comment by lordfuoco** [comment]
@X1machinemaker1X are you listening to the event like this ?
```
 <l-map
        ref="mainMap"
        :zoom="zoom"
        :world-copy-jump="true"
        :options="mapOptions"
        @leaflet:load="setMapReady(true)"
      >
```

also what version are you using ?

**Comment by X1machinemaker1X** [comment]
I was referencing this is the wrong spot. I got it to work. thanks
