### ISSUE TITLE
Move leaflet to peerDependencies?

### ISSUE THREAD

**Issue by nparley** [KoRiGaN/Vue2Leaflet#279]
Webpack will use isolated leaflets if the version of leaflet differs in your `package.json` file compared to the version in the requires from Vue2Leaflet. 

For example using the Leaflet.pm plugin (https://github.com/codeofsumit/leaflet.pm), the leaflet map constructer is modified. If the versions different importing leaflet.pm will not affect the version Vue2Leaflet is using and so the map will not be constructed with the plugin added.

The change would require the user to import leaflet before Vue2Leaflet. This seems to be done for a lot of leaflet plugins which don't require leaflet in the `package.json`.

This is a breaking change and probably needs thinking about, and I guess doesn't affect that many people. But I thought I would add it as a discussion as it did trip me up with making leaflet.pm work with Vue2leaflet.  

Or maybe exporting leaflet would be enough for this edge case so you could do:

```
import { L } from "vue2-leaflet";
import "leaflet.pm";
```

have not tested this though.

**Comment by lordfuoco** [comment]
Ehi! Thank you for the issue.
Problem is that being this a wrapper around leaflet we need to be very careful on the leaflet version. 
Because some methods that we use may not be available in a different version. 

We can export the imported leaflet tho!
This is rather simple and I will introduce this soon!

**Comment by nparley** [comment]
Thanks 👍

**Comment by lordfuoco** [comment]
@nparley Done in version 1.2.3.
This also let me open a discussion for plugin devs. I am making a separate issue out of this.

**Comment by nparley** [comment]
Yep. Might as well close this issue but link it to https://github.com/KoRiGaN/Vue2Leaflet/issues/281.
