### ISSUE TITLE
Leaflet version and version lock [FOR PLUGIN DEVS  / USERS]

### ISSUE THREAD

**Issue by DonNicoJs** [KoRiGaN/Vue2Leaflet#281]
After two days of debugging I finally managed to grasp an issue that I was having on some personal projects ( vue people and others ).
As it stands leaflet used to export itself to the window object, in more recent version they also have an es6 module version.
Most of the leaflet plugins uses the window object so they keep exporting it.
Now there are some edge cases that completely breaks both vue2-leaflet and the plugins if there is a mismatch version from what version vue-leaflet declare is different from the one declared both in the vue-leaflet-plugin and the leaflet-plugin.

I'll make an example with markercluster plugin.
vue-leaflet declare as dependency leaflet: 1.3.4
leaflet.markercluster declare as dependency: leaflet 1.3.1

They are just patch releases so it should be all fine.

What happens instead is that webpack see the two differences and load two leaflet instances.
now everything still works MINUS when:

leaflet markercluster declare a new class say: `const a = new LatLngBounds([lat, lon]).`
and then uses the leaflet method to check if that bound intersect with other markers.
Since that method check `a instanceof LatLngBounds` and that `LatLngBounds` is coming from a DIFFERENT leaflet instance that check will pass false and then everything will start behaving bad / breaking

Everything is fine if all the leaflet versions are set at the same since only one distance of leaflet is instantiated.
@jperelli 

EDIT FOR CLARITY:

A solid workaround for this is to use Aliases to point to a single leaflet root instance, for example in nuxt 1.x ( I believe 2.x too )  one would do:

```js
build: {
  extend(config){
    config.resolve.alias['leaflet'] = path.join(__dirname, 'node_modules/leaflet');
  }
}
```

**Comment by nparley** [comment]
This explains the problem: https://lexi-lambda.github.io/blog/2016/08/24/understanding-the-npm-dependency-model/

Why use peer dependencies https://stackoverflow.com/questions/26737819/why-use-peer-dependencies-in-npm-for-plugins

**Comment by nparley** [comment]
Adding unit tests with different leaflet versions would be nice too, to help find out about problems

**Comment by imudin** [comment]
@lordfuoco Making the same version of leaflet is not solving the issue

**Comment by lordfuoco** [comment]
@imudin To understand your problem can you please post down all the version of the leaflet related repo that you are using ?

**Comment by imudin** [comment]
@lordfuoco Now I works. I was using [vue2-leaflet-path-transform](https://github.com/imudin/vue2-leaflet-path-transform) locally. I  added it to my main project in this way `npm i /path/to/vue2-leaflet-path-transform`. After I published the plugin with leaflet@1.3.1 and vue2-leaflet@1.0.2 it is working. Even I updated leaflet of main project to v1.3.4.

**Comment by lordfuoco** [comment]
@imudin Great! So you are the author of vue2-leaflet-path-transform?
if so please state leaflet as a peerDependecy in your repo ( or not at all ) so that we can avoid this issue in the future

**Comment by imudin** [comment]
@lordfuoco Okay I will! thank you for your time 👍

**Comment by jperelli** [comment]
Hi! Sorry for the delay! I removed the dependendency from vue2-leaflet-markercluster, The package is already published in npm. I'm using import { L } from Vue2Leaflet instead whenever I need it

**Comment by lordfuoco** [comment]
@jperelli Thank you very much! I am in the process or building up 2.0.0 as a major change were leaflet is a peerDependency, I will try to submit a PR for your plugin to address the Leaflet import :)

**Comment by jperelli** [comment]
ok @lordfuoco! let me know of any help you need. We are working with @marcosfede on upgrading https://github.com/cualbondi/web-buscador to be able to use leaflet's esm (tree shaking) to reduce the size of the bundle.

**Comment by lordfuoco** [comment]
@jperelli the idea of this 2.0.0 is exactly to enable tree-shaking, where every vue2-leaflet component import only is own counterpart in leaflet

**Comment by lordfuoco** [comment]
@bytesnz yeas I am in the process to do so, but with `leaflet: "^1.3.4"`

**Comment by bytesnz** [comment]
That will mean it will be able to have peer version of 1.3.2, which you wanted to avoid (https://github.com/KoRiGaN/Vue2Leaflet/issues/281#issuecomment-437692435), didn't you?

**Comment by lordfuoco** [comment]
@bytesnz according to documentation ^1.3.4 should skip 1.3.2 :

^1.2.3 := >=1.2.3 <2.0.0

**Comment by bytesnz** [comment]
Ah yes. Is there any reason not to allow <1.3.2 though?

**Comment by bytesnz** [comment]
Only that version is bugged though correct? So using less than 1.3.2 should be fine as well?

**Comment by lordfuoco** [comment]
@bytesnz correct but we want 1.3.4 because it allow us to implement code splitting

**Comment by ciolt** [comment]
Finally! I was getting a frustrating error whenever I tried to add polylines dynamically. 

This workaround fixed it, @lordfuoco could this be added to the docs as a special note? I think it'd help save a lot of people (like me) time with debugging

**Comment by lordfuoco** [comment]
@ciolt a PR would help :) I am bit swamped with work and behind here

**Comment by kaboume** [comment]
Hi,
I'm using Nuxt 2.4.5 (last version), and I have the error "Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'" when the mouse hover a marker.

I  tried to put the workaround alias but it doesn't work 

```
build: {
    extractCSS: true,
    vendor: ["vue-notifications"],
    extend(config) {
      config.resolve.alias["leaflet"] = path.join(
        __dirname,
        "node_modules/leaflet"
      );
    }

```

The build says 

> ERROR  path is not defined

**Comment by ciolt** [comment]
@kaboume Add `const path = require('path');` at the very top of the same file

**Comment by kaboume** [comment]
Thank you!
After executed "npm install --save path" and added "const path = require("path");" at the top of the nuxt.config.js file, everything works fine.

**Comment by DonNicoJs** [comment]
@ciolt @kaboume did you try the new 2.0 ? it should fix the issue without workaround

**Comment by kaboume** [comment]
No I didn't. I will try. Thank you.

**Comment by DonNicoJs** [comment]
since 2.x is out since a while closing this
