### ISSUE TITLE
Any way to get leaflet-search to work with vue2leaflet?

### ISSUE THREAD

**Issue by X1machinemaker1X** [KoRiGaN/Vue2Leaflet#284]
ive tried several ways to get [leaflet-search](https://github.com/stefanocudini/leaflet-search) to work. And I cant figure it out, or even if its possible. I supposed I could create my own search functionality, but I wanted to try this first.

**Comment by X1machinemaker1X** [comment]
I think the main issue is being unable to give the search option for the layer as it requires a LayerGroup object, not the name of it.

**Comment by lordfuoco** [comment]
@X1machinemaker1X can you share a piece of code where this is implemented ?

**Comment by X1machinemaker1X** [comment]
I just ended up making my own search thing. it was simpler. sorry
