### ISSUE TITLE
Large number of clustered markers with custom icons on canvas, reactivity and click event

### ISSUE THREAD

**Issue by pixels-for-breakfast** [KoRiGaN/Vue2Leaflet#286]
Hi,

I'm having a hard time getting the following situation working.

**Map**
At first I had about 30 items, which worked great, showing inside clusters. Now that I have a 'large' number of markers (~1500 at the moment, 5.000+ potentially), the performance dropped drastically. Because of these performance issues they are now added from script using `L.markerClusterGroup`, addTo(map), etc, no longer from the template. The performance improved, altho' it can probably improve even more when I get my custom icon/image rendered on a canvas-layer.

**List**
The same items shown as markers on the map are also rendered as 'li' inside a list. These items are inside my Vuex state. I bound a click event to both the markers and list-items (using '@click') calling a Vuex action.

Since I needed to move them from template to script, I don't have reactivity anymore; my selected-status is not updating on both marker and list-item. And switching default-icon/selected-icon is no longer working either.

- Is it possible to render markers (in chunks) to a canvas-layer from the template to improve performance when having large numbers of items?
If not...
- How would I bind a click event to each marker, keeping it reactive and calling the proper Vuex action to change the state?
- How can I change the icon of a marker when it is clicked (selected: true)? And how would I restore to the default icon when selected is false again?

**Comment by lordfuoco** [comment]
Hi!

So performance problems arise when you put content inside the marker, with the latest version if the maker has no children it's not drawn in the Dom. 
If for example you have popup or tooltip move them out and use an even to show them. 

For icons I suggest you check the source code of vue-people where we consistently handle 2k markers each with  a custom icon.

Also pay triple attention that you don't have uneccessary repaints of the markers.

**Comment by lordfuoco** [comment]
About fitBounds you can run that on $nextTick() and it should do the trick but I would need see some code to understand better your situation.

You can bind the click and you should not incur in any performance issue, what version of this library are you using ?

**Comment by lordfuoco** [comment]
Closing this since it was solved through Discord
