### ISSUE TITLE
Step of Zoom

### ISSUE THREAD

**Issue by flerko** [KoRiGaN/Vue2Leaflet#287]
Hello!

How can I change step of zoom on an existing map?
As an example:
`<l-map :zoom="zoom"
           :minZoom="0"
           :maxZoom="4"
           :zoomSnap="0"
           :zoomDelta="0.25"
           :center="center"
           ref="Hall"
           :crs="crs">
<l-map>`

zoomSnap and zoomDelta doesn't work

Or: 
`
mounted() {
  this.$nextTick(() => {
    let map = this.$refs.Hall.mapObject;
    console.log(map.getZoomScale());
  });
}
`
returned NaN value

What am I doing wrong?

Thanks!

**Comment by lordfuoco** [comment]
Hi! Which version of vue-leaflet are you using?

**Comment by flerko** [comment]
1.0.2

**Comment by lordfuoco** [comment]
https://github.com/KoRiGaN/Vue2Leaflet/blob/master/examples/src/components/Simple.vue

You can check this example on how to use zoomSnap through the options props

**Comment by flerko** [comment]
It's works for me.
So much thanks!

**Comment by madurachanna** [comment]
Hey, @DonNicoJs . I had the same problem and https://github.com/KoRiGaN/Vue2Leaflet/blob/master/examples/src/components/Simple.vue
giveshttps://github.com/KoRiGaN/Vue2Leaflet/blob/master/examples/src/components/Simple.vue page not found!

**Comment by Vicellken** [comment]
> Hey, @DonNicoJs . I had the same problem and https://github.com/KoRiGaN/Vue2Leaflet/blob/master/examples/src/components/Simple.vue page not found!
> Wanted to set zoom to 1.25!

https://vue2-leaflet.netlify.app/examples/simple.html
