### ISSUE TITLE
Binding events?

### ISSUE THREAD

**Issue by MichalKrakow** [KoRiGaN/Vue2Leaflet#29]
Well some example would be awesome

**Comment by KoRiGaN** [comment]
I agree more documentation and examples would be great.

All event binding can be done to event called l-[leaflet_event]
Where [leaflet_event] is the name of the event from leaflet.

For example if you want to bind to leaflet marker move event, you can bind to Vue2Leaflet.Marker l-move event.

**Comment by MichalKrakow** [comment]
Works as described. Thanks.
