### ISSUE TITLE
How to access and add polylines to multiple maps using vue2leaflet

### ISSUE THREAD

**Issue by benjinne** [KoRiGaN/Vue2Leaflet#293]
Hi, I asked a question on stackoverflow, but I wasn't able to use the Vue2Leaflet tag, because it required more than 1000 reputation. Here's the link: https://stackoverflow.com/questions/53662238

### Description
I'm trying to create a page containing multiple maps with polylines by using v-for. I tried to use the leaflet:load event to call a method after the map has been loaded, but the event doesn't seem to exist.

Here is my idea, although I know it doesn't work.

Does anyone have some suggestions on how I could accomplish this?

    <template>
        <div>
            <div v-for="map in maps" :key="map.id">
                <l-map style="height:500px; width:500px" 
                       @leaflet:load="insertPolyline">
                    <l-tile-layer :url="url" :attribution="attribution"/>
                </l-map>
            </div>
        </div>
    </template>
    
    <script >
    import { LMap, LPolyline, LTileLayer} from 'vue2-leaflet';
    
    export default {
    components: {
        LMap,
        LPolyline,
        LTileLayer
      },
    data() {
        return {
            mapsLoaded: false,
            maps: [],
            url:'http://{s}.tile.osm.org/{z}/{x}/{y}.png',
            attribution:'&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> 
                         contributors',
        }
    },
    
    mounted() {
        this.maps.push('test1')
        this.maps.push('test2')
        this.maps.push('test3')
    },
    
    methods: {
        insertPolyline: function(event) {
            this.$nextTick(() => {
                var map = event.target.mapObject
                var polyline = require( 'google-polyline' )
                var points = polyline.decode( '_p~iF~ps|U_ulLnnqC_mqNvxq`@' )
                L.polyline(points, {
                color: 'blue',
                weight: 5,
                opacity: .7,
                lineJoin: 'round'
                }).addTo(map);
                map.fitBounds(points);
            })
        }
    }
    }
    </script>
    <style>
     @import "~leaflet/dist/leaflet.css";
    </style>

### Browsers Affected
Any

### Versions
- Vue: v3.0.1
- Vue2Leaflet: v1.2.3

**Comment by benjinne** [comment]
I came up with a solution on stackoverflow, here's the solution: https://stackoverflow.com/a/53669903/8233744

**Comment by lordfuoco** [comment]
@benjinne why don't you use the Vue2Leaflet LPolyline component to easily draw them ? you can head to the docs and check it:
https://korigan.github.io/Vue2Leaflet/#/components/l-polyline/

Sorry I can't answer on SO, I don't have points at all there.

**Comment by benjinne** [comment]
@lordfuoco It would have had the same issue with referencing each polyline component inside a v-for loop
