### ISSUE TITLE
Does LTileLayer have bounds prop?

### ISSUE THREAD

**Issue by hubertokf** [KoRiGaN/Vue2Leaflet#294]
Actualy, leaflet have bounds prop to tile-layers. But i didnt find that on vue2leaflet.

**Comment by lordfuoco** [comment]
@hubertokf Hi! yes you are right our mixin is lacking the bound props, I will make a PR for it soon.

Sorry to answer this late I somehow missed the email / snoozed it by mistake

**Comment by lordfuoco** [comment]
@hubertokf I did not forget about this! I was on a much needed Christmas break, I am on it!

**Comment by hubertokf** [comment]
Thank you very much @lordfuoco!

**Comment by hubertokf** [comment]
@lordfuoco I understand that you are busy with your work. I want to contribute with the project, but I need a tip where to code. If you could show me, I will try to fix that! :smile:

**Comment by lordfuoco** [comment]
Hi! You can start by investingating the code I l-tile-layer and tileLayer mixin!
And thank you

**Comment by DonNicoJs** [comment]
Closing this and opening a new issue
