### ISSUE TITLE
Custom keys in url template

### ISSUE THREAD

**Issue by dimtion** [KoRiGaN/Vue2Leaflet#30]
I'm building a custom map from this component and I'm running into a problem.

The url to retrieve the tiles are in the form `http://tile.org.com/{z}/{x}/{y}.png?red={r}&green={g}&blue={b}` and it seems that from the declaration of the [TileLayer component](https://github.com/KoRiGaN/Vue2Leaflet/blob/master/src/components/TileLayer.vue) it is not possible to add [custom keys](http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png?{foo}) in the template.

Is there a workaround ?

Thanks in advance.

**Comment by KoRiGaN** [comment]
Great work on the pull request ! It's now merged and will be in the next release of Vue2Leaflet
