### ISSUE TITLE
undefined error in V1.2.3

### ISSUE THREAD

**Issue by wangxd77** [KoRiGaN/Vue2Leaflet#300]
### Description

Error thrown when load the app. Errors detail is as below:
TypeError: "max2 is undefined"
	intersects webpack-internal:///./node_modules/leaflet/dist/leaflet-src.js:1053:7
	_clipPoints webpack-internal:///./node_modules/leaflet/dist/leaflet-src.js:8247:27
	_update webpack-internal:///./node_modules/leaflet/dist/leaflet-src.js:8292:3
	_reset webpack-internal:///./node_modules/leaflet/dist/leaflet-src.js:7800:3
	onAdd webpack-internal:///./node_modules/leaflet/dist/leaflet-src.js:7748:3
	_layerAdd webpack-internal:///./node_modules/leaflet/dist/leaflet-src.js:6527:3
	whenReady webpack-internal:///./node_modules/vue2-leaflet/node_modules/leaflet/dist/leaflet-src.js:4367:4
	addLayer webpack-internal:///./node_modules/vue2-leaflet/node_modules/leaflet/dist/leaflet-src.js:6549:3
	addLayer webpack-internal:///./node_modules/vue2-leaflet/dist/vue2-leaflet.min.js:1:36739
	boundFn webpack-internal:///./node_modules/vue/dist/vue.esm.js:186:11
	mounted webpack-internal:///./node_modules/vue2-leaflet/dist/vue2-leaflet.min.js:1:32661
	callHook webpack-internal:///./node_modules/vue/dist/vue.esm.js:2818:9
	insert webpack-internal:///./node_modules/vue/dist/vue.esm.js:4012:7
	invokeInsertHook webpack-internal:///./node_modules/vue/dist/vue.esm.js:5760:28
	patch webpack-internal:///./node_modules/vue/dist/vue.esm.js:5965:5
	_update webpack-internal:///./node_modules/vue/dist/vue.esm.js:2573:16
	updateComponent webpack-internal:///./node_modules/vue/dist/vue.esm.js:2691:7
	get webpack-internal:///./node_modules/vue/dist/vue.esm.js:3034:13
	run webpack-internal:///./node_modules/vue/dist/vue.esm.js:3111:17
	flushSchedulerQueue webpack-internal:///./node_modules/vue/dist/vue.esm.js:2877:5
	nextTick webpack-internal:///./node_modules/vue/dist/vue.esm.js:1784:9
	flushCallbacks webpack-internal:///./node_modules/vue/dist/vue.esm.js:1705:14

The error function is 
	intersects: function (bounds) { // (Bounds) -> Boolean
		bounds = toBounds(bounds);

		var min = this.min,
		    max = this.max,
		    min2 = bounds.min,
		    max2 = bounds.max,
		    xIntersects = (max2.x >= min.x) && (min2.x <= max.x),
		    yIntersects = (max2.y >= min.y) && (min2.y <= max.y);

		return xIntersects && yIntersects;
	},

When I downgrade to the Vue2Leaflet v1.0.2,  the app is OK.

### Browsers Affected

- [X] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions
- Leaflet: v1.3.4
- Vue: v2.5.21
- Vue2Leaflet: v1.2.3

**Comment by lordfuoco** [comment]
@wangxd77 do you use other vue2-leaflet plugins ? If so please refer to #281 while we are working on the 2.0 of  vue2-leaflet that will solve this issue for good

**Comment by wangxd77** [comment]
I don't use other plugins, this error arises when I draw the polyline. Thank you.

**Comment by lordfuoco** [comment]
@wangxd77 are you importing leaflet on your own or using import `{ L } from 'vue2-leaflet' `?  anyhow please try to add the webpack alias fix mentioned in #281

**Comment by wangxd77** [comment]
I try to add the webpack alias, but there is errors as below
These dependencies were not found:
* leaflet in ./node_modules/vue2-leaflet/dist/vue2-leaflet.min.js

I import leaflet using   import L from 'leaflet'
The code arise error is as below:
<template>
  <section>
    <l-polyline :latLngs="polyline['24'].latlngs" color="yellow" :weight="1" :opacity="1"></l-polyline>
    <l-polyline :latLngs="polyline['48'].latlngs" color="blue" :weight="1" :opacity="1"></l-polyline>
    <l-marker :latLng="polyline['48'].Bound" :icon="polyline['24'].icon" :opacity="1"></l-marker>
    <l-marker :latLng="polyline['24'].Bound" :icon="polyline['48'].icon" :opacity="1"></l-marker>
  </section>
</template>

<script>
import { LMarker, LPolyline } from 'vue2-leaflet'
export default {
  name: '',
  props: {},
  computed: {},
  components: {LMarker, LPolyline},
  methods: {},
  watch: {},
  data () {
    return {
      polyline: {
        48: {
          latlngs: [[0, 105], [0, 120], [15, 132], [34, 132]],
          icon: this.$L.divIcon({className: '', html: '<div style="color: blue">48</div>', iconSize: [0, 0], bgPos: [0, 0]}),
          Bound: [29.4, 126.2]
        },
        24: {
          latlngs: [[0, 105], [4.5, 113], [11, 119], [18, 119], [22, 127], [34, 127]],
          icon: this.$L.divIcon({className: '', html: '<div style="color: yellow">24</div>', iconSize: [0, 0]}),
          Bound: [29.4, 131.4]
        }
      }
    }
  },
  created () {
  },
  mounted () {
  }
}
</script>

<style scoped></style>

**Comment by DonNicoJs** [comment]
@wangxd77 is this issue still open for you ?

**Comment by wangxd77** [comment]
It has been resolved.
