### ISSUE TITLE
Starting with vue2-leaflet

### ISSUE THREAD

**Issue by josejachuf** [KoRiGaN/Vue2Leaflet#302]
Hi

versions:
leaflet@1.3.1
vue2-leaflet@1.2.3
vue@2.5.21

I tried to use vue2-leaflet in a project with quasar-framework [1] and the result was not good, tiles appear displaced and tiles are always missing.

I thought that it was some problem with quasar I consulted s in forum [2], but then I tried directly with vue with the same result:

https://imgur.com/k9B3ryo
https://imgur.com/9ldgOYG
The test code is based on:  Vue2Leaflet/examples/src/components/WMSLayers.vue

José

[1] https://quasar-framework.org/
[2] https://forum.quasar-framework.org/topic/3013/vue2-leaflet

**Comment by lordfuoco** [comment]
Hi! Did you follow the quickstart guide and imported the CSS too?

**Comment by josejachuf** [comment]
Thanks @lordfuoco, As you say, the following imports were missing

```
import L from 'leaflet'
import 'leaflet/dist/leaflet.css'

delete L.Icon.Default.prototype._getIconUrl

L.Icon.Default.mergeOptions({
  iconRetinaUrl: require('leaflet/dist/images/marker-icon-2x.png'),
  iconUrl: require('leaflet/dist/images/marker-icon.png'),
  shadowUrl: require('leaflet/dist/images/marker-shadow.png')
})
```

**Comment by lordfuoco** [comment]
Closing as is resolved
