### ISSUE TITLE
Binding a class to LMap makes custom classes disappear

### ISSUE THREAD

**Issue by wishinghand** [KoRiGaN/Vue2Leaflet#309]
### Description
No error thrown, but when adding a class via Vue's class bindings to LMap, the map loses a bunch of classes. In my case it makes the tiles white. In the provided demo it doesn't do that exactly, but when inspected, the map is missing a bunch of `leaflet-` prefixed CSS classes after the toggle has been clicked.

#### Live Demo
https://jsfiddle.net/wishinghand/5noybxh2/10/

#### Steps to Reproduce
Setup a button to toggle a Boolean in Vue's data object, defaulted to `false`. When `true` set the cursor to a custom icon.

#### Expected Results
Cursor gets changed to a custom icon and the map acts as normal.

#### Actual Results
The cursor is changed, but the map goes white and disappears, though any polygons/lines and popups stay.

The maps starts with these classes: 
```
vue2leaflet-map
leaflet-container
leaflet-touch
leaflet-retina
leaflet-fade-anim
leaflet-grab
leaflet-touch-drag
leaflet-touch-zoom
```

and only has `vue2leaflet-map` plus the extra class I bound.

### Browsers Affected

- [ x] Chrome
- [x ] Firefox
- [ ] Edge
- [ x] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions
- Leaflet: whatever Vue2Leaflet 1.0.2 uses
- Vue: v2.5.16
- Vue2Leaflet: v1.0.2

**Comment by wishinghand** [comment]
I've figured out a fix that works for me. Instead of binding the class on `LMap.vue`, I bind it on the parent `div`. In the CSS I then select .`.vue2leaflet-map` that's within `.edit-cursor`. This seems to solve all issues. I'm leaving this open due to my belief that binding to `LMap` shouldn't erase a bunch of CSS classes on it.

**Comment by DonNicoJs** [comment]
@wishinghand Sorry for not answering here, this is due to the fact that we bind the leaflet map directly in the component `$el` 
now this is not ideal, but to change this we would need to bind it inside another element inside the component which could be a breaking issue. 

I am not sure how to proceed here, what do you think ? Either way I want to update the docs to specify this quirk.

**Comment by wishinghand** [comment]
I don't think I'm skilled enough to weigh in. I don't know what the alternative to binding to `$el` would be.

**Comment by DonNicoJs** [comment]
Closing this and making a new issue to update the docs
