### ISSUE TITLE
Do not use minified version as main

### ISSUE THREAD

**Issue by imShara** [KoRiGaN/Vue2Leaflet#315]
Because webpack puts sourcemap path in output build of vendors.app.js and browser tries to find it at relative paths.
Problem could be reproduced with nuxt and nuxt-leaflet module which uses vue2leaflet.

Look how it properly made in [vue-mq](https://github.com/AlexandreBonaventure/vue-mq/blob/master/package.json).

**Comment by lordfuoco** [comment]
@imShara webpack uses the module entry as far as I know, I have no problem with my personal nuxt + leaflet instances at all. but in the upcoming 2.0.0 I will put the unminified verision in the main

**Comment by imShara** [comment]
Don't you have same warning in nuxt dev mode?
![679355665-pejqtutaajjzlzlhidrzpfqrsvatseee](https://user-images.githubusercontent.com/4913196/51103712-d389e700-17f4-11e9-9706-311c264cad1b.png)

Let's look at `http://192.168.43.200:3000/_nuxt/vendors.app.js`

```js
/***/ "./node_modules/vue2-leaflet/dist/vue2-leaflet.min.js":
/*!************************************************************!*\
  !*** ./node_modules/vue2-leaflet/dist/vue2-leaflet.min.js ***!
  \************************************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

!function(t,e){ true?module.exports=e(__webpack_require__(/*! leaflet */ "./node_modules/leaflet/dist/leaflet-src.js")):undefined}(window,function(t){return 
<... minified code ...>
.default,e.LPopup=n(36).default,e.LRectangle=n(37).default,e.LTileLayer=n(22).default,e.LTooltip=n(38).default,e.LWMSTileLayer=n(28).default}])});
//# sourceMappingURL=vue2-leaflet.min.js.map

/***/ }),
```

**Comment by imShara** [comment]
I'm using [nuxt-leaflet](https://github.com/schlunsen/nuxt-leaflet) which uses `"vue2-leaflet": "1.0.2"`. 

Importing via 

```js
  /*
  ** Nuxt.js modules
  */
  modules: [
    'nuxt-leaflet'
  ],
```

I'm digging it, there is much modern version of vue2leaflet, but not in npm. I will try to update it manually, thanks

**Comment by lordfuoco** [comment]
@imShara it's the beta version:
https://www.npmjs.com/package/vue2-leaflet

**Comment by DonNicoJs** [comment]
@imShara new version is out, with esm , cjs and umd support
