### ISSUE TITLE
Can WebGL Earth be easily integrated?

### ISSUE THREAD

**Issue by mikebronner** [KoRiGaN/Vue2Leaflet#317]
I noticed on this page (http://examples.webglearth.com) that WebGL Earth is a drop-in for leaflet. Has anyone experimenting using it with Vue2Leaflet, or does this require a separate component be created for this package? I would love to play with this, and might be able to contribute in the future, if additional work is required.

Thanks!

**Comment by bezany** [comment]
@mikebronner Look like `WebGL Earth` library not simple `leaflet` plugin. It is separate project. You do not need `leaflet` or `Vue2Leaflet` for this.

**Comment by mikebronner** [comment]
Thanks @bezany -- I haven't had time to play with it ... I was kind of hoping it wasn't a separate project, so that I could use what I have already built in Vue with it. Might have to create wrapper components for it in Vue to get around it.
