### ISSUE TITLE
Height in percentage

### ISSUE THREAD

**Issue by josejachuf** [KoRiGaN/Vue2Leaflet#324]
Hi all,
When fixed height in **px** works fine, but when I do it in **%** the map disappear

```
<div style="height: 100%; width: 100%;">
    <l-map ref="map"
      :zoom="zoom"
      :center="center"
      :maxZoom="maxZoom"
      style="height: 80%; width: 100%"
      ...
```

In the examples I see that it uses **%** [1]

Jose

[1] https://korigan.github.io/Vue2Leaflet/#/components/l-map/
      

### Browsers Affected

- [X] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions
- Leaflet: v1.3.1
- Vue: v2.5.17
- Vue2Leaflet: v1.2.3

**Comment by josejachuf** [comment]
Sorry, I mean the height inside **l-map**

**Comment by lordfuoco** [comment]
@josejachuf in the example it works because the container of the example has a fixed height.
What I do is to usually use vh /vw to achieve the same as with %

**Comment by josejachuf** [comment]
Thanks @lordfuoco , this work fine
Jose
