### ISSUE TITLE
Reactive marker - debounce not sending last lat lng

### ISSUE THREAD

**Issue by alexbainbridge** [KoRiGaN/Vue2Leaflet#325]
#### Steps to Reproduce
As per #274 - however this is a new issue as a new problem

The debounce function is not sending the LAST lat lng for a dragged marker (but is dragging OK and sending back data every 100 ms as configured).

If you remove the debounce function, all works as expected and the last position is correctly set.

#### Expected Results
The very last position should be sent back from the debounce function

#### Actual Results
A prior position is sent back - which does not correspond to the final resting point of a marker.

This causes user confusion as they are expecting the marker's visual position and the created lat lng to exactly match. 

### Browsers Affected
* Chrome
[Not tested others]

### Versions
- Vue: v2.5.13
- Vue2Leaflet: v1.2.3

Thanks!

**Comment by DonNicoJs** [comment]
This should be resolved in the latest 2.0.0-beta.1.
Could you check it?

**Comment by alexbainbridge** [comment]
@DonNicoJs I will take a look. Might be 10 days though (sorry)
Thanks for addressing!

**Comment by DonNicoJs** [comment]
@alexbainbridge the fix is not on the 2.0.1 stable :)

**Comment by fauzipadlaw** [comment]
not working on 2.0.0-beta.1 as well as it should :/

**Comment by DonNicoJs** [comment]
@fauzipadlaw did you try the latest version? (2.0.3) because we have unit tests ( in this PR https://github.com/KoRiGaN/Vue2Leaflet/pull/365/files ) and the unit test are passing (https://travis-ci.org/KoRiGaN/Vue2Leaflet/builds/516254653?utm_source=github_status&utm_medium=notification)

**Comment by fauzipadlaw** [comment]
I did.
https://jsfiddle.net/6zscu3md/

**Comment by DonNicoJs** [comment]
@fauzipadlaw you need the .sync modifier for it to work :) https://jsfiddle.net/v478n31w/3/

**Comment by fauzipadlaw** [comment]
great, it does work! thank you so much @DonNicoJs

**Comment by mudin** [comment]
@DonNicoJs Thanks a lot. `.sync` saved my day! One more issue is its not updating position on drag :(
