### ISSUE TITLE
How to add eari-leaflets plug in vue2-leaflet?

### ISSUE THREAD

**Issue by HoPGoldy** [KoRiGaN/Vue2Leaflet#326]
**Leaflet has been used** in my project, and there are some reasons Make me need to **add vue2-leaflet** dependencies. But when I added it, I found that some errors had been returned

`TypeError: Cannot read property 'tiledMapLayer' of undefined`

It is called here

```
L.esri.tiledMapLayer({
    url: ...
}).addTo(this.map)
```
so , does uses the leaflet plugin before using vue2-leaflet cause this problem ? If it is , is there any "official" way  to introduce esri-leaflet in vue2-leaflet? 

Thank you

### Versions
- Leaflet: v1.3.1
- Vue: v2.4.2
- Vue2Leaflet: v1.2.3

**Comment by bezany** [comment]
@HoPGoldy Hello!
**About error**
Before `L.esri.tiledMapLayer ...` check output
```javascript
console.log(L.version)
console.log(L.esri)
```
I think possible root of problem in import order of `L` from `leaflet`.
**About integrate L.esri.tiledMapLayer**
I create [simple example](https://jsfiddle.net/bezanyu/hw49p5yL/)
For correct integrate layer with `LControlLayers` component I used [`addLayer` method in `LMap`](https://github.com/KoRiGaN/Vue2Leaflet/blob/master/src/components/LMap.vue#L151) component.
Also you can create component for new layer type base on[ this code](https://github.com/KoRiGaN/Vue2Leaflet/blob/master/src/components/LWMSTileLayer.vue)

**Comment by lordfuoco** [comment]
@bezany Thank you for the good answer, @HoPGoldy  feel free to submit a PR with a new component :)

**Comment by HoPGoldy** [comment]
@bezany Thank you for your reply!

Adding `console.log(L.esri)` is invalid because it is still unrecognizable.

![image](https://user-images.githubusercontent.com/28479777/51649335-fc616780-1fbe-11e9-8b54-407b24415f87.png)

I also think this is the problem caused by the load order , the `L` of the `vue2-leaflet` overrides the `L` of the native `leaflet`.

Here is a solution , not elegant but working :

```html
<html>
</head>
...
    <script src="scripts/map/leaflet.js"></script>
    <script src="scripts/map/esri-leaflet.js"></script>
    <script>
    LL = L
    </script>
...
</head>

...

<body class="calcite">
    <div id="app"></div>
</body>

<script>
    L.esri = LL.esri
</script>
</html>
```

I backed up the `L` in the `LL` after load `esri-leaflet`, and then give `LL.esri` to new `L` after mounting the Vue.

I don't think this is a good way, so I still want to find a better solution.

And Thank you again！

**Comment by lordfuoco** [comment]
Have you tried to not load leaflet from leaflet but only from Vue2Leaflet?

**Comment by HoPGoldy** [comment]
I can't, there are already a lot of native leaflet code in the project, I need to ensure compatibility.

**Comment by lordfuoco** [comment]
@HoPGoldy I see, so stay tuned for 2.0 and this branch #323

**Comment by DonNicoJs** [comment]
@HoPGoldy 2.0 is out and it should solve your issue :)
