### ISSUE TITLE
Workaround for setZoom/setView/panTo bug

### ISSUE THREAD

**Issue by javiertury** [KoRiGaN/Vue2Leaflet#328]
Leaflet has a [bug](https://github.com/Leaflet/Leaflet/issues/2915) triggered when `setZoom` is followed by `setView`. `setView` can not execute correctly until the previous zoom animation has completed.

This is important to Vue2Leaflet since it uses `setZoom` to sync `zoom` and uses `panTo`(which calls `setView`) to sync `center`. See this [codepen](https://codepen.io/anon/pen/bzNPpz), click in `To London` and nothing will work, click `To Paris` or `To Berlin` and center will work but zoom will not.

I propose to pass a property to `l-map`,  `:animate="isAnimated"`. The map would use the methods `mapObject.panTo(latlng, { animate: this.animate })` and `mapObject.setZoom(zoom, { animate: this.animate })`. Animations would be enabled by default, and people hit by this bug can easily disable animations.

Do you know other potential solutions?

**Comment by lordfuoco** [comment]
@javiertury I think this is a good idea! Thank you for reporting it. @javiertury are you on VueLand discord? If so can you shot me a message ? (DonNico)

**Comment by javiertury** [comment]
I'm not on discord, sorry

**Comment by Georift** [comment]
In my use case I would like to disable panning when the center variable is changed. I looked for an option in either leaflet or vue-leaflet and couldn't find anything. Would you be open to me implementing the proposed `:animate="isAnimated"` solution to this bug? It will solve my problem perfectly.

**Comment by lordfuoco** [comment]
@Georift yes I am up to it, I am waiting for a stable 2.0 to proceed with other fixes / features

**Comment by javiertury** [comment]
In the PR above, I use the prop `no-blocking-animations` to disable setZoom and panTo animations, which are the ones causing this problem.

The name of this property is more specific than the previous proposal to avoid confusion. LMap from Vue2Leaflet@2.0.0 has many properties related to animations.

Regarding existing properties, `zoomAnimate` alone can't solve this issue.
