### ISSUE TITLE
Control Layer

### ISSUE THREAD

**Issue by ais-one** [KoRiGaN/Vue2Leaflet#33]
Hi,

If I need to display control layer (adding a few overlays on top of base map), how can I do so?

Map component can trigger "layeradd" event when the overlay is added, unfortunately, this event also triggers when marker is added.

How can I identify if the layer is a TileLayer (not Marker), and if TileLayer, which one is it (I could not find anything to identify that Tile Layer...

I may also need to add various GroupLayer to the control

**Comment by KoRiGaN** [comment]
layeradd event is documented on Leaflet documentation. It is triggered when a layer is added to a map. A marker is a Layer so the event is triggered as well.

You can test what kind of Layer it is by checking if it's an instance of something.
For example :
```
if (layer instanceof L.Marker) {
  console.log('i am an instance of L Marker');
}
if (layer instanceof L. TileLayer) {
  console.log('i am an instance of L TileLayer');
}
```

Adding LayerGroup is not a problem. Please look at the examples provided in the example folder.

**Comment by ais-one** [comment]
Hi I did it another way, I extended the Vue2Leaflet.TileLayer and Vue2Leaflet.LayerGroup components and added "name" to props.

In the mount function, I checked for the type and the name of the child (of the map object) and then formed the baselayer and overlay object arrays, and then after going through the children, created the layer control

**Comment by ais-one** [comment]
LayerGroup works with the control as well... this issue can be closed.

On a side note, this is not related to the issue but I also managed to the tracksymbol plugin work with vue2-leaflet, using the cluster marker as a reference and posted it github and npm, [https://www.npmjs.com/package/vue2-leaflet-tracksymbol](https://www.npmjs.com/package/vue2-leaflet-tracksymbol)
