### ISSUE TITLE
Cannot modify layer order.

### ISSUE THREAD

**Issue by billyhunt** [KoRiGaN/Vue2Leaflet#330]
### Description

When reordering Leaflet layers, they are not reordered on the map.  (first on top)

#### Live Demo
http://jsfiddle.net/billyhunt/yjpmLre6/32/

#### Steps to Reproduce
I would like to be able to reorder the layers when I reorder the underlying array containing the layers.

#### Expected Results
Layers change ordering on map.

#### Actual Results
Layers stay in given order.

### Browsers Affected

- [x ] Chrome
- [x ] Firefox
- [x ] Safari 9

### Versions
- Leaflet: v1.4.0
- Vue: v2.5.17
- Vue2Leaflet: v1.2.3

Thanks.

**Comment by lordfuoco** [comment]
@billyhunt Sadly I could not find any methods to do so in leaflet. ( if I overlooked a way please point it out ) At the moment I think the official way would be with a control layer possibly by adding a ref to it, hiding it from the map via CSS and then use the ref to target this function: `sortFunction` https://leafletjs.com/reference-1.4.0.html#control-layers-sortfunction

**Comment by bezany** [comment]
@billyhunt I found two possible solutions.
First: use `:key=index`.
http://jsfiddle.net/bezanyu/f6kvsjL4/
Second: use leaflet methods `setZIndex`.
http://jsfiddle.net/bezanyu/ubzkhomy/

**Comment by billyhunt** [comment]
Awesome!  Thank you!
