### ISSUE TITLE
No toolbar for draw?

### ISSUE THREAD

**Issue by jlpereira** [KoRiGaN/Vue2Leaflet#331]
Hi guys,

Im trying to add a toolbar to draw geometric figures like this example using the native leaflet library: 
http://leaflet.github.io/Leaflet.draw/docs/examples/full.html

But I didnt found nothing to get it work with vue2-leaflet.

This is possible to do with this lib?

Thanks!

**Comment by lordfuoco** [comment]
@jlpereira well there is no module to integrate that, feel free to create one! in the meantime you can still use the leaflet code in pure JS. do you need help with that?

**Comment by jlpereira** [comment]
Thanks for the answer, @lordfuoco . Im okay to use the leaflet library. I think we gonna move from vue-leaflet to leaflet in our project.

Thanks again!

**Comment by chistov** [comment]
@jlpereira , You can use hack or kind of.
1) npm i leaflet-draw -S (install draw library to your project).
2) Then code similar to this:

```
mounted() {
      this.$nextTick(() => {
      const map = this.$refs.map.mapObject;
      const drawControl = new window.L.Control.Draw({
        position: 'topright',
        draw: {
          polyline: {
            allowIntersection: false,
            showArea: true
          },
          polygon: false,
          rectangle: false,
          circle: false,
          marker: false
        }
      });

      map.addControl(drawControl);

      const editableLayers = new window.L.FeatureGroup().addTo(map);
      map.on(window.L.Draw.Event.CREATED, (e) => {
        // const type = e.layerType;
        const layer = e.layer;

        // Do whatever else you need to. (save to db, add to map etc)
        editableLayers.addLayer(layer);
      });
    });
```

So, 'vue2-leaflet' is only wrapper, but original Leaflet still accessible through window.L.

**Comment by jlpereira** [comment]
Thank you so much for your contribution @chistov but we already moved to the native leaflet library and we already have in working there, we only needed to use geojson and the draw view, so not really reason to use vue2-leaflet. But your contribution is great for other persons that need it on vue.

Thanks again!!

**Comment by kirvt** [comment]
@chistov
Thank you for example. It is the only one can be found on Internet. But unfortunetly this not works for me. Your mounted hook not added drawControl to the map. Could you please show full working example.

**Comment by chistov** [comment]
@kirvt 
Could you please show me with code what do you mean? Because from my code above you can see how control(or drawControl in my case) added to the map. Like so:

```
const drawControl = new window.L.Control.Draw({
...

map.addControl(drawControl);
```

**Comment by kirvt** [comment]
@chistov
`    import { LMap, LTileLayer } from 'vue2-leaflet';
    import 'leaflet/dist/leaflet.css';
    import 'leaflet-draw';

    export default {
        components: {
            LMap,
            LTileLayer
        },
        data() {
            return {
                zoom: 13,
                maxZoom: 22,
                center: L.latLng(53.348767, 83.745534),
                url: '---}',
                attribution: '---',
                mapOptions: {
                    zoomSnap: 1
                },
                windowHeight: window.innerHeight
            };
        },
        mounted() {
            window.addEventListener('resize', () => {
                this.windowHeight = window.innerHeight;
            });

            this.$nextTick(() => {
                const map = this.$refs.map.mapObject;
                const drawControl = new window.L.Control.Draw({
                    position: 'topright',
                    draw: {
                        polyline: {
                            allowIntersection: false,
                            showArea: true
                        },
                        polygon: false,
                        rectangle: false,
                        circle: false,
                        marker: false
                    }
                });

                map.addControl(drawControl);

                const editableLayers = new window.L.FeatureGroup().addTo(map);
                map.on(window.L.Draw.Event.CREATED, (e) => {
                    const layer = e.layer;
                    editableLayers.addLayer(layer);
                });
            });
        }
    }`

Actually I'd just copy-paste your sample code to my vue2leaflet-map component. All it do  is just add new  errors in log:
[Vue warn]: Error in nextTick: "TypeError: Cannot read property 'addControl' of undefined"
TypeError: Cannot read property 'addControl' of undefined

**Comment by chistov** [comment]
It seems like you have to add ref="map" to you html template. Example here:

```
<v-map ref="map" :zoom="zoom"
     :center="center"
     :options='{ zoomControl: false }'
     attribution='© Проект А'>
      <v-tilelayer :url="url" :attribution="attribution"></v-tilelayer>
      <v-geo-json v-for="(gj, idx) in geojson" :geojson="gj.geometry" :key="idx" :options="options(gj.geometry)">
        <v-popup :content="gotoTunnelCard" :options="{ autoClose: false, closeOnClick: false }"></v-popup>
      </v-geo-json>
    </v-map>
```

**Comment by kirvt** [comment]
@chistov
ref was given initially. This is not a case. Which versions of leaflet / vue2-leflet / leaflet-draw you use?

**Comment by chistov** [comment]
package.json:
"vue2-leaflet": "^1.2.3",
 "leaflet-draw": "^1.0.4",

Here is component code:

```
<template>
  <div style="width: 100%;height: 100%; background-color:#eee; position:relative;">
    <v-map ref="map" :zoom="zoom"
     :center="center"
     :options='{ zoomControl: false }'
     attribution='© Проект А'>
      <v-tilelayer :url="url" :attribution="attribution"></v-tilelayer>
      <v-geo-json v-for="(gj, idx) in geojson" :geojson="gj.geometry" :key="idx" :options="options(gj)">
        <v-popup :content="gotoTunnelCard" :options="{ autoClose: false, closeOnClick: false }"></v-popup>
      </v-geo-json>
    </v-map>
  </div>
</template>


<script>
import Vue2Leaflet from 'vue2-leaflet';
import 'leaflet-draw';

export default {
  components: {
    'v-map': Vue2Leaflet.LMap,
    'v-tilelayer': Vue2Leaflet.LTileLayer,
    'v-marker': Vue2Leaflet.LMarker,
    'v-geo-json': Vue2Leaflet.LGeoJson,
    'v-popup': Vue2Leaflet.Popup
  },

  mounted() {
    this.$nextTick(() => {
      const map = this.$refs.map.mapObject;

      this.drawControl = new window.L.Control.Draw({
        position: 'topright',
        draw: {
          polyline: {
            allowIntersection: false,
            showArea: true
          },
          polygon: false,
          rectangle: false,
          circle: false
        }
      });

      window.L.DrawToolbar.include({
        getModeHandlers(_map) {
          return [
            {
              enabled: true,
              handler: new window.L.Draw.Polyline(_map),
              title: 'Добавить тоннель'
            }
          ];
        }
      });

      this.drawControl.setDrawingOptions({ // new lines will have different color
        polyline: {
          shapeOptions: {
            color: '#ff0a1e'
          }
        }
      });

      map.addControl(this.drawControl);

      this.editableLayers = new window.L.FeatureGroup().addTo(map);
      const control = this.drawControl._container.querySelector('.leaflet-draw-toolbar');

      /* Commit drawn tunnel */
      let link = document.createElement('a');
      link.className = 'leaflet-draw-draw-OK_ICON';
      link.style.display = 'none';
      link.onclick = () => {
        this.$store.dispatch('tunnelEdit', this.newTunnel);
        this.$emit('tunnelAdd');
      };
      this.okBtn = control.appendChild(link);

      /* Remove drawn tunnel */
      link = document.createElement('a');
      link.className = 'leaflet-draw-draw-NOK_ICON';
      link.style.display = 'none';
      link.onclick = () => {
        this.okBtn.style.display = 'none';
        this.nokBtn.style.display = 'none';
        this.layers.forEach(l => this.editableLayers.removeLayer(l));
        this.newTunnel = {
          geometry: {
            coordinates: []
          }
        };
      };
      this.nokBtn = control.appendChild(link);

      map.on(window.L.Draw.Event.CREATED, (e) => {
        const layer = e.layer;
        const coords = layer._latlngs.map(objCoordinates => [objCoordinates.lng, objCoordinates.lat] );

        this.newTunnel.geometry.coordinates.push(coords);
        this.newTunnel.categoryDate = 0;
        this.editableLayers.addLayer(layer);
        this.layers.push(layer);
        this.okBtn.style.display = 'block';
        this.nokBtn.style.display = 'block';
      });
    });
  },

  data(){
    return {
      zoom: 13,
      editableLayers: null,
      drawControl: null,
      layers: [],
      okBtn: null,
      cancelBtn: null,
      newTunnel: {
        geometry: {
          type: 'MultiLineString',
          coordinates: []
        }
      },
      center: [55.75583, 37.61778],
      // url: 'http://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}.png',
      url: 'http://10.101.20.207/api/{z}/{x}/{y}.png',
      attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors',
      marker: window.L.latLng(47.413220, -1.219482),
      popupRoot: null,
      tunnel: null,
      tName: 0
    };
  },

  computed: {
    geojson(){ return this.$store.state.TunnelsCategories.tunnels; }
  },

  methods: {
    gotoTunnelCard(tunnel){
      this.$store.dispatch('tunnelEdit', tunnel);
      this.$emit('tunnelCommonInfo');
    },

    renderPopup(tunnel){
      const popupRoot = document.createElement('div');
      popupRoot.setAttribute("id", "leafroot-id");
      const el = document.createElement('button');

      const imgId = (function (id){
        switch(id){
          case 1: return 165;
          case 2: return 67;
          case 3: return 166;
          case 53: return 169;
          case 54: return 170;
          case 12: return 97;
          default: return 1;
        }
      }(tunnel.id));

      popupRoot.innerHTML = '<h5 style="font-weight:bold">' + tunnel.name + '</h5>' +
        '<img class="popup-img" src="imgs/'+ imgId + '_3.png"/>' +
        '<div class="popup-text">Категория: ' + tunnel.category + '</div>' +
        '<div class="popup-text">Дата установки: ' + tunnel.categoryDate + '</div>' +
        '<div class="popup-text">Название дороги: ' + tunnel.roadName + '</div>' +
        '<div class="popup-text length">Длина дороги: ' + tunnel.length + '</div>';


      el.innerHTML = 'Перейти к рассчёту';
      el.classList = 'btn notice-btn btn-secondary';
      el.onclick = this.gotoTunnelCard.bind(this, tunnel);
      popupRoot.appendChild(el);

      return popupRoot;
    },
    onEachFeatureFunction(tunnel) {
      return (feature, layer) => {
        const popup = this.renderPopup(tunnel);
        layer.bindTooltip('<div style="font-weight:bold;">'+ tunnel.name + '</div>', { permanent: false, sticky: true });
        layer.bindPopup(
          popup,
        { permanent: false, sticky: true });
      };
    },

    options(tunnel) {
      return {
        onEachFeature: this.onEachFeatureFunction.call(this, tunnel)
      };
    },
  },
};

</script>

<style lang="scss">
  $fontSize: 14px;

  .leaflet-popup-content{
    #leafroot-id{
      position: relative;

      .popup-img{
        height: 150px;
        width: 300px;
      }

      .popup-text{
        font-size: $fontSize;
        &.length{
          margin-bottom: 20px;
        }
      }

      .notice-btn{
        width: 155px;
      }
    }
  }

  .leaflet-draw-draw-OK_ICON{
    background-image: url("/static/tunnels/images/ok-btn.png") !important;
    background-size: 25px auto !important;
  }

  .leaflet-draw-draw-NOK_ICON{
    background-image: url("/static/tunnels/images/nok-btn.png") !important;
    background-size: 25px auto !important;

  }

</style>
```

**Comment by DonNicoJs** [comment]
Also I think a specific plugin was released for draw! closing here

**Comment by tamirgilany** [comment]
> Also I think a specific plugin was released for draw! closing here

Do you have a link for that plugin? Couldn't find any...
Thanks

**Comment by tamirgilany** [comment]
> @jlpereira , You can use hack or kind of.
> 
> 1. npm i leaflet-draw -S (install draw library to your project).
> 2. Then code similar to this:
> 
> ```
> import LDraw from 'leaflet-draw';
> 
> // your code here
> 
> mounted() {
>       this.$nextTick(() => {
>       const map = this.$refs.map.mapObject;
>       const drawControl = new window.L.Control.Draw({
>         position: 'topright',
>         draw: {
>           polyline: {
>             allowIntersection: false,
>             showArea: true
>           },
>           polygon: false,
>           rectangle: false,
>           circle: false,
>           marker: false
>         }
>       });
> 
>       map.addControl(drawControl);
> 
>       const editableLayers = new window.L.FeatureGroup().addTo(map);
>       map.on(window.L.Draw.Event.CREATED, (e) => {
>         // const type = e.layerType;
>         const layer = e.layer;
> 
>         // Do whatever else you need to. (save to db, add to map etc)
>         editableLayers.addLayer(layer);
>       });
>     });
> ```
> So, 'vue2-leaflet' is only wrapper, but original Leaflet still accessible through window.L.

Any reason why the drawControl which are in false such as polygon, rectangle and so on are still visible despite having the value false?

Thanks!

**Comment by haoxl3** [comment]
@chistov 
Would it be convenient for you to share your project ? I want to know your code about 
```
computed: {
        geojson() {
            return this.$store.state.TunnelsCategories.tunnels;
        }
    }
```

thant you very much!

**Comment by chistov** [comment]
@haoxl3 
Hi there! That variable is an array and it matches geojson format. For example:

tunnels[0] is equal to:
 {
...// some specific data
geometry:{
   type: 'MultiLineString',
   coordinates: [
   // some data here
  ],
  ... // and so on
  }
}

**Comment by gabrielsmelo** [comment]
Hi guys.

What if I need to remove the toolbar after adding something?

**Comment by kareniukas** [comment]
There is plugin for drawing

https://github.com/hubertokf/vue2-leaflet-draw
