### ISSUE TITLE
does this plugin provide route mapping feature?

### ISSUE THREAD

**Issue by novaknole** [KoRiGaN/Vue2Leaflet#332]
Basically, I'm just asking a question. so That's why I deleted the schema skeleton of how a question should be added depending on your rules. Sorry for that. 

I need the following feature. When user types initial and final address, I need to draw a line which connects these two points on the map via the red line for example. Does this plugin provide this feature or is there anything vue-related plugin of leaflet that provides that?

**Comment by lordfuoco** [comment]
@novaknole if you would be using only vue2-leaflet you should use reverse geocoding to get the lat and lon of the two points. then you could have a polyline made with those.

Maybe take a look at this: http://www.liedman.net/leaflet-routing-machine/

There is still no vue2-leaflet-routing-machine wrapper tho. Feel free to create one!
