### ISSUE TITLE
camelCase event name in LMarker

### ISSUE THREAD

**Issue by nrmncr** [KoRiGaN/Vue2Leaflet#334]
Hi!

LMarker component emit event with name 'update:latLng', but according to vue2 documentation ([vue2 event names](https://vuejs.org/v2/guide/components-custom-events.html#Event-Names)) names must be in kebab-case ('update:lat-lng')

vue2-leaflet v1.2.3

**Comment by lordfuoco** [comment]
@nrmncr thank you nice catch! I will add it to the work to be done :)
