### ISSUE TITLE
layers definition from webservice (1/2 offtopic)

### ISSUE THREAD

**Issue by josejachuf** [KoRiGaN/Vue2Leaflet#335]
Sorry for the offtopic, but since there is no discussion list I consult it here

I have some base layers and I am trying to load some overlays layers with the parameters read from a webservice (localidades) with axios. I make the call from the created () method.

The problem is that the call is asynchronous and it happens that when the layers are loaded in l-map component, the call has not ended yet and my variable this.localidad is still null.

How can I solve it?

Jose

**Comment by bezany** [comment]
@josejachuf Hello! May be simple add check `v-if='localidad'` in you overlays layers template.

**Comment by josejachuf** [comment]
Hi.@bezany Thanks for the reply.
The error was commenting on a computed property which returns the array of layers
