### ISSUE TITLE
use of arrays to specify center/lat-lng

### ISSUE THREAD

**Issue by brianmay** [KoRiGaN/Vue2Leaflet#34]
From the example:

```html
<div id="app" style="height: 100%">
  <v-map :zoom=13 :center="[47.413220, -1.219482]">
    <v-tilelayer url="http://{s}.tile.osm.org/{z}/{x}/{y}.png"></v-tilelayer>
    <v-marker :lat-lng="[47.413220, -1.219482]"></v-marker>
  </v-map>
</div>
```

The problem with using arrays like this for 'center' and 'lat-lng' is that Vue gets a new array every time the map gets rendered. This in turn means the map will get re-centered every time the map is refreshed (i.e. anything in the map changes, e.g. a marker moves). Even if the values have not changed they will be sent to the component as though they have changed. Presumably the same thing happens for the markers too (not tested).

A work around is to create the array as a data property:

```python
data: function() {
        return {
            map_centre: [-38, 145],
            map_zoom: 13,
        }
        ...
}
```

And use this in the map:

```html
<v-map ref="map" :zoom="map_zoom" :center="map_centre" style="height: 500px;">
```

However this does not work if rendering markers from a list:

```html
<v-marker
            ref="marker"
            v-for="item in inventory"
            v-if="item.c8y_Position && item.c8y_Position.lat && item.c8y_Position.lng"
            :key="item.id"
            :lat-lng="[item.c8y_Position.lat, item.c8y_Position.lng]">
</v-marker>
```

Is it possible that we could pass lat and lng and separate properties and not use the array?

**Comment by KoRiGaN** [comment]
Hi @brianmay,

Thanks for describing this issue very clearly.

I would like to keep the Vue2Leaflet API as close as possible to leaflet API, so I don't want to expose lat and lng properties separately, if possible. 

I think it is possible to fix this issue by making sure object reference and lat lng value have changed before updating properties.

I'm going to investigate around this.

Mickaël

**Comment by KoRiGaN** [comment]
The issue about map center should be fixed in v0.0.49.

@brianmay, I am not sure what you mean in the last part : 

> However this does not work if rendering markers from a list:

**Comment by brianmay** [comment]
> I think it is possible to fix this issue by making sure object reference and lat lng value have changed before updating properties.

I previously considered this option however, I suspect this will still mean the component is still re-rendered (by vue) when nothing changes - which is kind of wasteful.

**Comment by KoRiGaN** [comment]
Hi @brianmay,

Not sure what can cause many re-rendering by vue.

I'm closing this issue as it have not been updated for a while. If you have an running example showing the impact of too many re-rendering please share it and reopen this issue. I will try to find a solution around this.

Cheers,

Mickaël
