### ISSUE TITLE
Documentation playgrounds broken

### ISSUE THREAD

**Issue by dpiquet** [KoRiGaN/Vue2Leaflet#341]
Hi, it seems the documentation playgrounds are broken: https://korigan.github.io/Vue2Leaflet/#/components/l-circle/

It see that a script is not loading (404 error)

**Comment by DonNicoJs** [comment]
@dpiquet Hi thank you! I will check it

**Comment by DonNicoJs** [comment]
@dpiquet Thank you, fixed now. It may need an hard refresh due to github pages cache

**Comment by nuhamind2** [comment]
Seem grid layer not working in the example
[https://korigan.github.io/Vue2Leaflet/#/components/l-grid-layer/](https://korigan.github.io/Vue2Leaflet/#/components/l-grid-layer/)

**Comment by DonNicoJs** [comment]
@nuhamind2 yes you are right. that component is on the beta version of 1.2.3. Apologies for all this problems, but I will release 2.0 this week and we can finally have a stable doc linked to a stable code.

Apologies again

**Comment by DonNicoJs** [comment]
Closing since 2.0 is released
