### ISSUE TITLE
Unit test

### ISSUE THREAD

**Issue by DonNicoJs** [KoRiGaN/Vue2Leaflet#345]
Since @bezany already started I am opening an issue for unit test.
We are highly lacking them right now and we definitively need more. 
After 2.0 is released I am not going to work on any new feature (except bug fixing ) until we have a decent unit test coverage.

If anyone want's to help I would love any PR here.

**Comment by mikeu** [comment]
What is the current status on this? I'd be up for trying to expand the coverage, but don't want to duplicate work. I was thinking of starting with the functions in the utils file.

**Comment by DonNicoJs** [comment]
@mikeu you can start working on it! Nobody stood up for it. Please open immediately a pr with WIP in the title! And thank you!

**Comment by pumano** [comment]
test suite has good coverage or need help?

**Comment by DonNicoJs** [comment]
@pumano need help :) especially because I plan a refactor for vue3 and without tests I can't :)
