### ISSUE TITLE
Module '"vue2-leaflet"' has no exported member 'LMap'

### ISSUE THREAD

**Issue by HendrikCammann** [KoRiGaN/Vue2Leaflet#346]
Hello :-)

I am using Leaflet in Combination with Vue|Typescript.
But I have the problem, that when i try to import the Map, TileLayer etc. from vue2-leaflet my IDE tells me: Module '"vue2-leaflet"' has no exported member 'LMap'.

It still compiles tough and everything works fine, but when I run 'npm build' the build fails because of this. Does anyone know how to fix it?

`import { LMap, LTileLayer, LMarker, LPopup, LTooltip } from 'vue2-leaflet';` that how my import lookslike.

I am still new to this, so I am sorry if this question has been answered in anyway. It already did look through the other issues but it sadly did not help me.

the start of my ts file:

```
import Vue from 'vue';
    import { Component, Prop } from 'vue-property-decorator';
    import * as L from 'leaflet';
    import { LMap, LTileLayer, LMarker, LPopup, LTooltip } from 'vue2-leaflet';
    import LMarkerCluster from 'vue2-leaflet-markercluster';
    import { CompanyModel } from '../../models/Company.model';

    import { Getter, Action, namespace } from 'vuex-class';
    import { CompanyActionTypes } from '@/store/modules/company/actions';
    import { EventModel } from '../../models/Event.model';
    import { EventActionTypes } from '../../store/modules/event/actions';
    const companyModule = namespace('company');
    const eventModule = namespace('event');

    @Component({
        components: {
            LMap,
            LTileLayer,
            LMarker,
            LPopup,
            LTooltip,
            LMarkerCluster,
        },
    })
    export default class LeafletComponent extends Vue {
....
    }
```

### Versions
- Leaflet: ^1.4.0
- Vue: ^2.5.21
- Vue2Leaflet: ^1.2.3

**Comment by DonNicoJs** [comment]
I am not a TS expert for that you need @HIMISOCOOL but I think you manually need to install some types. Could you try the new beta version ? No worries about double asking

**Comment by HIMISOCOOL** [comment]
yeah, I am still not 100% why it happens, I don't have to install anything extra with ^1.2.3 and typescript but others have reported success when they install @types/leaflet. My packagelock.json has it at 1.2.14 so probably install ~1.2.14.
I would be interested to see if the new beta version is working for you too though :P

**Comment by HendrikCammann** [comment]
thanks for the fast answers :)

I tried adding @types/leaflet but it seems that this is not fixing my problem. This is how my package.json looks like:

```
"dependencies": {
        "@types/leaflet": "^1.2.14",
        "axios": "^0.18.0",
        "contentful": "^7.3.0",
        "contentful-management": "^5.4.0",
        "contentful-vue": "^1.0.5",
        "leaflet": "^1.4.0",
        "register-service-worker": "^1.5.2",
        "vee-validate": "^2.1.7",
        "vue": "^2.5.21",
        "vue-axios": "^2.1.4",
        "vue-class-component": "^6.0.0",
        "vue-property-decorator": "^7.0.0",
        "vue-router": "^3.0.1",
        "vue2-leaflet": "^1.2.3",
        "vue2-leaflet-markercluster": "^2.1.2",
        "vuelidate": "^0.7.4",
        "vuex": "^3.0.1",
        "vuex-class": "0.3.1",
        "vuex-router-sync": "^5.0.0"
    },
    "devDependencies": {
        "@types/chai": "^4.1.0",
        "@types/mocha": "^5.2.4",
        "@vue/cli-plugin-babel": "^3.3.0",
        "@vue/cli-plugin-pwa": "^3.3.0",
        "@vue/cli-plugin-typescript": "^3.3.0",
        "@vue/cli-plugin-unit-mocha": "^3.3.0",
        "@vue/cli-service": "^3.3.0",
        "@vue/test-utils": "^1.0.0-beta.20",
        "chai": "^4.1.2",
        "node-sass": "^4.9.0",
        "sass-loader": "^7.0.1",
        "typescript": "^3.0.0",
        "vue-template-compiler": "^2.5.21"
    }
```

What is this beta version you are talking about? :)

**Comment by HIMISOCOOL** [comment]
Not that I think it makes a difference to the packagelock.json but types
generally go in the dev dependencies.
https://github.com/KoRiGaN/Vue2Leaflet/releases/tag/v2.0.0 is the newer
version.
Seems to be up on npm now.

**Comment by HendrikCammann** [comment]
@HIMISOCOOL 

fixed it :) I forgot to add the @types/leaflet to my tsconfig.json.

```
"types": [
            "webpack-env",
            "mocha",
            "chai",
            "leaflet"
        ],
```

After adding, everything worked fine.

**Comment by HIMISOCOOL** [comment]
Oh sweet, maybe we should add that as a verification step in the Readme 🤔

**Comment by DonNicoJs** [comment]
@HIMISOCOOL Is this something that happens in all the TS projects or only with vue2-leaflet ? I mean manually adding the type

**Comment by HIMISOCOOL** [comment]
I dont think I've ever had to do that.
this is my current tsconfig

```{
    "compilerOptions": {
        "target": "esnext",
        "module": "esnext",
        "strict": true,
        "jsx": "preserve",
        "importHelpers": true,
        "moduleResolution": "node",
        "experimentalDecorators": true,
        "esModuleInterop": true,
        "allowSyntheticDefaultImports": true,
        "sourceMap": true,
        "baseUrl": ".",
        "types": [
            "node",
            "jest"
        ],
        "paths": {
            "@/*": [
                "src/*"
            ]
        },
        "lib": [
            "esnext",
            "dom",
            "dom.iterable",
            "scripthost"
        ]
    },
    "include": [
        "src/**/*.ts",
        "src/**/*.tsx",
        "src/**/*.vue",
        "tests/**/*.ts",
        "tests/**/*.tsx"
    ],
    "exclude": [
        "node_modules"
    ]
}```

and theres nothing specific to leafet.
But I guess it doesnt hurt to add 
"If you have trouble compiling with typescript, ensure @types/leaflet is installed, if there is still an issue after that try including it in the types section of your tsconfig like so:
"types": [
    *your other types*,
    "leaflet"
]

**Comment by DonNicoJs** [comment]
@HIMISOCOOL We actually completely lack a doc section for typescript, what would make sense to write there?
