### ISSUE TITLE
Update releases in github to match NPM

### ISSUE THREAD

**Issue by schlunsen** [KoRiGaN/Vue2Leaflet#348]
Hi, thanks for a great project.

I can see that NPM package for vue2-leaflet  has been updated with a new release of this project, but can't seem to find it here on github?

https://david-dm.org/schlunsen/nuxt-leaflet

**Comment by DonNicoJs** [comment]
@schlunsen you are right I still not have done a github release matching npm, in the pipeline, I am adjusting some travis stuff first

**Comment by DonNicoJs** [comment]
@schlunsen Releases are now on pair And I will endeavour to keep them up
