### ISSUE TITLE
Vue2Leaflet@2.0.0 can't find leaflet from CDN

### ISSUE THREAD

**Issue by javiertury** [KoRiGaN/Vue2Leaflet#349]
Vue2Leaflet@2.0.0 requires leaflet to be imported separatedly. After loading leaflet@1.4.0 from a CDN, leaflet is exported as `window.L`, while Vue2Leaflet expects to find leaflet on `global.leaflet`.

I think Vue2-leaflet should search on `global.L`. Is thre any reason (perhaps old leaflet versions) to search in global.leaflet as well?

```
<link rel="stylesheet" href="//unpkg.com/leaflet@1.4.0/dist/leaflet.css">
<script src="//unpkg.com/leaflet@1.4.0/dist/leaflet.js"></script>
<!-- Only window.L is created -->
<script src="//unpkg.com/vue2-leaflet@2.0.0/dist/vue2-leaflet.min.js"></script>
<!-- vue2-leaflet.min.js tries to find leaflet on global.leaflet but finds nothing -->
```

**Comment by DonNicoJs** [comment]
@javiertury is actually a mistake, this is an easy fix, rolling out a patch version right now

**Comment by DonNicoJs** [comment]
@javiertury fixed on npm and fixed the docs! 
Also corrected on how to import from CDN since now we specify the UNPKG script in the package.json

Thanks!
