### ISSUE TITLE
Sub-component inside v-popup and v-tooltip

### ISSUE THREAD

**Issue by tortuetorche** [KoRiGaN/Vue2Leaflet#35]
Hi @KoRiGaN,

Is it possible to use sub-component inside the content of v-popup and v-tooltip, instead of pure HTML string inside the `content` property?

So we can do this kind of stuff:
```html
<div id="app">
  <v-map :zoom="zoom" :center="center">
    <v-tilelayer :url="url" :attribution="attribution"></v-tilelayer>
    <v-marker :lat-lng="marker">
      <v-popup>
        <button @click='counter += 1'>{{ some_content }}</button>
      </v-popup>
    </v-marker>
  </v-map>
</div>
```

Cheers,
Tortue Torche

**Comment by mtdavidson** [comment]
@tortuetorche I was trying to do the same thing but couldn't quite figure it out. I ended up creating a new component with properties. As you need to build up a string to pass to `bindPopup`. It might not be the best method but it did work. 

```
<template>
</template>

<script>

    import eventsBinder from '../utils/eventsBinder.js';
    import propsBinder from '../utils/propsBinder.js';

    const events = [
        'add',
        'remove',
        'popupopen',
        'popupclose',
        'tooltipopen',
        'tooltipclose'
    ];

    const props = {
        content: {
            default: '',
        },
        thumbnail: {
            default: '',
        },
        rating: {
            default: 0,
        },
        link: {
            default: ''
        }
    };

    export default {
        props: props,
        computed: {
            // a computed getter
            popupContent: function () {
                // There is probably a better way to do this
                return `
                    <div class="media">
                      <div class="media-left">
                        <img src="${this.thumbnail}" alt="" height="72" width="72">
                      </div>
                      <div class="media-body">
                        <a href="${this.link}"><h6 class="media-heading">${this.content}</h6></a>
                        Rating: <b>${this.rating}</b>
                      </div>
                    </div>
                `;
            }
        },
        mounted() {
            this.mapObject = L.popup();
            eventsBinder(this, this.mapObject, events);
            propsBinder(this, this.mapObject, props);
            if (this.$parent._isMounted) {
                this.deferredMountedTo(this.$parent.mapObject);
            }
        },
        beforeDestroy() {
            if (this.parent.getPopup()) {
                this.parent.unbindPopup();
            }
        },
        methods: {
            deferredMountedTo(parent) {
                this.parent = parent;
                parent.bindPopup(this.popupContent);
            },
            setContent(newVal, oldVal) {
                if (newVal) {
                    this.parent.bindPopup(this.popupContent);
                } else {
                    if (this.parent.getPopup()) {
                        this.parent.unbindPopup();
                    }
                }
            },
        }
    };
</script>
```

**Comment by KoRiGaN** [comment]
Hi @tortuetorche,

Not sure how to implement that properly with Vue.
If someone can give a little help on that it would be welcome. :-)

**Comment by jmaister** [comment]
Hi,

I think that it could work using <slot> in the v-popup template https://vuejs.org/v2/guide/components.html#Single-Slot

Then, using the method popup.setContent(<String|HTMLElement|Function> htmlContent), the content can be all the slot content.

**Comment by fdenzer** [comment]
I don't get it, how am i supposed to use
e.g. <router-link> inside a popup?
I just (sudo!) npm linked this package to view the examples, but none of them
were using components inside a pop-up.

So far, `:content="[...]"` renders no sub-components for me.

**Comment by KoRiGaN** [comment]
Hi @fdenzer,
Give a look at MarkerPopupExample and MarkerPopup in the example folder provided in the repo.
Let me know if it helps.

Micka

**Comment by fdenzer** [comment]
Hi @KoRiGaN ,
a CS student and me took a look at the example,
yet we did not get router-link to render as a sub-component in our custom component like this:

```javascript
<template>
  <div>
    <h2>Popup</h2>
    <div><router-link to="/">back home</router-link></div>

  </div>
</template>
```

**Comment by core01** [comment]
Me also need to work router-link inside popup. @fdenzer do you find the solution?
If anyone has found the solution and can share, I will be grateful.
Thanks.

**Comment by fdenzer** [comment]
`<div><router-link to=" '/' ">` without a colon looked very fishy.

Note that, in order to *not* reference a property called `/`,
the syntax needs to contain two more single quotation marks.
Because`to="{/}" would behave like `:to="/"`, which makes no sense.

**Comment by punkmap** [comment]
I'm trying to fire a click event from a link created dynamically in a popup. is this possible? 

The code I'm working with is:
<v-marker v-for="contact in contacts" :lat-lng="contact.address.position" :icon="defaultIcon">
      <v-popup :content="contact.name">
        
      </v-popup>
    </v-marker>

contacts: [
    {
      name: '<router-link tag="li" :to="/foo"><a>/foo</a></router-link>',
      address: {
        complete_address: '...',
        position: [35.792394301494056,-78.76595011070837]
      },
      phone_number: '+49.....',
      email: 'me@here.com'
    }]

How can this be done? 

Thanks, Tyler
