### ISSUE TITLE
Possible incorrect using for .. in

### ISSUE THREAD

**Issue by nailfor** [KoRiGaN/Vue2Leaflet#354]
### Versions
- Vue2Leaflet: v2.0.2

Hi. 

I am writing a plugin for vue2leaflet and found that the registerLayerControl method may incorrectly use for..in
in cycle
```
      for (var layer in this.layersToAdd) {
        this.layerControl.addLayer (layer);
      }
```
the layer variable will return 0, not layer, because 
```
this.layersToAdd.push(layer) 
```
of the addLayer method creates a non-associative array

**Comment by DonNicoJs** [comment]
@nailfor You are 100% right it should be `for ..of ` would you be interested in making a PR ?

**Comment by nailfor** [comment]
done.

if interesting, im done vue2laeaflet-draw component to vue2leaflet, but i'm don't know how use rollup bundler for distribution

**Comment by DonNicoJs** [comment]
@nailfor you can check how I am using it here! Or you can add me to the repo so I can help you there
