### ISSUE TITLE
Adding Vue2Leaflet child components to <l-map> from nuxt child

### ISSUE THREAD

**Issue by wadclapp** [KoRiGaN/Vue2Leaflet#357]
### Description
Is it possible to have a parent container with `<l-map>`, then include some Vue2Leaflet components into it from `<nuxt-child />`?

Parent.vue
```html
<template>
  <div>
    <l-map>
      <nuxt-child />
    </l-map>
  </div>
</template>
```

Parent/Child.vue
```html
<template>
  <l-layer-group>
    <l-circle-marker
      :latLng="[51, -3]"
    ></l-circle-marker>
  </l-layer-group>
</template>
```

I need to load different content depending on the current route, and ideally have them in separate files rather than one big one.

But it's not working for me, and getting the error below. Is this possible? Or what am I doing wrong?

#### Expected Results
circle marker is added to map

#### Actual Results
circle marker is not added to map, and error is thrown
TypeError: this.parentContainer.addLayer is not a function

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions
- Leaflet: v1.3.4
- Vue: v2.6.7
- Vue2Leaflet: v1.2.3

**Comment by DonNicoJs** [comment]
@wadclapp can you provide a codesandbox or codepen with a minimal example ? I think I can help you

**Comment by wadclapp** [comment]
Hi @DonNicoJs , thanks. I've created a codesandbox here - https://codesandbox.io/s/m7x98rppwp?fontsize=14

All files other than `layouts/map.vue` and `pages/map.vue` can be ignored. I think I managed to recreate it.

It's just not hooking into the map object in the parent file. Works fine when using a normal component, just not when using `<nuxt />`/`<nuxt-child />`.

**Comment by DonNicoJs** [comment]
@wadclapp if you move the`<Nuxt>` element inside the `<l-map>` is going to work, otherwise the parent / child relationship is not kept:

https://codesandbox.io/s/743o49qw8j?fontsize=14

**Comment by wadclapp** [comment]
Oops, that wasn't the issue in my project. I think having a computed property called 'mapObject' broke things (as I'm storing map object in store). Thanks for your help though, and great work on vue2leaflet!

Leaflet doesn't support SSR does it?

**Comment by DonNicoJs** [comment]
@wadclapp sadly leaflet and ssr are not friends :( and probably never be
