### ISSUE TITLE
IconDefault errors using vue-loader

### ISSUE THREAD

**Issue by EyMaddis** [KoRiGaN/Vue2Leaflet#36]
Hi,
thanks for the great component! I have a problem setting the image when using vue-loader.

IconDefault does not set the image path at all, 
```html
    <leaflet-icon-default path="static/media/map"></leaflet-icon-default>`
```
Renders to

```html
<img src="http://localhost:4000/static/media/marker-icon.2273e3d8.png&quot;)marker-icon.png" class="leaflet-marker-icon ...">
```

Notice the invalid link.

**Comment by novoselrok** [comment]
I think this is a webpack issue. I solved it by using this comment: https://github.com/PaulLeCam/react-leaflet/issues/255#issuecomment-261904061

**Comment by KoRiGaN** [comment]
Hi @EyMaddis,
Seems to be the same issue as issue #28 

It's a problem between Webpack and Leaflet so closing this issue and keeping only #28 until a clean solution is found.

Mickaël
