### ISSUE TITLE
How to add ContextMenu in Vue2 Leaflet？

### ISSUE THREAD

**Issue by shcolo** [KoRiGaN/Vue2Leaflet#360]
How to add ContextMenu in Vue2 Leaflet？
Like https://github.com/aratcliffe/Leaflet.contextmenu

**Comment by DonNicoJs** [comment]
@shcolo you can either use it 'manually' with the mapObject API exposed through refs or by the ready event or create your own plugin! 
Labelling as plugin-request and closing

**Comment by julienlz** [comment]
Hello,

i am using contextmenu directly on map,

 this.$nextTick(() => {
        this.$refs.myMap.mapObject.bindPopup(`HELLO`)
      })

its not working. Have you get an idea ?
