### ISSUE TITLE
Coordinate mismatch with google maps

### ISSUE THREAD

**Issue by maratumba** [KoRiGaN/Vue2Leaflet#364]
### Description
Coordinates from google maps don't match coordinates on ESRI World Imagery tiles.

#### Live Demo

http://jsfiddle.net/gulyamani/ocjw580q/

#### Steps to Reproduce
Go on [google maps](https://www.google.com/maps/place/40%C2%B050'11.6%22N+29%C2%B030'51.5%22E/@40.836566,29.5135417,222m/data=!3m2!1e3!4b1!4m5!3m4!1s0x0:0x0!8m2!3d40.836566!4d29.514314) and search for these coordinates: 40.836566, 29.514314

Then create a map and place a marker at those coordinates. (See the fiddle)

#### Expected Results
Markers should be at the same spot.

#### Actual Results
Markers have ~20 meters between them.

### Browsers Affected
- [x] Chrome
- [x] Firefox
- [x] Edge
- [x] Safari 9
- [x] Safari 8
- [x] IE 11

### Versions
- Leaflet: v1.0.3
- Vue: v2.5.16
- Vue2Leaflet: v1.0.1

**Comment by DonNicoJs** [comment]
@maratumba do you think this is a Vue2Leaflet issue or a leaflet issue? 
can you reproduce the issue with leaflet alone?

**Comment by maratumba** [comment]
I got [this reply](https://gis.stackexchange.com/questions/317050/coordinate-mismatch-between-google-maps-and-leaflet-using-esri-world-imagery/317091#317091) on gis stack exchange, which says it is an issue with the misaligned ESRI imagery. 

The problem appears to be localized, you can compare different imagery for the problematic location [here](https://next.plnkr.co/edit/UBZH033vlMbMXmpMYTqS?p=preview&utm_source=legacy&utm_medium=worker&utm_campaign=next&preview).

**Comment by DonNicoJs** [comment]
@maratumba thank you for the reply, so is not an issue here :) thank you nonetheless! Closing
