### ISSUE TITLE
TileLayer doesn't update

### ISSUE THREAD

**Issue by iamvdo** [KoRiGaN/Vue2Leaflet#37]
Hello,
Find an issue where modifying `url` does not update component. See here: https://jsfiddle.net/k04zpLx9/40/

I'm currently learning Vue, so I'm not an expert. It seems that, as there is no DOM elements, component is not updated. Adding something like this will work:

```vue
<template>
  <span :url="url"></span>
</template>

<script>
...
updated() {
    this.$tileLayer.setUrl(this.url);
}
...
</script>
``` 

Is it OK? Is there another solution?

**Comment by KoRiGaN** [comment]
Hi @iamvdo, 
Thanks for the JSFiddle example.

I think it is a bug on tileLayer component where url (and other) property is not bound to leaflet method.

I will try to have a look at it as soon as possible.

Mickaël
