### ISSUE TITLE
Accessing component methods without refs

### ISSUE THREAD

**Issue by wishinghand** [KoRiGaN/Vue2Leaflet#370]
When using Vue2Leaflet components in a `v-for`, I often have need to modify that specific one after an event, like dragging a marker. When I look for ways to access a specific Vue2Leaflet component, I usually see recommendations to set a ref on it, then calling `this.$refs.refName.mapObject.componentMethod`. Is there a way to pass the instance of a component through an event so that component methods can then be called on them?

**Comment by DonNicoJs** [comment]
@whisinghand I am thinking to add a 'ready' event to all the components that emit the mapObject back this would solve lots of problems actually

**Comment by wishinghand** [comment]
How might that look in practice?

**Comment by DonNicoJs** [comment]
Something like this: 

```
<template>
<l-map ...>
<l-tile-layer ... />
<l-marker v-for="..." @ready="markerReady" />
</l-map>
</template>

<script>
export default {
methods: {
markerReady(mapObject) {
mapObject.openTooltip();
}
}
}
```

Ugly formatting aside this should solve your issue I think and also provide a reliable event where mapObject is always present

**Comment by DonNicoJs** [comment]
@wishinghand  2.1.3 is out with ready event on all the component

**Comment by wishinghand** [comment]
Is there a way to call `@ready` again? My predicament is like this:

```
<span v-for="gate in gates">
  <l-marker
    @moveend="updateGateCoords(gate, $event)"
    :key="gate.id"
    :lat-lng="gate.coordinates"
    :draggable="true"
  >
</span>
```

When I drag the `l-marker`, I do some checks the `@moveend` event `updateGateCoords`. If the gate is moved into an invalid area, I'd like to call `setLatLng` on it with the previous coordinates from `$event` to move it back to where it started. This is where I'd need the `mapObject` for that specific `l-marker`, but I'm unsure of how to access it.

**Comment by DonNicoJs** [comment]
@wishinghand my suggestion is: wrap the l-marker in another component, that component should be a proxy that pass down any props and event but listen to the marker @ready and store the map object in an internal value say `localMapObject` then everytime u ran updateGateCoords you can pass up the stored localmapobject (sorry I am on mobile)

**Comment by wishinghand** [comment]
I've setup a wrapper component like this for the template part:

```
<template>
    <l-marker
            @moveend="emitNewCoords($event)"
            @ready="setMapObject"
            :icon="icon"
            :lat-lng="latLng"
            :draggable="true"
      >
    <slot></slot>
  </l-marker>
</template>
```

and the `@ready` event doesn't seem to trigger. I have it just saving the mapObject when it happens:

```
setMapObject(mapObject) {
  this.localMapObject = mapObject
}
```

**Comment by DonNicoJs** [comment]
@wishinghand I received an email with an update from your issue but I can't find the message here. Did you delete it? is it solved for you now?

**Comment by wishinghand** [comment]
The issue is solved now. The comment I deleted was about not being able to access the `@ready` event but for some reason my branch reset my vue2leaflet version. After an `npm install` I was able to get this workaround to deliver the expected results.
