### ISSUE TITLE
Can I set a L.point() size for LTileLayer?

### ISSUE THREAD

**Issue by EnkeChan** [KoRiGaN/Vue2Leaflet#371]
Thanks for make this project!  It help me a lot.  

And there is a powerful prop for tileLayer I can not use easily.

I use like this:

l-tile-layer :tileSize="L.point(100,200)"  l-tile-layer   (I can not write<>)

It seems that vue2leaflet does not support L.point size?

P.S: My English is not good, I am a Chinese, I'm  learning English hardly. hah

**Comment by DonNicoJs** [comment]
Hi @EnkeChan thank you for opening an issue.
`tileSize` does not have a corresponding `getTileSize` method, so it's not a direct prop BUT! you can pass it to the `:options` to have it set on the tile-layer creation

**Comment by EnkeChan** [comment]
ok!

**Comment by DonNicoJs** [comment]
@EnkeChan does this work for you ? can we close the issue?

**Comment by EnkeChan** [comment]
yes！ Thank you!
