### ISSUE TITLE
Support for eeGeo

### ISSUE THREAD

**Issue by hubertokf** [KoRiGaN/Vue2Leaflet#373]
First of all, I tryed using stackoverflow with tag Vue2Leaflet, but since I dont have much reputation and to create that tag needs 15000, I could not post it using that tag. 

So.. 

I want to show a 3D object model in a map. I'm using Vue2 with Vue2Leaflet. Actually I found eeGeo that could help me. It works very well with Leaflet lib, but how can i use it with Vue2Leaflet.

**Comment by DonNicoJs** [comment]
@hubertokf two ways 
1) create a plugin :) 
2) directly using it by referencing the map with the mapObject

**Comment by hubertokf** [comment]
Thank you @DonNicoJs !

hehe, I have tried before to include some code on lib, but got no luck with that. I couldnt understand how everything work. But I will give another try. Thanks!

**Comment by DonNicoJs** [comment]
Labelled as plugin request and closing. Feel free to re-open
