### ISSUE TITLE
LWMSTileLayer baseUrl Error

### ISSUE THREAD

**Issue by michaelzhu288** [KoRiGaN/Vue2Leaflet#388]
### Description
Hi,

I got The data property "baseUrl" is already declared as a prop. Use prop default value instead.  when using the WMS component. How to solve this issue?

vue.runtime.esm.js?2b0e:587 [Vue warn]: The data property "baseUrl" is already declared as a prop. Use prop default value instead.

found in

---> <LWMSTileLayer>
       <LMap>
         <MapTest> at src/components/views/map/MapTest.vue
           <AppLayout2> at src/layout/Layout2.vue
             <App> at src/App.vue
               <Root>

Regards

#### Steps to Reproduce
```
<template>
  <l-map ref="myMap" :zoom="zoom" :center="center"
         :markerZoomAnimation="true"
         :fadeAnimation="true"
         :minZoom="9"
         :maxZoom="14"
         >
    <l-wms-tile-layer
      v-for="layer in baseLayers"
      :key="layer.name"
      :base-url="layer.url"
      :layers="layer.layers"
      :visible="layer.visible"
      :name="layer.name"
      :transparent="true"
      format="image/png"
      layer-type="base"
    />
  </l-map>
</template>

<script>
  import {LCircleMarker, LControlLayers, LMap, LMarker, LPopup, LWMSTileLayer,LTileLayer,LControl,LControlAttribution} from "vue2-leaflet";
    export default {
        name: "MapTest",
      components: {
        LMap,
        "l-wms-tile-layer": LWMSTileLayer,
        LControlLayers,
        LMarker,
        LPopup,
        'l-circle-marker': LCircleMarker,
        LTileLayer,
        LControl,
        LControlAttribution
      },
      data(){
          return {
            zoom: 9,
            bounds:null,
            markers: [],
            center: [1.0422703924068677, 10.498809814453127],
            mapHeight:750,
            baseLayers: [
              {
                name: "Suhong",
                visible: true,
                layers: "flex:BU8_Polyline",
                url: 'http://localhost:8080/geoserver/test/wms'
              }
            ]
          }
      }
    }
</script>

<style scoped>

</style>

```

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions
- Leaflet: v1.4.0
- Vue: v3.7.0
- Vue2Leaflet: v2.1.1

**Comment by DonNicoJs** [comment]
Hi! could you create a reproduction in codesandbox / codepen?

**Comment by michaelzhu288** [comment]
Hi DonNicoJs,

There's global variable with the name baseUrl in my template which confilct with the WMS's prop.  It is OK now.

Regards
