### ISSUE TITLE
plugin css usage issue

### ISSUE THREAD

**Issue by SiddiquiImran** [KoRiGaN/Vue2Leaflet#39]
Hi,

have used a plugin for leaflet integration
https://www.npmjs.com/package/vue2-leaflet

but when we try to import css it's not showing image files as it creating wrong paths even if it converts it into inline images

so is there any option to skip plugin files from webpack merge or any other options to handle it.

![image](https://cloud.githubusercontent.com/assets/20870175/25985884/9eb0479e-370a-11e7-9563-8476f6bb71ad.png)

**Comment by ais-one** [comment]
I think you have 2 problems, not 1.

1) For the images in the CSS 

I got the answer from react-leaflet, it had exactly the same problem...

[https://github.com/PaulLeCam/react-leaflet/issues/255](https://github.com/PaulLeCam/react-leaflet/issues/255)

```
import L from 'leaflet'
delete L.Icon.Default.prototype._getIconUrl

L.Icon.Default.mergeOptions({
  iconRetinaUrl: require('leaflet/dist/images/marker-icon-2x.png'),
  iconUrl: require('leaflet/dist/images/marker-icon.png'),
  shadowUrl: require('leaflet/dist/images/marker-shadow.png')
})
```

2) For you map, I think you need to specify a height.

**Comment by SiddiquiImran** [comment]
@ais-one thanks for the help

**Comment by KoRiGaN** [comment]
Thanks @ais-one ! 

Closing this issue as @ais-one comment seems to explain everything.
