### ISSUE TITLE
Preffix  false

### ISSUE THREAD

**Issue by ricardopolo** [KoRiGaN/Vue2Leaflet#390]
In `          <l-control-attribution
            position="bottomright"
            :prefix="false "
          />`
you can  pass `prefix` as false to remove the prefix. It works!

However, it is giving an exception
![image](https://user-images.githubusercontent.com/1263856/57412841-cb94ef00-71b7-11e9-9759-671d78c3ce57.png)

**Comment by DonNicoJs** [comment]
@ricardopolo Thanks for the issue, we just need to fix the prop types here!

**Comment by ricardopolo** [comment]
Hello, when are you planning to release a new version in npm?
(that includes this fix :))

**Comment by DonNicoJs** [comment]
@ricardopolo in this week :)

**Comment by ricardopolo** [comment]
Thank you @DonNicoJs 😄

**Comment by DonNicoJs** [comment]
@ricardopolo 2.2.0 is out on npm
