### ISSUE TITLE
The map disappear when i add the leaflet.css file

### ISSUE THREAD

**Issue by Dallel19** [KoRiGaN/Vue2Leaflet#394]
Hello, 
I am trying to reproduce the simple map example. At the beginning i got a bad displaying of the map and when i added the leaflet.css the map disappear. 
before adding the css file: 

![Screenshot_2019-05-17 leaflet-vuejs-example](https://user-images.githubusercontent.com/35085413/57901148-b37a3b00-785b-11e9-87c0-2106f9a45d39.png)
and after i add it: 
![Screenshot_2019-05-17 leaflet-vuejs-example(1)](https://user-images.githubusercontent.com/35085413/57901146-b2e1a480-785b-11e9-9885-bfbcf39834a7.png)

my main.js looks like:
`import Vue from 'vue'`
`import { Icon } from "leaflet";`
`import App from './App.vue'`
`import "leaflet/dist/leaflet.css"`

`delete Icon.Default.prototype._getIconUrl;
`
`Icon.Default.mergeOptions({
`
`  iconRetinaUrl: require("leaflet/dist/images/marker-icon-2x.png"),
`
`  iconUrl: require("leaflet/dist/images/marker-icon.png"),
``  shadowUrl: require("leaflet/dist/images/marker-shadow.png")
``});
`

`Vue.config.productionTip = false
`
`new Vue({
`  
`render: h => h(App)
`
`}).$mount('#app')
`
Thanks,

**Comment by DonNicoJs** [comment]
@Dallel19 hi! You need to set a fixed height to the map!

**Comment by Dallel19** [comment]
It's working! 
Thank you,
