### ISSUE TITLE
I have a problem 

### ISSUE THREAD

**Issue by entrehuihui** [KoRiGaN/Vue2Leaflet#400]
I set multiple markers on the map, like this  
     key =”'mark'+ i“中添加”LMarker v-for =“（v，i）：lat-lng =”v“> </ LMarker
But after my value is updated, the coordinates will not be updated, but it will disappear.
My coordinate values are like this  [[22.593262, 113.925971],[22.593262, 113.945971]] at the beginning.
Then update these values likes：　 [[23.593262, 113.925971],[23.593262, 113.945971],[23.593262, 113.945971]]

The middle example is blocked by the system, I will add
"LMarker v-for="(v, i) in marker" :key="'mark'+i" :lat-lng="v"></LMarker"
I omitted the beginning "<" and the end of the ">" my way the complete code will be blocked by the system.

**Comment by entrehuihui** [comment]
The middle example is blocked by the system, I will add 
"<LMarker v-for="(v, i) in marker" :key="'mark'+i" :lat-lng="v"></LMarker> "

**Comment by entrehuihui** [comment]
The middle example is blocked by the system, I will add
"LMarker v-for="(v, i) in marker" :key="'mark'+i" :lat-lng="v"></LMarker"
I omitted the beginning "<" and the end of the ">" my way the complete code will be blocked by the system.

**Comment by entrehuihui** [comment]
Thank you very much for your help, I have solved this problem.

**Comment by entrehuihui** [comment]
Thank you very much for your help, I have solved this problem.Is due to a problem triggered by data refresh

**Comment by DonNicoJs** [comment]
@entrehuihui sorry for not being able to help, but I am glad that you managed to solve the issue.
