### ISSUE TITLE
Vue2Leaflet: Error in mounted hook

### ISSUE THREAD

**Issue by mderkach** [KoRiGaN/Vue2Leaflet#402]
Hi. I'm newbie to vue and help me solve problem. What i'm doing wrong?
Error appers, when i try to reproduce quick setup guide for components, and i get similar error to https://github.com/KoRiGaN/Vue2Leaflet/issues/144#issuecomment-465003915

i have checked #281 issue and changed my webpack config to: http://prntscr.com/nx7n26
but get something like that: http://prntscr.com/nx7kl8
Package.json: http://prntscr.com/nx7ncz
Entrypoint: http://prntscr.com/nx7nj3
Component: http://prntscr.com/nx7npw

P.S. sorry for bad english.

**Comment by DonNicoJs** [comment]
@mderkach hi did you install leaflet as a dependency?

**Comment by mderkach** [comment]
@DonNicoJs 
Hello, thanks for reply!
Problem was in wrong intendation of components. l-tile-layer must be in l-map, as i saw it from exmaples of components. In my case no alias is needed. For now, it works fine

I created from early beginnig bundle step-by-step and it works :)

**Comment by DonNicoJs** [comment]
@mderkach glad that is solved and sorry for the poor support, I am badly overloaded lately :)
