### ISSUE TITLE
Error in LMarker setLatLng

### ISSUE THREAD

**Issue by nailfor** [KoRiGaN/Vue2Leaflet#403]
[Vue warn]: Error in callback for watcher "latLng": "Error: Invalid LatLng object: (undefined, undefined)"

<l-marker :lat-lng='[0,0]'><l-marker>

code in min.js:
```
                    setLatLng: function(t) {
                        if (null != t && this.mapObject) {
                            var e = this.mapObject.getLatLng(),
                                n = {
                                    lat: t[0] || t.lat,
                                    lng: t[1] || t.lng
                                };
                            n.lat === e.lat && n.lng === e.lng || this.mapObject.setLatLng(n)
                        }
                    },
```
I'm set newVal  = [0,0], 
lat: t[0] || t.lat set lat in undefined, because t[0] === 0(i.e. false)

Need to patch function latLng() like this
```
                                n = {
                                    lat: t.lat || t[0],
                                    lng: t.lng || t[1]
                                };

```

### Versions
- Leaflet: v1.3.1
- Vue: v2.6.7
- Vue2Leaflet: v2.0.2

**Comment by DonNicoJs** [comment]
@nailfor those this happen with the latest vue2-leaflet version?

**Comment by nailfor** [comment]
after update to latest 2.1.1 set markere latLng to [0,0] work normaly
thx
