### ISSUE TITLE
how to draggable rectangle

### ISSUE THREAD

**Issue by haoxl3** [KoRiGaN/Vue2Leaflet#405]
### Description

why l-rectangle don't draggable?
#### Live Demo

http://jsfiddle.net/Boumi/k04zpLx9/
none
#### Steps to Reproduce
I want to rectangle to be able to drag across the map, just like marker,this is my code:
```
<l-rectangle :bounds="rectangle.bounds" :l-style="rectangle.style" :draggable="true" :visible="true"/>
```

#### Expected Results

but rectangle does not drag, I hope rectangle can drag
### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions
- Leaflet: v1.5.1
- Vue: v2.5.16
- Vue2Leaflet: v2.1.1

**Comment by bezany** [comment]
@haoxl3 Because in leaflet [rectangle](https://leafletjs.com/reference-1.5.0.html#rectangle) not have options `draggable`. You can try done custom draggable rectangle with [this approach](https://gis.stackexchange.com/questions/128189/creating-draggable-circle-in-leaflet).
