### ISSUE TITLE
does this plugin support IE browser?

### ISSUE THREAD

**Issue by lunjingjie** [KoRiGaN/Vue2Leaflet#408]
when I run this plugin in IE browser, it can not work，which IE browser version does it support ?

**Comment by DonNicoJs** [comment]
@lunjingjie this depends on how you are bundling your code.

**Comment by bezany** [comment]
@lunjingjie Yes, see this example https://bezany.github.io/wkt-map/ 
[Online test](https://www.browserling.com/browse/win/10/ie/11/https%3A%2F%2Fbezany.github.io%2Fwkt-map%2F).

**Comment by lunjingjie** [comment]
> @lunjingjie Plugin exactly works in ie11, see this example https://bezany.github.io/wkt-map/
> [Online test](https://www.browserling.com/browse/win/10/ie/11/https%3A%2F%2Fbezany.github.io%2Fwkt-map%2F).
> Theoretically, vue + leaflet support from IE9, but I not checked.
> [Also works in ie9](https://www.browserling.com/browse/win/vista/ie/9/https%3A%2F%2Fbezany.github.io%2Fwkt-map%2F)

thank you
