### ISSUE TITLE
I am getting a strange problem

### ISSUE THREAD

**Issue by entrehuihui** [KoRiGaN/Vue2Leaflet#409]
#### Steps to Reproduce
// [22.582088484855117, 113.91798093769808]
 center: function(v) {
      console.log(v, "+++++");
      console.log(this.$refs.lmapmy.mapObject.getCenter(), "--------");
    },

#### Expected Results

[22.582088484855117, 113.91798093769808] ++++++
LatLng {lat: 22.582088484855117, lng: 113.91798093769808 "--------"
#### Actual Results

[22.582088484855117, 113.91798093769808] ++++++
LatLng {lat: 22.573438264572406, lng: 113.90625 "--------"

### Browsers Affected

- [v ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions
- Leaflet: vX.X.X
- Vue: vX.X.X
- Vue2Leaflet: vX.X.X

**Comment by DonNicoJs** [comment]
@entrehuihui which version of vue2-leaflet?

**Comment by entrehuihui** [comment]
> @entrehuihui哪个版本的vue2-leaflet？

"vue2-leaflet": "^2.1.1"

**Comment by entrehuihui** [comment]
> @entrehuihui which version of vue2-leaflet?

thank you very much!
This phenomenon will appear when the first click is set, then change the coordinates to display the correct result, and then return the coordinates back.English is not good, I hope you can understand,

**Comment by mr337** [comment]
I believe I am getting the same issue. I have pinned it down to the starting zoom level.

My default has map configured with `data` as so:
```
zoom: 4,
center: latLng(39.8283, -95.5795) //roughly center of US
```

Upon pulling a location from the backend I update the map
```
this.zoom = 19
this.center = latLng(this.telem.lat, this.telem.long)
```

Console log output
```
Expected center: LatLng(37.127294, -93.297569) 
Map center: LatLng(37.160317, -93.339844)
```

And it is off just like @entrehuihui mentioned. The only temporary fix I could find was to have an initial starting zoom >= 8. What is odd is every zoom level from 1-8 seems to get closer and closer till dead on when zoom level 8 is reached.

**Comment by mr337** [comment]
Wonder if this is a timing thing, if I zoom first, then center like on a timer tick it works perfectly.

**Comment by DonNicoJs** [comment]
@mr337 @entrehuihui  so this issue is due to leaflet panTo method that has a small animation timeframe and hence takes time to update all the values.

In the codebase we already have a property called: `noBlockingAnimations` you can try to set that to `true` on `l-map` and see if this fixes the issue.

**Comment by entrehuihui** [comment]
> @ mr337 @entrehuihui 所以这个问题是由于传单panTo方法有一个小动画时间帧，因此需要时间来更新所有值。
> 
> 在代码库中，我们已经有一个名为的属性：`noBlockingAnimations`您可以尝试将其设置为`true`on `l-map`并查看是否可以解决问题。

Thank you for your help, I have solved this problem, the method is the same @mr337   as the method.
But I tried to use noBlockingAnimations

**Comment by entrehuihui** [comment]
> @mr337 @entrehuihui so this issue is due to leaflet panTo method that has a small animation timeframe and hence takes time to update all the values.
> 
> In the codebase we already have a property called: `noBlockingAnimations` you can try to set that to `true` on `l-map` and see if this fixes the issue.

Thank you for your help, I have solved this problem, the method is the same @mr337   as the method.
But I tried to use noBlockingAnimations to set true, it will make a deviation from the center point of the setting, Unless I re-edit a new center point again.I feel very much help again.I will go through the detailed setup to set noBlockingAnimations, and then record my results.

**Comment by mr337** [comment]
Looking around I found another related issue, https://github.com/KoRiGaN/Vue2Leaflet/issues/328.

Sadly the `noBlockingAnimations` has an effect but still isn't centered.

Original bug results:
```
Expected center: LatLng(37.127294, -93.297569) 
Map center: LatLng(37.160317, -93.339844)
```

Using `noBlockingAnimations` made the problem worse :(
```
Expected center: LatLng(37.127294, -93.297569) 
Map center: LatLng(39.8283, -95.5795)
```

What is odd is this behavior was in the pre 2.0 version. I'm not 100% for sure how that changed :S

**Comment by entrehuihui** [comment]
> 环顾四周，我发现了另一个相关的问题，[＃328](https://github.com/KoRiGaN/Vue2Leaflet/issues/328)。
> 
> 可悲的是，`noBlockingAnimations`它有效果，但仍然没有集中。
> 
> 原始bug结果：
> 
> ```
> Expected center: LatLng(37.127294, -93.297569) 
> Map center: LatLng(37.160317, -93.339844)
> ```
> 
> 使用`noBlockingAnimations`使问题变得更糟:(
> 
> ```
> Expected center: LatLng(37.127294, -93.297569) 
> Map center: LatLng(39.8283, -95.5795)
> ```
> 
> 奇怪的是这种行为是在pre 2.0版本中。我不是100％肯定这是怎么改变的：S



> Looking around I found another related issue, #328.
> 
> Sadly the `noBlockingAnimations` has an effect but still isn't centered.
> 
> Original bug results:
> 
> ```
> Expected center: LatLng(37.127294, -93.297569) 
> Map center: LatLng(37.160317, -93.339844)
> ```
> 
> Using `noBlockingAnimations` made the problem worse :(
> 
> ```
> Expected center: LatLng(37.127294, -93.297569) 
> Map center: LatLng(39.8283, -95.5795)
> ```
> 
> What is odd is this behavior was in the pre 2.0 version. I'm not 100% for sure how that changed :S

The result is tested multiple times, I get the same conclusion as you, noBlockingAnimations does not make the result better, but produces a larger deviation.

**Comment by javiertury** [comment]
@entrehuihui and @mr337, you are right. I made a mistake in [this patch](https://github.com/KoRiGaN/Vue2Leaflet/pull/347). `noBlockingAnimations` was reversed, e.i. blocking animations were disabled by default and `noBlockingAnimations` enabled them. I will try to amend it in #428.

Now let's go back to your issue, leaflet has tons of animations and many of them are blocking. Were you using `<l-map bounds="...">`? Did you manually call mapObject methods, e.g. `this.$refs.map.mapObject.fitBounds()`? Which ones?

**Comment by javiertury** [comment]
Pull request #429 corrects the meaning of `noBlockingAnimations`. It also disables animations for fitBounds which may block map changes.

If you still experience a mismatch between expected and actual coordinates, I suggest you take a look at:

1. Direct leaflet(`mapObject`) method calls such as `locate`, which may trigger blocking animations.
2. Events bouncing back and forth.
    * Floating point comparison is imprecise, some times `l-map` can receive a value for `center`, compare it against its internal value, decide it is not the same and trigger a `update:center` which triggers again a `center`. This happens until the value converges into a number, which may  be a little bit off the original value.
3. Leaflet bugs.
    * Leaflet is designed with user interaction in mind, but not programmatic use.
