### ISSUE TITLE
Widget options

### ISSUE THREAD

**Issue by fergardi** [KoRiGaN/Vue2Leaflet#41]
How to set original Leaflet widget zoom, navigation, scale options like position, attributes, etc?

**Comment by ais-one** [comment]
If I understand you correctly,

Refer to [https://github.com/KoRiGaN/Vue2Leaflet/issues/46](https://github.com/KoRiGaN/Vue2Leaflet/issues/46)

You can get the map object from there and use that to set whatever options you need.

If the answer not correct, please give an example of what you are trying to achieve.

**Comment by fergardi** [comment]
I'm trying to override the default widget options in http://leafletjs.com/reference-1.0.3.html#control and http://leafletjs.com/reference-1.0.3.html#control-zoom, like 'position': 'top-right', for example.

**Comment by ais-one** [comment]
Would the following help?

```
// inside mounted(), find the map object
// refer to https://github.com/KoRiGaN/Vue2Leaflet/issues/46
// do the following...
...
map.zoomControl.remove()
L.control.zoom({ position:'topright' }).addTo(map);
```

**Comment by fergardi** [comment]
Yes, it helps indeed! I guess it's reasonable to do so, but in the future those widget options should be customizable using :props, don't you think?

Thank you for your help.

**Comment by ais-one** [comment]
You may be right, but this Vue library is still pretty new to me so I can't make a good opinion on this.

The author of this library may be in a better position to explain why things are done in a certain way, but so far I do see this library being improved actively.

**Comment by KoRiGaN** [comment]
Hi @fergardi,

**Zoom** and **Scale** Controls in Leaflet are **not** implemented yet as I didn't have time to do it.

You will be able to modified **Attributions** via a prop on each TileLayer in the v0.0.50 thanks to @EyMaddis pull request.
**Layers** Control only works for WMSLayers at the moment thanks to @nikos pull request. More work will be requiered to make it a generic layer control.

Mickaël

**Comment by fergardi** [comment]
It's nice to know. Thanks for your work!

**Comment by ItsLhoudini** [comment]
So, is not possible to disactivate zoomControl?

**Comment by 3RedM0** [comment]
You can remove the control this way : 
`
map.zoomControl.remove()
`

**Comment by ItsLhoudini** [comment]
```
        name: 'map',
        props: [],

        data () {
            return {
                attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors',
                center: [47.413220, -1.219482],
                marker: [47.413220, -1.219482],
                url: 'http://{s}.tile.osm.org/{z}/{x}/{y}.png',
                zoom: 13,
                scrollWheelZoom: false
            }
        },

        mounted () {
            this.zoomControl.remove()
        },

```

Like this?

**Comment by ItsLhoudini** [comment]
YEAH, perfect!

**Comment by KoRiGaN** [comment]
Hi @fergardi, @ais-one, @ItsLhoudini,  

Controls are now implemented in v1.0.1.

Let me know if it solves your issue.

Micka

**Comment by ais-one** [comment]
ok, time to update package...

**Comment by ais-one** [comment]
@KoRiGaN 

Thanks for the notice, I have updated my code base (vue2-leaflet-tracksymbol v1.0.11) to work on Vue2Leaflet v1.0.1 in my develop branch, seems to be working fine.

[https://github.com/ais-one/vue2-leaflet-tracksymbol/tree/develop
](https://github.com/ais-one/vue2-leaflet-tracksymbol/tree/develop
)

Will push it to master once further testing is done.

**Comment by ais-one** [comment]
@KoRiGaN 

Done its on master branch now.

**Comment by KoRiGaN** [comment]
Closing as no comments for 3 weeks.
Please reopen this issue if it not solved yet.
