### ISSUE TITLE
Memory Leak l-map

### ISSUE THREAD

**Issue by camper6** [KoRiGaN/Vue2Leaflet#410]
### Description
VueComponents are accumulating as the view gets updated because of l-map. On a cleap app, the increase of VueComponents isn't so bad, but it's there. In our app, the problem is even worse  affecting our app performance (1022 VueComponents to 2000+ just from repeating step 5. to 6 below).

#### Live Demo
https://codesandbox.io/s/simple-todo-app-with-vue-91kyc

#### Steps to Reproduce
1. Go the Live Demo link
2. Open chrome devtools - Memory tab
3. Select codesandbox.io in the VM Instance
4. Click on collect garbage (the garbage icon on the top left beneath Elements tab)
5. Click on the 'Mimic Router Switch' buttons 6 times
6. Take a heap snapshot
7. Refresh and repeat step 4. to 6. again, except on step 5. make it 12 times
8. You will see in the heap snapshots the VueComponent number slowly increasing the more you switch views

#### Expected Results
The number of VueComponents stay consistent as the view gets updated, commenting out l-map does so.

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions
- Leaflet: ^1.5.1
- Vue: ^2.5.22
- Vue2Leaflet: ^2.1.1

**Comment by DonNicoJs** [comment]
@camper6 thanks for the very detailed issue. We did a memory investigation some time ago.. I will check the demo and report during the day

**Comment by DonNicoJs** [comment]
@camper6 I've gotten around to investigate this only now, I am sorry, i've been able to reproduce, checking possible causes now

**Comment by DonNicoJs** [comment]
@camper6 I managed to find the issue, fix it and release version 2.2.1 that address the issue.
THIS WAS A GREAT CATCH, and is going to be a performance boost for many complex applications.
KUDOS to you. 

If you can try 2.2.1 and let me know if it fixes the problem on your side too  I would be even more grateful

**Comment by camper6** [comment]
@DonNicoJs Finally had the time to update vue2-leaflet. Rerun tests and went through the steps to check for memory leak, and found VueComponents remain consistent after switching views with route.

So problem solved!

Thanks for your time and great job, Don. I'll close this issue now.

**Comment by DonNicoJs** [comment]
@camper6 Glad that it solved your issue! Sorry again for the long time before I could go and  investigate this issue.
