### ISSUE TITLE
PolyLine on top of geoJson

### ISSUE THREAD

**Issue by Simpey** [KoRiGaN/Vue2Leaflet#416]
Hi, i'm trying to put PolyLine on top of geoJson http://joxi.ru/D2PJ9a4tqxYv9r I've tried this solution:
https://stackoverflow.com/questions/44283449/leaflet-make-polyline-on-top-of-geojson and also tried to call bringToFront() from $refs - this.$refs.polyline.bringToFront() But nothing helped Can you help me with this one pls?

**Comment by DonNicoJs** [comment]
Hi! To access leaflet methods you need to use the `mapObject` prefix after
the ref!

`this.$refs.yourref.mapObject.leafletMethod()`
