### ISSUE TITLE
How to set custom Marker icon?

### ISSUE THREAD

**Issue by fergardi** [KoRiGaN/Vue2Leaflet#42]
How to set custom Marker icon?

**Comment by ffischer1984** [comment]
in your html file in <v-map>-tag:
<v-icondefault :image-path="path"></v-icondefault>
components:{ 'v-icondefault': Vue2Leaflet.Icon}

**Comment by fergardi** [comment]
The answer was:

```
v-marker(:icon="icon")
```

Where icon is:

```
icon () {
  return L.icon({
    iconUrl: url,
    iconSize: [40, 40],
    iconAnchor: [20, 20]
  })
}
```

**Comment by insanity54** [comment]
For future visitors, #95 has a good [example](https://jsfiddle.net/Boumi/z3bmc1ex/1/) of changing icons.

**Comment by bestian** [comment]
How do i set custom Marker icon in a <l-maker> component?

**Comment by ffischer1984** [comment]
`                <v-map :zoom="zoom" :center="center">
                    <v-tilelayer :url="url" :attribution="attribution"></v-tilelayer>
                    <v-marker v-for="item in markers" :key="item.key" :lat-lng="item.position" :icon="item.icon" :visible="true" v-on:l-click="onMarkerClick(item)"></v-marker>
                </v-map>`

The type of item.icon has to be L.icon (from leaflet)

**Comment by bestian** [comment]
it's not worked for me.

here's my code:

`<template lang="jade">
  .hello
    l-map(style="width: 100%; height: 600px;" ref="map", :zoom="7", :center="[22.413220, 121.219482]")
      l-tile-layer(:url="url", :attribution="attribution")
      l-marker(v-for = "h in hands", :lat-lng="countLatLng(h)", :icon="icon")
</template>

<script>

import { L } from 'leaflet'
import { LMap, LTileLayer, LMarker, LPopup } from 'vue2-leaflet'
import { handsRef } from '../firebase'
import mix from '../mixins/mix.js'

export default {
  name: 'map',
  mixins: [mix],
  components: {LMap, LTileLayer, LMarker, LPopup},
  data () {
    return {
      url: 'http://{s}.tile.osm.org/{z}/{x}/{y}.png',
      attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors',
      icon: L.icon(
        { iconUrl: 'https://cdn5.vectorstock.com/i/1000x1000/99/84/map-marker-icon-vector-13489984.jpg',
          shadowUrl: '',
          iconSize: [38, 95], // size of the icon
          shadowSize: [50, 64], // size of the shadow
          iconAnchor: [22, 94], // point of the icon which will correspond to marker's location
          shadowAnchor: [4, 62], // the same for the shadow
          popupAnchor: [-3, -76] // point from which the po
        })
    }
  },
  firebase: {
    hands: handsRef
  },
  methods: {
    countLatLng: function (h) {
      if (!h.latlngColumn) { return {lat: 0, lng: 0} }
      return {lat: h.latlngColumn.split(',')[0], lng: h.latlngColumn.split(',')[1]}
    }
  }
}
</script>`

please help, thanks~

**Comment by bestian** [comment]
It' not worked

My component is l-maker, not v-marker

Maybe the code will be different

**Comment by ffischer1984** [comment]
Yeah it's old source Code from me. You have replace v with l. I'm not really sure why you're talking about l-maker. I think the webcomponent is l-marker with a r

**Comment by bestian** [comment]
yes, it's  l-marker
how do i use custom icon on these components?

**Comment by ffischer1984** [comment]
hmmn there are two possibilities:
- your marker has false lat/lng coordinates (don't know what the
method "countLatLng"
really does) So look in your html-code if you can find the marker or use
the vue-dev tools
- there is something false with you'r jsx-code? (I'm not an expert in jsx)

Bestian Tang 小巴 <notifications@github.com> schrieb am Fr., 26. Okt. 2018 um
06:57 Uhr:

**Comment by eregnier** [comment]
hey, maybe it is late, maybe it is not : I made this library recently to do custom markers : 
https://github.com/eregnier/vue-leaflet-custom-marker
hope this helps

**Comment by JosephRidge** [comment]
Great stuff @eregnier
