### ISSUE TITLE
l-control-layers reordering when shown/hidden

### ISSUE THREAD

**Issue by mgiraldo** [KoRiGaN/Vue2Leaflet#420]
### Description
Overlay layer order gets modified when shown/hidden by `l-control-layers`

#### Live Demo
Repository link: https://github.com/mgiraldo/livingarchive/blob/9073277cddf9ca6c189fd0dd7ef1cd625de9fa9f/components/ResultsMap.vue#L22-L35

#### Steps to Reproduce
1. Add a `l-control-layers`
2. Add two `l-geo-json`with `layer-type="overlay"` that overlap
3. Turn on and off the overlays

#### Expected Results
The overlap of the overlays is preserved (lowest one in html being topmost)

#### Actual Results
The last one to be shown is topmost

![control](https://user-images.githubusercontent.com/133020/61550783-66fcd880-aa21-11e9-9fa1-19daaa6b3d1d.gif)

### Browsers Affected
- [x] Chrome
- [x] Firefox
- [x] Edge
- [x] Safari 12

### Versions
- Leaflet: v1.5.1
- Vue: v2.6.10
- Vue2Leaflet: v2.1.1
- nuxt-leaflet: v0.0.18

**Comment by mgiraldo** [comment]
seems related to this Leaflet/Leaflet#5201

**Comment by DonNicoJs** [comment]
@mgiraldo this sounds like a underlaying leaflet issue, closing here!
