### ISSUE TITLE
crossOrigin wms

### ISSUE THREAD

**Issue by lufias** [KoRiGaN/Vue2Leaflet#421]
In TileLayerWMS, can you please add option for crossOrigin?

**Comment by DonNicoJs** [comment]
@lufias you can pass crossOrigin option trough the `options` prop like this:

`< TileLayerWMS :options="{crossOrigin: true}" />`

**Comment by lufias** [comment]
Thank you.. it really never cross my mind that you can actually pass option..

**Comment by DonNicoJs** [comment]
Closing :)

**Comment by dulerong** [comment]
Thank you so much.

I was having warning issues in chrome, specifically the following message.

> Because a cookie’s SameSite attribute was not set or is invalid, it defaults to SameSite=Lax, which prevents the cookie from being sent in a cross-site request. This behavior protects user data from accidentally leaking to third parties and cross-site request forgery.

> Resolve this issue by updating the attributes of the cookie:
Specify SameSite=None and Secure if the cookie should be sent in cross-site requests. This enables third-party use.
Specify SameSite=Strict or SameSite=Lax if the cookie should not be sent in cross-site requests.

However, after attaching `:options="{crossOrigin: true}"` to my `LTileLayer` component, the warning messages stopped showing up.

Thanks!
