### ISSUE TITLE
map placement is weird on default vue project

### ISSUE THREAD

**Issue by srep2512** [KoRiGaN/Vue2Leaflet#425]
I discovered your awesome project and wanted to try it out with a default vue project. The map is loading but I don't know why the positioning is so wrong and it seems like multiple maps are rendered?

Is there something else that I have to configure? 
![map](https://user-images.githubusercontent.com/32433257/62031987-dffdec00-b1e8-11e9-86d9-8c805249ca4c.PNG)

vue create testleaf -n
cd testleaf
npm install leaflet vue2-leaflet --save

then I changed the "HelloWorld" component:

```vue
<template>
<div style="height: 100%; width: 100%">
    <div class="info" style="height: 15%">
      <span>Center: {{ center }}</span>
      <span>Zoom: {{ zoom }}</span>
      <span>Bounds: {{ bounds }}</span>
    </div>
    <l-map
      style="height: 80%; width: 100%"
      :zoom="zoom"
      :center="center"
      @update:zoom="zoomUpdated"
      @update:center="centerUpdated"
      @update:bounds="boundsUpdated"
    >
      <l-tile-layer :url="url"></l-tile-layer>
    </l-map>
  </div>
</template>

<script>
import {LMap, LTileLayer, LMarker } from 'vue2-leaflet';

export default {
  name: 'HelloWorld',
  data () {
    return {
      url: 'http://{s}.tile.osm.org/{z}/{x}/{y}.png',
      zoom: 3,
      center: [47.413220, -1.219482],
      bounds: null
    };
  },
  methods: {
    zoomUpdated (zoom) {
      this.zoom = zoom;
    },
    centerUpdated (center) {
      this.center = center;
    },
    boundsUpdated (bounds) {
      this.bounds = bounds;
    }
  }, 
  components: {
        LMap,
        LTileLayer,
        LMarker
  }
}
</script>

Browser: Mozilla Firefox 68.0.1

**Comment by DonNicoJs** [comment]
@srep2512 Hi! this is a typical case where CSS is not loaded:
https://korigan.github.io/Vue2Leaflet/#/quickstart?id=locally-installed-components
Check here and make sure you have imported the css somewhere in your project!

**Comment by srep2512** [comment]
@DonNicoJs Sorry for missing that in the documentation. Now it's working :)
