### ISSUE TITLE
Square and Ruler

### ISSUE THREAD

**Issue by nikitachernih** [KoRiGaN/Vue2Leaflet#426]
Hello

Need to implement in the project:
-Ruler calculator
-Square calculator
https://3planeta.com/googlemaps/google-maps-area-calculator-tools.html

Are there any options?

**Comment by justinbeatz** [comment]
You can check this one: https://github.com/ljagis/leaflet-measure

**Comment by nikitachernih** [comment]
> You can check this one: https://github.com/ljagis/leaflet-measure

Thank you!
