### ISSUE TITLE
noBlockingAnimations is inverted

### ISSUE THREAD

**Issue by javiertury** [KoRiGaN/Vue2Leaflet#428]
Last time #328, we discussed how Leaflet animations block Vue2Leaflet consecutive commands. The reason is that leaflet is built for user interaction, not for programatic use.

I sent [this patch](https://github.com/KoRiGaN/Vue2Leaflet/pull/347) to disable animations with `noBlockingAnimations`. But I made a mistake, that prop is reversed. Vue2Leaflet enables animations when `noBlockingAnimations = true` and viceversa.

The following lines [205](https://github.com/KoRiGaN/Vue2Leaflet/blob/master/src/components/LMap.vue#L205) and [218](https://github.com/KoRiGaN/Vue2Leaflet/blob/master/src/components/LMap.vue#L218) were affected

```js
// Wrong, current code
{ animate: !this.noBlockingAnimations ? false : null }
// What it should mean
{ animate: this.noBlockingAnimations ? false : null }
```

@mr337 says in [this comment](https://github.com/KoRiGaN/Vue2Leaflet/issues/409#issuecomment-509424633):

> Using noBlockingAnimations made the problem worse :(

Of course! After [the patch](https://github.com/KoRiGaN/Vue2Leaflet/pull/347) that I submitted in January everyone had blocking animations disabled by default. Those that tried to use `noBlockingAnimations` were renabling again those animations.

So, should blocking animations be enabled by default and make `noBlockingAnimations = true` disable animations?

**Comment by DonNicoJs** [comment]
@javiertury yes, can you proceed with this PR ?
