### ISSUE TITLE
Map initialization - gestureHandling

### ISSUE THREAD

**Issue by mawieutc** [KoRiGaN/Vue2Leaflet#430]
Hello,

I am trying to add gesturehandling so that the user won't unzoom when scrolling down.

I installed leaflet-gesture-handling through npm

```
import { GestureHandling } from "leaflet-gesture-handling";
L.Map.addInitHook("addHandler", "gestureHandling", GestureHandling);
```

but this doesn't do anything
<l-map ref="map" :zoom="zoom" :center="center" gestureHandling :options="mapOptions" @update:center="centerUpdate" @update:zoom="zoomUpdate">

any idea how to do this?

thanks a lot!

**Comment by mawieutc** [comment]
it works with this.$refs.map.mapObject.zoomOut();
So now I would like to fit bounds content... this doesn't work though
this.$refs.map.mapObject.fitBounds(this.$refs.map.mapObject.getBounds());

**Comment by timdorey** [comment]
@mawieutc 
> it works with this.$refs.map.mapObject.zoomOut();
> So now I would like to fit bounds content... this doesn't work though
> this.$refs.map.mapObject.fitBounds(this.$refs.map.mapObject.getBounds());

I am attempting to use gestureHandler plugin also but have not been able to get it to work. Did you end up finding a solution?

**Comment by mawieutc** [comment]
Actually yes! Here is my code:

```
<l-map ref="map" gestureHandling :options="mapOptions">

import { GestureHandling } from "leaflet-gesture-handling";

  data () {
    return {
      mapOptions: {
        zoomSnap: 0.5,
        gestureHandling:true
      }
   }

```

**Comment by timdorey** [comment]
@mawieutc 

Perfect! That worked like a charm. Thanks.

**Comment by fbnlsr** [comment]
Sorry to bump this issue but @mawieutc's solution does not work for me. I'm using Vue2 with TypeScript, and it seems the `GestureHandling` import is never used in that example. Also, the `gestureHandling` parameter inside the `l-map` tag gets renamed to `gesture-handling`.

Anyone has a full working example to share?

**Comment by tripflex** [comment]
For anybody using this and the custom text/wording, **make sure** you specify `duration` in the `gestureHandlingOptions` otherwise for some reason it sets it to zero or something odd and doesn't show
