### ISSUE TITLE
generate maker with click

### ISSUE THREAD

**Issue by hack20858** [KoRiGaN/Vue2Leaflet#436]
Good morning, I need to generate a maker when the person clicks on the map, obviously the maker has to be generated and give me the latitude and longitude, will this be possible? From already thank you very much

**Comment by Carnid** [comment]
Take a look at this fiddle: http://jsfiddle.net/b2g1Lt9y/
The important bits are to:
- have an `<l-marker>` tag with a `v-for` that points to an array of markers
- have a `@click` (or `v-on:click`) event handler on your map that binds to a method in your component
- this method (`addMarker`) has an event, which conveniently supplies the `latlng` of where the user clicked. So you only need to add this latlng to your array of markers

**Comment by hack20858** [comment]
Thank you, this worked for me.
