### ISSUE TITLE
doubleClickZoom binding does not seem to work for l-map

### ISSUE THREAD

**Issue by Carnid** [KoRiGaN/Vue2Leaflet#438]
### Description
doubleClickZoom option doesn't seem to be passed to the leaflet map object as per leaflet documentation: https://leafletjs.com/reference-1.5.0.html#map-doubleclickzoom

#### Live Demo
Here: http://jsfiddle.net/snLedmf0/

#### Steps to Reproduce
Add any `<l-map>` component to your view, add `:doubleClickZoom="false"` and double-click on the map

#### Expected Results

It should not zoom in

#### Actual Results

It zooms in

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions
- Leaflet: v1.3.2
- Vue: v2.5.3
- Vue2Leaflet: v1.0.2

**Comment by Carnid** [comment]
I would be glad to use a workaround if possible. If there is any clean way to get the Leaflet.Map object that was created and add the option using javascript I could do it.

**Comment by DonNicoJs** [comment]
@Carnid double click zoom is not an implemented prop but, any leaflet option can be passed on `options` prop, let me know if this fixes the problem

**Comment by Carnid** [comment]
Ah so that's how it works! Yes it works, thank you :)
While I have you on the line, is there documentation on how to access the underlying leaflet javascript objects after the vue components have been instanciated? Say I wanted to programmatically call `openPopup(latlng)` on a popup that I added beforehand?

**Comment by DonNicoJs** [comment]
https://korigan.github.io/Vue2Leaflet/#/faq/

mapObject is also returned by all the ready events
