### ISSUE TITLE
How to use two different Icon-pics??

### ISSUE THREAD

**Issue by ffischer1984** [KoRiGaN/Vue2Leaflet#44]

**Comment by ais-one** [comment]
More details please

**Comment by KoRiGaN** [comment]
Hi @ffischer1984,
 
It seems more of a leaflet question.
[here](http://leafletjs.com/examples/custom-icons/) you will find how to create different icon with leaflet.

You can then bind these to the marker icon property in vue2-leaflet.

Mickaël

**Comment by KoRiGaN** [comment]
Closing as no answer for 10 days.
