### ISSUE TITLE
Autocomplete

### ISSUE THREAD

**Issue by chrisgrim** [KoRiGaN/Vue2Leaflet#441]
Hi,
I am loving this plugin, it seems like a great way to get around Google's rates. I was wondering if there was any autocomplete functionality like google places? I'd love for users to be able to enter their address and it show up on the map.

**Comment by DonNicoJs** [comment]
@chrisgrim take a look at the plugin section of our docs :)

**Comment by chrisgrim** [comment]
Hi @DonNicoJs 
Thanks so much for the quick response! I tried installing the vue2-leaflet-geosearch plugin and ran into a bit of a issue and I am not sure if I should ask here or not. I see that with Vue2Leaflet everything is called by <l-map :zoom="zoom" :center="center">. However when I tried to do the plugin it is now being called by <v-map :zoom=3 :center="location"></v-map>. I tried adding all the code provided with the plugin documentation but I think I am missing something. I am getting a console error : Vue2Leaflet is not defined. Yet I believe I am calling it. Here is my code
`<template>
	<div class="create-content">
		<div class="create-title">
    		<h2> Location</h2>
    	</div>

			<v-map :zoom=3 :center="location">
			  <v-tilelayer url="http://{s}.tile.osm.org/{z}/{x}/{y}.png"></v-tilelayer>
			  
			  <v-geosearch :options="geosearchOptions" ></v-geosearch>
			  
			</v-map>
				
		    <div class="create-button">
		        <button @click.prevent="submitLocation()" class="create"> Next </button>
		    </div>

		</div>
    </div>
</template>

<script>
	import {LMap, LTileLayer, LMarker} from 'vue2-leaflet'
	import { OpenStreetMapProvider } from 'leaflet-geosearch';
	import VGeosearch from 'vue2-leaflet-geosearch';

	Vue.component('v-map', Vue2Leaflet.Map);
	Vue.component('v-tilelayer', Vue2Leaflet.TileLayer);

	export default {

		components: { 
			LMap, 
			LTileLayer, 
			LMarker,
			VGeosearch
		},

		data() {
			return {

				places: [],
				currentPlace: null,
				address: '',
				zoom:13,
				center: L.latLng(45.508, -73.587),
				url:'http://{s}.tile.osm.org/{z}/{x}/{y}.png',
				marker: L.latLng(47.413220, -1.219482),
				markers: [],
				geosearchOptions: { provider: new OpenStreetMapProvider(),},
			}
		},

		methods: {
			

			addMarker(e) {
		  		this.markers.push({latlng: e.latlng});
		  	},

			geolocate() {
				navigator.geolocation.getCurrentPosition(position => {
					this.center = {
						lat: position.coords.latitude,
						lng: position.coords.longitude
					};
				});
			},
		},
};



</script>`

**Comment by DonNicoJs** [comment]
I believe this is an error in the plugin, trying to mount vue2leaflet in the wrong way, try to link this issue in their repo and see if they can help you, if not please ping me back

**Comment by chrisgrim** [comment]
Hi @DonNicoJs 
I just added the issue to their repo. Thank you so much!!

**Comment by chrisgrim** [comment]
Hi @DonNicoJs 
I haven't heard back from from them. Do you know how long it takes for them to respond? 
Thanks!

**Comment by DonNicoJs** [comment]
@chrisgrim Sorry for the slow answer, no I have no idea sadly :( is this still not working ?

**Comment by chrisgrim** [comment]
Hi @DonNicoJs I never was able to get it to work so I decided to go a different route and use google maps. Sorry for not closing this.
