### ISSUE TITLE
Am I misunderstanding how to capture Leaflet events?

### ISSUE THREAD

**Issue by wishinghand** [KoRiGaN/Vue2Leaflet#449]
According to the Vue2Leaflet docs:
"Most of our components do not emit events but all the components pass down listeners for leaflets events. It's possible to bind to them by simply writing `@leafletEventName`"

I'm not seeing that happen with the popup. I checked the Leaflet docs and there is an event that Popups have inherited from Layer called `popupclose`. Whenever I listen for that event, I don't get any reaction.

#### Live Demo
https://jsfiddle.net/wishinghand/scpder2x/1/

#### Steps to Reproduce
1. Add a popup close event listener to a popup: `<l-popup @popupclose="testEvent">`
2. Log to the console in the function
3. Open a popup, then close it
4. Notice that any `console.logs` have not appeared

#### Expected Results
for `@popupclose` to emit an event

#### Actual Results
No event is emitted

### Browsers Affected

- [ ] Chrome
- [ X ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions
- Leaflet: v1.5.1
- Vue: v2.5.22
- Vue2Leaflet: v2.2.1

**Comment by DonNicoJs** [comment]
@wishinghand Ehi! I think leaflet docs are not super clear but `popupclose` is emitted by the map, or the layer where is bound :) not the popup itself! 

https://leafletjs.com/reference-1.5.0.html#map-popupclose
here is the fixed fiddle:
https://jsfiddle.net/odymch9s/1/

**Comment by wishinghand** [comment]
Ah, I see. I got it working. Thanks!
