### ISSUE TITLE
Updating marker position

### ISSUE THREAD

**Issue by MichalKrakow** [KoRiGaN/Vue2Leaflet#45]
Not sure if i understood marker component code but it seems there's no way to call setLatLng() on marker and just binding :lat-lng="position" will not trigger map refresh when the value changes.

This should be an option for some live maps applications.
Regards.

**Comment by MichalKrakow** [comment]
Ugly but works:
```
this.$refs.myLoc.mapObject.setLatLng(this.position);
```

**Comment by ais-one** [comment]
Thanks for the tip, 

For my case the lat-lon will come from some piece of data in the Vuex store, after mutating the data, need to also reflect the change on the marker (tracksymbol in my case)...

**Comment by KoRiGaN** [comment]
@MichalKrakow  Yes that's ugly...

I will look into it as it is suppose to work.

**Comment by procreatorspl** [comment]
This happens only for small changes that does not require map to redraw. If map redraws the marker gets updated.

**Comment by KoRiGaN** [comment]
Fixed In v0.0.50

Mickaël
