### ISSUE TITLE
save additional data to polyline component

### ISSUE THREAD

**Issue by Razz21** [KoRiGaN/Vue2Leaflet#454]
Hi there, is there an option to extend Polyline component to save additional data (eg. id to identify line)? I am trying to implement programmatic component selection.

**Comment by DonNicoJs** [comment]
@Razz21 what about putting refs on the components?

**Comment by Razz21** [comment]
Thanks for fast response. 
Marker component allows to extend `options` prop, I thought there is similar way for Polyline.

**Comment by DonNicoJs** [comment]
@Razz21 you can add new data to options anyhow, without modifying the source code! can I see a piece of code?

**Comment by Razz21** [comment]
well, i tried to use options prop before, but not found my variables in polyline options property.
I simply add existing Options mixin to Polyline component

**Comment by DonNicoJs** [comment]
@Razz21 Oh interesting, so this is a bug :) I'll take a look, polyline should inherit options too

**Comment by Razz21** [comment]
According to manual `options` prop is not supported in this component.
Thanks for help, presented solution works for me.
