### ISSUE TITLE
How to change center, zoom, bounds of the map?

### ISSUE THREAD

**Issue by fergardi** [KoRiGaN/Vue2Leaflet#46]
Like in leaflet, setCenter(), setZoom(), setBounds(), etc?

Where is the map object exposed to use it?

Thanks.

**Comment by ais-one** [comment]
Pass in a ref in v-map

```
    <v-map 
      ref="map"
      ...
    >
    </vmap>
```

Then You can get access to it during when component is mounted

```
  mounted: function () {
    const mapComponent = this.$refs.map
    ...
  }
```

And use it elsewhere...

**Comment by fergardi** [comment]
This indeed exposes the v-map object, which has setCenter and setBounds, for example. What I'm trying to achieve is to access the Leaflet map, which has many more options to work with.

**Comment by ais-one** [comment]
I think I know what you mean, I wanted to add layer control also...

```
    const mapComponent = this.$refs.map
    const childrenLen = mapComponent.$children.length
    const map = mapComponent.mapObject // the leaflet map object
    for (let i = 0; i < childrenLen; i++) {
      if (mapComponent.$children[i].$tileLayer !== undefined) { // base layer
        const tileLayer = mapComponent.$children[i].$tileLayer
        const name = mapComponent.$children[i].$vnode.data.attrs.name
        if (name === 'x1') baseLayers.osm = tileLayer
        if (name === 'x2') baseLayers.mapbox = tileLayer
      } else if (mapComponent.$children[i].$vnode !== undefined) { // overlay layer
        const tileLayer = mapComponent.$children[i].mapObject
        const name = mapComponent.$children[i].$vnode.data.attrs.name
        if (name === 'g1') overlays.tracks = tileLayer
      }
    }
```

**Comment by fergardi** [comment]
That was **exactly** what I was looking for, thanks! **this.$refs.map.mapObject** is the actual Leaflet map!

**Comment by KoRiGaN** [comment]
@fergardi  yes all components have a property mapObject which is the actual Leaflet object.

So it works for all components (Marker, Circle, etc)  ;-)

**Comment by robertjoellewis** [comment]
I resolved this with the following syntax:

I declared centerLatLong as empty object in data (), then ...

mounted () {
    this.$refs.map.mapObject.on('move', () => {
      this.centerLatLong = this.$refs.map.mapObject.getCenter()
      console.log('map was moved')
    })
  }
