### ISSUE TITLE
LMarker.vue with title

### ISSUE THREAD

**Issue by nailfor** [KoRiGaN/Vue2Leaflet#470]
### Versions
- Leaflet: v1.5.1
- Vue: v2.6.7
- Vue2Leaflet: v2.1.1

In Leaflet docs https://leafletjs.com/reference-1.5.0.html#marker Marker has a 'title' prop. 
If I write:
```
    var options = optionsMerger(Object.assign({}, this.layerOptions,
      {icon: this.icon,
      zIndexOffset: this.zIndexOffset,
      draggable: this.draggable}), this);
    options.title=this.name;
```
and call
```
<l-marker :lat-lng='{"lat":55.625684,"lng":37.790262}' name='134 км' layer-type='edit' >
```
all works fine, but without  options.title=this.name i can't set title options
How I can do this?

PS: Of couse, I know how call 'popup', but this is overload...

**Comment by DonNicoJs** [comment]
@nailfor You can pass the options directly in the `options` prop as a dictionary, this way you do not need `optionsMerger` let me know if this fix your problem

**Comment by nailfor** [comment]
Yes, its work
<v-marker :lat-lng='{"lat":55.625684,"lng":37.790262}' :options='{title: "134 км"}' layer-type='edit' >

but, may be, better way is 'title' property?

**Comment by DonNicoJs** [comment]
@nailfor I did not yet check 1.5 leaflet, but we add 'direct' properties only if there is a corresponding `setProperty` that we can call when the reactive property change.

**Comment by nailfor** [comment]
thx for quick help ))
