### ISSUE TITLE
Getting Reference to VMap

### ISSUE THREAD

**Issue by Grogglex** [KoRiGaN/Vue2Leaflet#50]
Hi guys, first off, thanks so much for working on this library. Secondly, I'm wondering if there is a way to get a reference to the `map` object from within the component that the map is embedded. So, for instance I'd like to be able to use Leaflet to `panTo` but I'm unsure how to get a handle on it to call anything against it. I see that the component structure looks like this:

![image](https://cloud.githubusercontent.com/assets/22781313/26797201/728168e6-4a02-11e7-82b9-c2d2e4cd5d8a.png)

But I'm not sure how to access the map within the VMAP component under my Stroll Map component. Any help with this would be great! Thanks.

**Comment by Grogglex** [comment]
Saw something in closed issues about using Refs. I'll close this and if it doesn't work then I'll come back. Don't know how I missed it.

**Comment by SupriyaSudhindra** [comment]
did you find the solution for it?

**Comment by SupriyaSudhindra** [comment]
Hi @KoRiGaN ,
   Actually, I was talking about using 'panTo' functionality and not refs..

**Comment by KoRiGaN** [comment]
Once you have access to the Leaflet map object you can use it as in Leaflet.
so map.panTo(...) should work.

**Comment by SupriyaSudhindra** [comment]
@KoRiGaN Thank you...I tried as you said it gave error saying "Uncaught TypeError: me.$refs.map.panTo is not a function"

**Comment by SupriyaSudhindra** [comment]
Also...i checked the map object...i didn't find the panTo property..

**Comment by KoRiGaN** [comment]
In the readme it is said:
`this.$refs.map.mapObject;`
so use:
`this.$refs.map.mapObject.panTo(...);`
