### ISSUE TITLE
Image Overlay with v-for not updating when removing elements from array

### ISSUE THREAD

**Issue by fergardi** [KoRiGaN/Vue2Leaflet#55]
As opposed as the v-for v-marker behaviour, in which I can add and remove markers of an array and the map updates accordingly, if I do the same with v-for v-image-overlay and add and then remove the image, the layer won't update and the old image remains rendered forever.

Is there a method for forcing to redraw the map or at least redraw the layer?

Thanks.

**Comment by KoRiGaN** [comment]
I think the good way to manage this is to remove image overlay from layers in the before destroy event.

It's not even well manage for the marker as is it simply hidden and not removed.
Work should be done to test adding/removing components for all components.

Don't have much time for this at the moment.

**Comment by KoRiGaN** [comment]
Hi @fergardi,

Do you have an example reproducing this issue?
The Vue2Leaflet version v0.0.55 includes beforeDestroy methods that should correctly remove ImageOverlay from the map.

Cheers,

Mickaël

**Comment by KoRiGaN** [comment]
@fergardi,
 
I did some tests around it and it seems to work correctly with the last version of Vue2Leaflet.

[Here](https://jsfiddle.net/Boumi/eykybb8u/) is the working version with Vue2Leaflet 0.0.55.

[Here](https://jsfiddle.net/Boumi/eykybb8u/2/) is the version reproducing the bug with Vue2Leaflet 0.0.53.

I'm closing this for now. Feel free to reopen it if you still have troubles.

Cheers,

Mickaël
