### ISSUE TITLE
Listening for Ready Event of Map

### ISSUE THREAD

**Issue by Grogglex** [KoRiGaN/Vue2Leaflet#57]
I'm having an issue where if the user navigates away from the map while it's loading it's causing strange behavious in other parts of my application. I'm wondering if there is a way to listen for the `l-ready` event from the V-Map from the parent component?

I've tried to listen in `mounted`:

```
     this.$refs.strollMap.$on('l-ready', function(){
        console.log('Ready')
      })
```
But I can't seem to get a hook into it.

**Comment by KoRiGaN** [comment]
Hi @Grogglex,

Not sure what is your issue, but I assume that in mounted hook it's too late and the l-ready event was already triggered.

The best way would be to handle the ready event directly 

```
v-on:l-ready="doSomething" 
```
There you could propagate the event or do what you want

**Comment by Grogglex** [comment]
Hi, sorry for the poorly posted issue. I ended up attaching the listener with this syntax:

`    <v-map @l-ready="mapReady()" v-if="initialLocation !== null" :zoom="30" :min="0" :max="20"
           :center="[initialLocation.latitude, initialLocation.longitude]" id="map" ref="map">`

Sorry for the silly issue! Thanks for your great library.
