### ISSUE TITLE
imageoverlay 'lat' not defined

### ISSUE THREAD

**Issue by b0rt** [KoRiGaN/Vue2Leaflet#58]
I am almost certain its a user error on my part but when i try to add imagoverlay im getting 
Cannot read property 'lat' of undefined

here is an example of the usecase
https://jsfiddle.net/b0r7/9f2yf3xh/20/

**Comment by KoRiGaN** [comment]
Hi @b0rt,

You need to provide the bounds property of the image overlay and it should work.

Mickaël

**Comment by b0rt** [comment]
Hi @KoRiGaN ,

you are correct. Thank you.

I did update the fiddle for future researchers with a working example
https://jsfiddle.net/b0r7/9f2yf3xh/31/
