### ISSUE TITLE
unable to set maxZoom above 18

### ISSUE THREAD

**Issue by CharlesOkwuagwu** [KoRiGaN/Vue2Leaflet#59]
Hi, i'm unable to set maxZoom above 18.

My code:

```
<template>
  <div style="height: 100%; width:100%">
      <v-map style="height: 100%; width:100%" :zoom="zoom" :center="center" :maxZoom="max" :minZoom="min">
        <v-tilelayer :url="url" :attribution="attribution" :maxZoom="max" :minZoom="min"></v-tilelayer>
      </v-map>
  </div>
</template>

<script>
  import Vue2Leaflet from 'vue2-leaflet';

  export default {
    name: 'home',
    components: {
      'v-map': Vue2Leaflet.Map,
      'v-tilelayer' :Vue2Leaflet.TileLayer,
      'v-marker': Vue2Leaflet.Marker
    },
    data () {
      return {
        zoom: 17,
        max: 19,
        min: 13,
        center: L.latLng(6.328400, 8.105166),
        url: 'http://localhost:5000/tiles/{z}/{x}/{y}/',
        attribution: 'Demo'
      }
    }
  }
</script>
<style>
</style>
```

**Comment by KoRiGaN** [comment]
Hi @CharlesOkwuagwu ,

It works for me. [Here](https://jsfiddle.net/5she0969/1/) is a running example with a maxZoom of 20.

**Comment by CharlesOkwuagwu** [comment]
will retry

**Comment by ergonomicus** [comment]
@KoRiGaN @CharlesOkwuagwu it seems that it doesn't work, is it?

**Comment by chrisamow** [comment]
> Hi @CharlesOkwuagwu ,
> 
> It works for me. [Here](https://jsfiddle.net/5she0969/1/) is a running example with a maxZoom of 20.

Hi KoRiGaN,
I was trying to implement this and noticed even on your jsfiddle when zoomed in to levels 19 and 20 there are no features.  Did this solution break since this original issue (was so long ago)?
