### ISSUE TITLE
Questions: Ability to load multiple tileLayers?

### ISSUE THREAD

**Issue by akhchan99** [KoRiGaN/Vue2Leaflet#63]
Is it possible to load multiple tileLayers?

eg. I used the ESRI World map, and I want to overlay the boundary and transport layer.

I tried

```
<v-map>
  <v-tilelayer :url="esriWorldLayer">
  <v-tilelayer :url="esriBoundaryLayer">
  <v-tilelayer :url="esriTransportLayer">
</v-map>
```

But the end result only show the TransportLayer.

I also tried to set the zIndex through params, but doesn't seem to work.

**Comment by akhchan99** [comment]
I accomplished this by using the $refs
```
<v-map ref="map">
```
define these constants
```
const esriBoundary = L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/Reference/World_Boundaries_and_Places/MapServer/tile/{z}/{y}/{x}')

const esriTransport = L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/Reference/World_Transportation/MapServer/tile/{z}/{y}/{x}')
```
in a method, call
```
this.$refs.map.mapObject.addLayer(esriTransport)
this.$refs.map.mapObject.addLayer(esriBoundary)
```

**Comment by sobiero** [comment]
@akhchan99 Do you have a sample of this code anywhere in jsfiddle? I'm trying the same but can't get it to work

**Comment by akhchan99** [comment]
Check this

[jsfiddle](https://jsfiddle.net/7bc4aoud/)

how I made it work is it load different tile as normal, when its loading ESRI layer (I added a watch), and manually added a layer on top of it (the transport layer) using the map reference.

**Comment by sobiero** [comment]
Thanks @akhchan99 , works perfectly
