### ISSUE TITLE
Style.JSON

### ISSUE THREAD

**Issue by ItsLhoudini** [KoRiGaN/Vue2Leaflet#64]
Hi there, is it possible to load custom map styles like [Klokantech](https://github.com/openmaptiles/klokantech-basic-gl-style), and how?

Thanx

**Comment by KoRiGaN** [comment]
Hi @ItsLhoudini,

I think it's possible.
First you have to serve tiles from somewhere, this can be raster or vector tiles. For example [TileServer GL](http://tileserver.readthedocs.io/en/latest/) can provide this.

Then you have to choose if you want to use raster or vector tiles.
Leaflet doesn't support vector tiles natively so I think it's easier to use raster tiles. 
They will be server on http://localhost:8080/styles/ciwf4zbsv007y2pmt2rspc1dc/{z}/{x}/{y}.png
(ciwf4zbsv007y2pmt2rspc1dc is KlokanTech style's id.

If you want to use vector tiles it involves some plugin to make leaflet compatible with WebGL and vector tiles. I think it should work but I never tried it.
You can have a look at [MapBox GL Leaflet](https://github.com/mapbox/mapbox-gl-leaflet)

Let me know if you try these kind of things.

Mickaël

**Comment by KoRiGaN** [comment]
@ItsLhoudini I'm closing this as no comment for 2 weeks.
Reopen it if you need to.

Cheers.

**Comment by lostdesign** [comment]
I know this is two years old, but that Gist helped me work it out. https://gist.github.com/timwis/eb2c7824bc8dca1727bd1bd96ecf24f0
