### ISSUE TITLE
How can i get street names?

### ISSUE THREAD

**Issue by safeallahee** [KoRiGaN/Vue2Leaflet#65]
Is there a way to get the streets name that clicked on map?

**Comment by KoRiGaN** [comment]
Hi @safeallahee,

This is more a Leaflet question. But as far as I know Leaflet only display images from location and zoom level. It as no knowledge of street name, city and all this kind of information.

You have to make a call to an other service like [Nominatim](https://nominatim.openstreetmap.org/) to do a reverse geocoding request and get location information from latitude and longitude.

Hope this helps.

Mickaël
