### ISSUE TITLE
Conditionally rendered geoJSON

### ISSUE THREAD

**Issue by lisovenkoNastya** [KoRiGaN/Vue2Leaflet#66]
Hello! Thanks for this component.
I have trouble with a conditionally rendered geoJSON layer.

I include the layer in the existing map with such code:
`<v-geojson-layer v-if="geojson" :geojson="geojson"></v-geojson>`

When I switch the variable "geojson" from "undefined" to some real data, I get an error:
[Vue warn]: Error in mounted hook: "TypeError: Cannot read property 'addLayer' of undefined"

I guess the problem in this string: https://github.com/KoRiGaN/Vue2Leaflet/blob/master/src/components/GeoJSON.vue#L11

this.$parent.$mapObject returns "undefined". 
And this.$parent.mapObject (without $) returns a proper parent object.

I guess this.$parent.$mapObject should be replaced by  this.$parent.mapObject

**Comment by KoRiGaN** [comment]
@jteppinette PR should fix your issue in v0.0.52.

Let me know.

**Comment by KoRiGaN** [comment]
Hi @lisovenkoNastya I 'm closing this issue as it have not been commented for 2 weeks.
I assume @jteppinette  PR fixed this issue.

Feel free to reopen this issue if you still have troubles with this.

Cheers,

Mickaël
