### ISSUE TITLE
GeoJSON onEachFeature

### ISSUE THREAD

**Issue by securit** [KoRiGaN/Vue2Leaflet#67]
Firstly, is there a way to stylize each Feature of a collection?

eg with the following GeoJSON
```
{"type": "FeatureCollection",
  "features": [
    {"type": "Feature",
      "geometry": { "type": "LineString", "coordinates": [[174.346433, -35.739337], [174.346433, -35.739337]]},
      "properties": { "in_port": true,  "id": 12824}
    },
    {"type": "Feature",
      "geometry": { type": "LineString","coordinates": [[ 174.346433,-36.739337],[174.347434,-35.739337]]},
      "properties": {"in_port": false, "id": 12824
      }
    }
]
}
```
I would like to colorize the generated lines based upon the in_port property. 
Secondly I would like to attach a popup to each line string (ie feature) when I click on it?

**Comment by felipefreitasffs** [comment]
I need the same thing

**Comment by KoRiGaN** [comment]
@jteppinette PR should fix your issue in v0.0.52.

Let me know.

**Comment by KoRiGaN** [comment]
Hi @securit and @felipefreitasffs,

This example https://jsfiddle.net/Boumi/t87cj3rs/ show how to switch styles and popup content for geojson features.

Let me know if it helps,

Cheers,

Mickaël

**Comment by KoRiGaN** [comment]
Closing as no comment for a while.
