### ISSUE TITLE
support for circles

### ISSUE THREAD

**Issue by berendberendsen** [KoRiGaN/Vue2Leaflet#7]
Happy to make a PR

**Comment by KoRiGaN** [comment]
Accidentally closed this issue instead of #5, so I'm reopening it.
Will may have some time to work on it tomorrow.

**Comment by KoRiGaN** [comment]
Hi Berend, 
Here is a simple implementation for circles. There is a small example in the example folder.

**Comment by berendberendsen** [comment]
Thanks @KoRiGaN! Works like a charm
