### ISSUE TITLE
How to use Leaflet-MiniMap?

### ISSUE THREAD

**Issue by COLABORATI** [KoRiGaN/Vue2Leaflet#77]
OK, I am trying to "vue-ize" a leaflet app - thank you very much for this code, it helps to understand how that might work. 

Now: how do I use leaflet plugins like e.g. [Leaflet-MiniMap](https://github.com/Norkart/Leaflet-MiniMap)?

I need to make it a vue component? Would you like to provide an example?
Some documentation about how to do that for other plugins would be great!
Thank you very much!

**Comment by KoRiGaN** [comment]
Hi @COLABORATI,

Yes the easiest way is to make a vue component.

You can see example of some plugins: 
[MarkerCluster](https://github.com/jperelli/vue2-leaflet-markercluster)
[TrackSymbol](https://github.com/ais-one/vue2-leaflet-tracksymbol)

I will add this to readme file so people can find this information easily.

Let me know if it helps,

Cheers,

Mickaël

**Comment by KoRiGaN** [comment]
Hi @COLABORATI,

I'm closing this as it's not active for two weeks. 
Feel free to reopen it if you need more help.

Cheers,

Mickaël
