### ISSUE TITLE
Accessing to internal Leaflet map object

### ISSUE THREAD

**Issue by mpallante** [KoRiGaN/Vue2Leaflet#79]
Hello everyone,

I'm trying to access the Leaflet map object contained in the component, but without any luck. I need it so that I can call methods on the map object. In particular, I'm trying to call the `locate()` method.

I've seen that there is a `mapObject` variable inside the `Map` component, bu I'm not able to access it. I also tried to register the `l-ready` event (that seems to be fired at the end of the initialization process), but then I cannot access the context.

I did this in my component:
```
<template>
    <div>
        <v-map v-on:l-ready="readyHandler"></v-map>
    </div>
</template>
<script>
    ...
    methods: {
        readyHandler() {
            // ?!?
        }
    }
    ...
</script>
```
If I try `console.log(this)` inside the handler, I get my component and not the `Map`.

How can I solve this?

Thanks a lot!

**Comment by ivanjaros** [comment]
I have solved it with using the l-ready event, as you, and assigning the map object to data attribute via `this.mapObject = this.$children[0].mapObject;` in the main "app". The map is the first element so key is 0 but it would be better to search for 'mapObject' in all children and find the correct child that way.

**Comment by KoRiGaN** [comment]
Hi @mpallante & @ivanjaros,

You can use Vue refs to access it.
So for example : 
`
<v-map ref="map" ...>
...
</v-map>
`
Then in your code you can use this ref to access the inner mapObject which is Leaflet instance: 
`this.$refs.map.mapObject`

The $refs property will only populated after the Vue instance is mounted I think. I you use it before that you should have undefined.

Let me know if this solve your problem.

**Comment by ivanjaros** [comment]
Thanks, that is a better approach.

**Comment by mpallante** [comment]
Thanks a lot @KoRiGaN, this is exacly what I needed. Sorry for the late answer, but I was busy with other tasks. I'm closing the issue.

**Comment by robertjoellewis** [comment]
Does this (this.$refs.map.mapObject) still work with the new version of leaflet? I can't seem to get it to work although I got it to work with an older verion (0.0.51)? Thanks!

I am trying to access the "move" event with the new vue2-leaflet so I can get the center rapidly updated.
