### ISSUE TITLE
Component as popup content

### ISSUE THREAD

**Issue by ivanjaros** [KoRiGaN/Vue2Leaflet#83]
Hi,
I would like to use more complex content for (marker) popup like structured html or better yet, a component, instead of only simple text. What would be a good way to do this? I see that bindPopup() method in Leaflet accepts html element as well but am still not sure what would be the best practice to do this.

**Comment by KoRiGaN** [comment]
Hi @ivanjaros,
 
Your question seems exactly like #35.
You can find some help there. I don't know what works or not as I haven't tried it myself. I may requiere some modification in Vue2Leaflet to work properly.  

Hope this helps.

Cheers,

Mickaël
