### ISSUE TITLE
localhost/:1 Uncaught SyntaxError: Unexpected token import

### ISSUE THREAD

**Issue by JamesxuWang** [KoRiGaN/Vue2Leaflet#85]
Hi,
when i tried to run the demo,the chrome tell me "localhost/:1 Uncaught SyntaxError: Unexpected token import";

Uncaught SyntaxError: Unexpected token import
    at Object.<anonymous> (app.js:696)
    at __webpack_require__ (app.js:556)
    at fn (app.js:87)
    at Object.<anonymous> (app.js:587)
    at __webpack_require__ (app.js:556)
    at app.js:579
    at app.js:582

Breakpoints is 
" (function(module, exports) {
	eval("import Vue from 'vue'\nimport App from './App'\n\n\nnew Vue({\n  el: '#main',\n  template: '<App/>',\n  components: { App }\n});\n\n//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIndlYnBhY2s6Ly8vLi9zcmMvbWFpbi5qcz8zNDc5Il0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiJBQUFBO0FBQ0E7OztBQUdBO0FBQ0E7QUFDQTtBQUNBLGVBQWU7QUFDZixDQUFDIiwiZmlsZSI6IjE4LmpzIiwic291cmNlc0NvbnRlbnQiOlsiaW1wb3J0IFZ1ZSBmcm9tICd2dWUnXG5pbXBvcnQgQXBwIGZyb20gJy4vQXBwJ1xuXG5cbm5ldyBWdWUoe1xuICBlbDogJyNtYWluJyxcbiAgdGVtcGxhdGU6ICc8QXBwLz4nLFxuICBjb21wb25lbnRzOiB7IEFwcCB9XG59KTtcblxuXG5cbi8vLy8vLy8vLy8vLy8vLy8vL1xuLy8gV0VCUEFDSyBGT09URVJcbi8vIC4vc3JjL21haW4uanNcbi8vIG1vZHVsZSBpZCA9IDE4XG4vLyBtb2R1bGUgY2h1bmtzID0gMCJdLCJzb3VyY2VSb290IjoiIn0=");
/***/ })"
how can i deal with it?

**Comment by KoRiGaN** [comment]
Hi @JamesxuWang,

Can you tell me which versions are you using ? 
Vue, Leaflet, Vue2Leaflet and Webpack so I can try to reproduce ?

Cheers,

Mickaël

**Comment by JamesxuWang** [comment]
Thank you for your reply，I am sorry it's too late to see it;
I was download it from GitHub 15 days ago, and follow the  **README.md** to run the demo,
C:\Users\Administrator
λ  npm vue -v
5.3.0
C:\Users\Administrator
λ  npm vue2leaflet -v
5.3.0
C:\Users\Administrator
λ  npm Webpack -v
5.3.0
,it's seem that you had updated version 10 days ago. i will try the new first.

 forgive my poor English! 
Thanks !

**Comment by KoRiGaN** [comment]
Hi @JamesxuWang,
The version you give is your npm version.
Can run `npm list [package name]` to get the current version of vue, vue2leaflet and webpack.

Thanks,

**Comment by JamesxuWang** [comment]
E:\vuele\node_modules\vue2-leaflet
λ  npm list vue2leaflet
vue2-leaflet@0.0.55 E:\vuele\node_modules\vue2-leaflet
`-- (empty)

E:\vuele\node_modules\vue2-leaflet
λ  npm list vue
vue2-leaflet@0.0.55 E:\vuele\node_modules\vue2-leaflet
`-- vue@2.4.3

E:\vuele\node_modules\vue2-leaflet
λ  npm list webpack
vue2-leaflet@0.0.55 E:\vuele\node_modules\vue2-leaflet
`-- webpack@2.7.0
i just want to run the demo.i try it again ,but it doesn't work, i don't know which step i had done was wrong.

Create a new folder
$ npm install vue2-leaflet --save
$ cd node_modules
$ cd vue2-leaflet
$ npm install
$ npm link
$ cd examples
$ npm link vue2-leaflet
$ npm install
$ npm run dev

**Comment by KoRiGaN** [comment]
Hi @JamesxuWang,

I have updated webpack to the last commit of the project. Can you give it a try and tell me if you still have the issue. 

It should fix it.

Micka
