### ISSUE TITLE
Styles

### ISSUE THREAD

**Issue by Youdaman** [KoRiGaN/Vue2Leaflet#9]
Took me a while to work out why my map wasn't loading properly (it was showing up full browser height with random tiles loading) -- you need to make sure the leaflet.css is included, either via a HTML link tag or in your component style via something like `@import "~leaflet/dist/leaflet.css";`

**Comment by KoRiGaN** [comment]
You're right that problem was not explained at all so I have added your comment into the readme file.

I don't know if there is a better way to handle this... Reopen this issue if a better solution than documentation exists.
