### ISSUE TITLE
[help] repeating markers on map with custom popup input

### ISSUE THREAD

**Issue by Fillah** [KoRiGaN/Vue2Leaflet#94]
Hey. 

Is it possible to make an enEach function on markers, which adds them on the map based on the Lat lng? By default the marker is looking like this:
`
marker: L.latLng(56.135180, 9.219490),`

Besides is there a solution for adding custom input side the popup? I saw this commit and tryed doing the same thing, but didn't seem to work:
https://github.com/ktmud/Vue2Leaflet/blob/b6a746a8c40b43c2f927d78e356673f01712f5fe/src/components/Popup.vue

My goal is to add a unique text and a button inside the popup

Thanks in advance

**Comment by KoRiGaN** [comment]
Hi @Fillah,

You can do nearly all you want following this working [example](https://jsfiddle.net/Boumi/5apzcqvu/).

The last part is having custom content like a button or any Vue component inside the popup. This does not work at the moment however it should work soon thanks to this PR #35.
I will try to merge this PR by the end of this week.

Mickaël

**Comment by KoRiGaN** [comment]
Hi @Fillah,

Having custom content like a button or any Vue component inside the popup should now work with release v0.0.57.

Please reopen this issue if you still have an issue.

Cheers,

Mickaël
