### ISSUE TITLE
Different icon for selected

### ISSUE THREAD

**Issue by delaneyj** [KoRiGaN/Vue2Leaflet#95]
I seem to be the first person to try to tag a question with vue2leaflet and have rep under 1500 so I can't post there.

How do you change the icon on a marker clicked `@l-click` event?  Basically I want to change the size/color of selected marker and reset the previous marker to default.  Not sure how to do this in terms of Vue2Leaflet's interface.

Using vue2 2.3.4 and vue2leaflet 0.0.55

**Comment by KoRiGaN** [comment]
Hi @delaneyj,

Here is a working [example](https://jsfiddle.net/Boumi/z3bmc1ex/1/).

Mickaël

**Comment by delaneyj** [comment]
Great!  Thank you so much!

**Comment by imudin** [comment]
@KoRiGaN This is working only the icon is clicked. How to make it work programmatically ?

**Comment by KoRiGaN** [comment]
@imudin this is done programmatically. In this example, it's done when a user clicks a marker but you can trigger it when you want (just swap the icon when you require as in the example).

**Comment by imudin** [comment]
@KoRiGaN Thank you for your reply! can you check this [example](https://jsfiddle.net/z3bmc1ex/19/)

**Comment by KoRiGaN** [comment]
@imudin do you have a problem with your example? Can you explain what is the issue?

**Comment by KoRiGaN** [comment]
@imudin you are using a method to get the icon which is not reactive so the marker doesn't update.
You should use a computed property instead.
Make sure you understand how reactivity works in vuejs. This 2 pages of the documentation should help:
- [Reactivity in depth](https://vuejs.org/v2/guide/reactivity.html)
- [List Caveats](https://vuejs.org/v2/guide/list.html#Caveats)
