### ISSUE TITLE
google maps tile layer

### ISSUE THREAD

**Issue by rhoseno98** [KoRiGaN/Vue2Leaflet#98]
hi, how can i use google maps on vue2-leaflet?
or is there plugin for this?

**Comment by KoRiGaN** [comment]
Hi @rhoseno98,

Google Maps Terms of user forbid any means of tile access other than through the Google Maps API. See [Leaflet FAQ](https://github.com/Leaflet/Leaflet/blob/master/FAQ.md#data-providers) for more information about it.

The solution in Leaflet is to use a plugin called [GoogleMutant](https://gitlab.com/IvanSanchez/Leaflet.GridLayer.GoogleMutant).

I never tried it but I think it should work with Vue2Leaflet.

Hope this helps,

Micka

**Comment by KoRiGaN** [comment]
Closing as no answer for a month.

**Comment by vinayakkulkarni** [comment]
Can you please make an example @KoRiGaN ?

**Comment by jperelli** [comment]
Just pinging you @vinayakkulkarni and @rhoseno98 to say that there is a plugin now for this that uses googlemutant, see the readme here.
