### ISSUE TITLE
Please write proper installation and setup instructions.

### ISSUE THREAD

**Issue by gkatsanos** [KoRiGaN/Vue2Leaflet#99]
Mentioning in the installation instructions would be pretty necessary. (to not have to guess the library name)

```
import Vue2Leaflet from 'vue2-leaflet';
```

**Comment by lmatab** [comment]
Thank a lot for this idea, It helped me

**Comment by KoRiGaN** [comment]
Thanks for spotting this.

I have added it to the Readme.

Micka
